local GetSpellInfo = GetSpellInfo;


--------------------
-- Spells by SpellId
--------------------
VUHDO_SPELL_ID_ABOLISH_DISEASE = GetSpellInfo(552);
VUHDO_SPELL_ID_ABOLISH_POISON = GetSpellInfo(2893);
VUHDO_SPELL_ID_ACTIVATE_FIRST_TALENT = GetSpellInfo(63645);
VUHDO_SPELL_ID_ACTIVATE_SECOND_TALENT = GetSpellInfo(63644);
VUHDO_SPELL_ID_ANCESTRAL_HEALING = GetSpellInfo(16176);
VUHDO_SPELL_ID_ANCESTRAL_SPIRIT = GetSpellInfo(2008);
VUHDO_SPELL_ID_BINDING_HEAL = GetSpellInfo(32546);
VUHDO_SPELL_ID_BLESSED_HEALING = GetSpellInfo(70772);
VUHDO_SPELL_ID_CHAIN_HEAL = GetSpellInfo(1064);
VUHDO_SPELL_ID_CIRCLE_OF_HEALING = GetSpellInfo(34861);
VUHDO_SPELL_ID_CLEANSE_SPIRIT = GetSpellInfo(51886);
VUHDO_SPELL_ID_CURE_DISEASE = GetSpellInfo(528);
VUHDO_SPELL_ID_CURE_TOXINS = GetSpellInfo(526);
VUHDO_SPELL_ID_DESPERATE_PRAYER = GetSpellInfo(19236);
VUHDO_SPELL_ID_DISPEL_MAGIC = GetSpellInfo(527);
VUHDO_SPELL_ID_DIVINE_AEGIS = GetSpellInfo(47509);
VUHDO_SPELL_ID_DIVINE_FAVOR = GetSpellInfo(20216);
VUHDO_SPELL_ID_DIVINE_ILLUMINATION = GetSpellInfo(31842);
VUHDO_SPELL_ID_DIVINE_INTERVENTION = GetSpellInfo(19752);
VUHDO_SPELL_ID_EARTHLIVING = GetSpellInfo(51945);
VUHDO_SPELL_ID_FLASH_HEAL = GetSpellInfo(2061);
VUHDO_SPELL_ID_FLASH_OF_LIGHT = GetSpellInfo(19750);
VUHDO_SPELL_ID_FOUNTAIN_OF_LIGHT = GetSpellInfo(71864);
VUHDO_SPELL_ID_GIFT_OF_THE_NAARU = GetSpellInfo(59547);
VUHDO_SPELL_ID_GRACE = GetSpellInfo(47516);
VUHDO_SPELL_ID_GREATER_HEAL = GetSpellInfo(2060);
VUHDO_SPELL_ID_GUARDIAN_SPIRIT = GetSpellInfo(47788);
VUHDO_SPELL_ID_HEAL = GetSpellInfo(2054);
VUHDO_SPELL_ID_HEALING_TOUCH = GetSpellInfo(5185);
VUHDO_SPELL_ID_HEALING_WAVE = GetSpellInfo(331);
VUHDO_SPELL_ID_HOLY_LIGHT = GetSpellInfo(635);
VUHDO_SPELL_ID_HOLY_SHOCK = GetSpellInfo(20473);
VUHDO_SPELL_ID_INNERVATE = GetSpellInfo(29166);
VUHDO_SPELL_ID_INSPIRATION = GetSpellInfo(14893);
VUHDO_SPELL_ID_LAY_ON_HANDS = GetSpellInfo(633);
VUHDO_SPELL_ID_LESSER_HEAL = GetSpellInfo(2050);
VUHDO_SPELL_ID_LESSER_HEALING_WAVE = GetSpellInfo(8004);
VUHDO_SPELL_ID_LIFEBLOOM = GetSpellInfo(33763);
VUHDO_SPELL_ID_MEND_PET = GetSpellInfo(136);
VUHDO_SPELL_ID_MISDIRECTION = GetSpellInfo(34477);
VUHDO_SPELL_ID_MOONKIN_FORM = GetSpellInfo(24858);
VUHDO_SPELL_ID_NOURISH = GetSpellInfo(50464);
VUHDO_SPELL_ID_PAIN_SUPPRESSION = GetSpellInfo(33206);
VUHDO_SPELL_ID_PALA_CLEANSE = GetSpellInfo(4987);
VUHDO_SPELL_ID_POAK = GetSpellInfo(64413);
VUHDO_SPELL_ID_POWERWORD_SHIELD = GetSpellInfo(17);
VUHDO_SPELL_ID_PRAYER_OF_HEALING = GetSpellInfo(596);
VUHDO_SPELL_ID_PRAYER_OF_MENDING = GetSpellInfo(33076);
VUHDO_SPELL_ID_PURGE = GetSpellInfo(370);
VUHDO_SPELL_ID_PURIFY = GetSpellInfo(1152);
VUHDO_SPELL_ID_REBIRTH = GetSpellInfo(20484);
VUHDO_SPELL_ID_REDEMPTION = GetSpellInfo(7328);
VUHDO_SPELL_ID_REGROWTH = GetSpellInfo(8936);
VUHDO_SPELL_ID_REJUVENATION = GetSpellInfo(774);
VUHDO_SPELL_ID_REMOVE_CURSE = GetSpellInfo(2782);
VUHDO_SPELL_ID_DISPEL_CURSE = GetSpellInfo(475);
VUHDO_SPELL_ID_RENEW = GetSpellInfo(139);
VUHDO_SPELL_ID_RENEWED_HOPE = GetSpellInfo(57470);
VUHDO_SPELL_ID_RESURRECTION = GetSpellInfo(2006);
VUHDO_SPELL_ID_REVIVE = GetSpellInfo(50769);
VUHDO_SPELL_ID_RIPTIDE = GetSpellInfo(61299);
VUHDO_SPELL_ID_SACRED_SHIELD = GetSpellInfo(53601);
VUHDO_SPELL_ID_SHADOWFORM = GetSpellInfo(15473);
VUHDO_SPELL_ID_SPELLSTEAL = GetSpellInfo(30449);
VUHDO_SPELL_ID_SWIFTMEND = GetSpellInfo(18562);
VUHDO_SPELL_ID_TRANQUILITY = GetSpellInfo(740);
VUHDO_SPELL_ID_TREE_OF_LIFE = GetSpellInfo(33891);-- Aura of the player having it 33891, Aura that it gives to others 65139
VUHDO_SPELL_ID_WILD_GROWTH = GetSpellInfo(48438);
VUHDO_SPELL_ID_IMPROVED_SHADOWFORM = GetSpellInfo(47569);
VUHDO_SPELL_ID_CYCLONE = GetSpellInfo(33786);

------------------
-- Buff categories
------------------


-- Priest
VUHDO_SPELL_ID_BUFFC_FEAR_WARD         = "01" .. GetSpellInfo(6346);
VUHDO_SPELL_ID_BUFFC_INNER_FIRE        = "02" .. GetSpellInfo(588);
VUHDO_SPELL_ID_BUFFC_SHADOW_FIEND      = "03" .. GetSpellInfo(34433);
VUHDO_SPELL_ID_BUFFC_POWER_INFUSION    = "04" .. GetSpellInfo(10060);
VUHDO_SPELL_ID_BUFFC_VAMPIRIC_EMBRACE  = "05" .. GetSpellInfo(15286);
VUHDO_SPELL_ID_BUFFC_LEVITATE          = "06" .. GetSpellInfo(1706);
VUHDO_SPELL_ID_BUFFC_PAIN_SUPPRESSION  = "07" .. GetSpellInfo(33206);

-- Shaman
VUHDO_SPELL_ID_BUFFC_HEROISM           = "08" .. GetSpellInfo(32182);
VUHDO_SPELL_ID_BUFFC_BLOODLUST         = "09" .. GetSpellInfo(2825)
VUHDO_SPELL_ID_BUFFC_EARTH_SHIELD      = "10" .. GetSpellInfo(974);
VUHDO_SPELL_ID_BUFFC_MANA_TIDE_TOTEM   = "11" .. GetSpellInfo(16190);
VUHDO_SPELL_ID_BUFFC_TIDAL_FORCE       = "12" .. GetSpellInfo(55198);
VUHDO_SPELL_ID_BUFFC_NATURES_SWIFTNESS = "13" .. GetSpellInfo(16188);

-- Paladin
VUHDO_SPELL_ID_BUFFC_BEACON_OF_LIGHT = "14" .. GetSpellInfo(53563);
VUHDO_SPELL_ID_BUFFC_RIGHTEOUS_FURY  = "15" .. GetSpellInfo(25780);
VUHDO_SPELL_ID_BUFFC_SACRED_SHIELD   = "16" .. GetSpellInfo(53601);

-- Druid
VUHDO_SPELL_ID_BUFFC_GIFT_OF_THE_WILD = "17" .. GetSpellInfo(21849);
VUHDO_SPELL_ID_BUFFC_THORNS           = "18" .. GetSpellInfo(467);

-- Warlock
VUHDO_SPELL_ID_BUFFC_DETECT_INVISIBILITY = "19" .. GetSpellInfo(132);

-- Mage
VUHDO_SPELL_ID_BUFFC_ARCANE_BRILLIANCE = "20" .. GetSpellInfo(23030);
VUHDO_SPELL_ID_BUFFC_ICE_BLOCK         = "21" .. GetSpellInfo(45438);
VUHDO_SPELL_ID_BUFFC_FOCUS_MAGIC       = "22" .. GetSpellInfo(54646);
VUHDO_SPELL_ID_BUFFC_COMBUSTION        = "23" .. GetSpellInfo(11129);
VUHDO_SPELL_ID_BUFFC_AMPLIFY_MAGIC     = "24" .. GetSpellInfo(1008);
VUHDO_SPELL_ID_BUFFC_DAMPEN_MAGIC      = "25" .. GetSpellInfo(604);
VUHDO_SPELL_ID_BUFFC_SLOW_FALL         = "26" .. GetSpellInfo(130);

-- Death Knights
VUHDO_SPELL_ID_BUFFC_HORN_OF_WINTER = "27" .. GetSpellInfo(57330);
VUHDO_SPELL_ID_BUFFC_BONE_SHIELD    = "28" .. GetSpellInfo(49222);

-- Warriors
VUHDO_SPELL_ID_BUFFC_VIGILANCE = "29" .. GetSpellInfo(50720);

-- Hunter
VUHDO_SPELL_ID_BUFFC_TRUESHOT_AURA = "30" .. GetSpellInfo(19506);



--------
-- Buffs
--------

-- Ascension
VUHDO_SPELL_ID_BUFF_MANAFORGED_BARRIER = GetSpellInfo(701463);



-- Priest
VUHDO_SPELL_ID_BUFF_PRAYER_OF_FORTITUDE = GetSpellInfo(21562);
VUHDO_SPELL_ID_BUFF_POWER_WORD_FORTITUDE = GetSpellInfo(1243);

VUHDO_SPELL_ID_BUFF_DIVINE_SPIRIT    = GetSpellInfo(14752);
VUHDO_SPELL_ID_BUFF_PRAYER_OF_SPIRIT = GetSpellInfo(27681);

VUHDO_SPELL_ID_BUFF_PRAYER_OF_SHADOW_PROTECTION = GetSpellInfo(27683);
VUHDO_SPELL_ID_BUFF_SHADOW_PROTECTION           = GetSpellInfo(976);

VUHDO_SPELL_ID_BUFF_FEAR_WARD        = GetSpellInfo(6346);
VUHDO_SPELL_ID_BUFF_INNER_FIRE       = GetSpellInfo(588);
VUHDO_SPELL_ID_BUFF_SHADOWFIEND      = GetSpellInfo(34433);
VUHDO_SPELL_ID_BUFF_POWER_INFUSION   = GetSpellInfo(10060);
VUHDO_SPELL_ID_BUFF_VAMPIRIC_EMBRACE = GetSpellInfo(15286);
VUHDO_SPELL_ID_BUFF_LEVITATE         = GetSpellInfo(1706);


-- Shaman
VUHDO_SPELL_ID_BUFF_FLAMETONGUE_TOTEM      = GetSpellInfo(8227);
VUHDO_SPELL_ID_BUFF_SEARING_TOTEM          = GetSpellInfo(3599);
VUHDO_SPELL_ID_BUFF_FIRE_ELEMENTAL_TOTEM   = GetSpellInfo(2894);
VUHDO_SPELL_ID_BUFF_FROST_RESISTANCE_TOTEM = GetSpellInfo(8181);
VUHDO_SPELL_ID_BUFF_MAGMA_TOTEM            = GetSpellInfo(8190);
VUHDO_SPELL_ID_BUFF_TOTEM_OF_WRATH         = GetSpellInfo(30706);

VUHDO_SPELL_ID_BUFF_GROUNDING_TOTEM         = GetSpellInfo(8177);
VUHDO_SPELL_ID_BUFF_NATURE_RESISTANCE_TOTEM = GetSpellInfo(10595);
VUHDO_SPELL_ID_BUFF_WINDFURY_TOTEM          = GetSpellInfo(8512);
VUHDO_SPELL_ID_BUFF_WRATH_OF_AIR_TOTEM      = GetSpellInfo(3738);
VUHDO_SPELL_ID_BUFF_SENTRY_TOTEM            = GetSpellInfo(6495);

VUHDO_SPELL_ID_BUFF_EARTHBIND_TOTEM         = GetSpellInfo(2484);
VUHDO_SPELL_ID_BUFF_STRENGTH_OF_EARTH_TOTEM = GetSpellInfo(8075);
VUHDO_SPELL_ID_BUFF_STONESKIN_TOTEM         = GetSpellInfo(8071);
VUHDO_SPELL_ID_BUFF_STONECLAW_TOTEM         = GetSpellInfo(5730);
VUHDO_SPELL_ID_BUFF_EARTH_ELEMENTAL_TOTEM   = GetSpellInfo(2062);
VUHDO_SPELL_ID_BUFF_TREMOR_TOTEM            = GetSpellInfo(8143);

VUHDO_SPELL_ID_BUFF_CLEANSING_TOTEM       = GetSpellInfo(8170);
VUHDO_SPELL_ID_BUFF_MANA_SPRING_TOTEM     = GetSpellInfo(5675);
VUHDO_SPELL_ID_BUFF_FIRE_RESISTANCE_TOTEM = GetSpellInfo(8184);
VUHDO_SPELL_ID_BUFF_HEALING_STREAM_TOTEM  = GetSpellInfo(5394);

VUHDO_SPELL_ID_BUFF_MANA_TIDE_TOTEM = GetSpellInfo(16190);

VUHDO_SPELL_ID_BUFF_HEROISM = GetSpellInfo(32182);

VUHDO_SPELL_ID_BUFF_BLOODLUST = GetSpellInfo(2825);

VUHDO_SPELL_ID_BUFF_EARTH_SHIELD = GetSpellInfo(974);

VUHDO_SPELL_ID_BUFF_FLAMETONGUE_WEAPON = GetSpellInfo(8024);
VUHDO_SPELL_ID_BUFF_ROCKBITER_WEAPON   = GetSpellInfo(8017);
VUHDO_SPELL_ID_BUFF_FROSTBRAND_WEAPON  = GetSpellInfo(8033);
VUHDO_SPELL_ID_BUFF_WINDFURY_WEAPON    = GetSpellInfo(8232);
VUHDO_SPELL_ID_BUFF_EARTHLIVING_WEAPON = GetSpellInfo(51730);

VUHDO_SPELL_ID_BUFF_LIGHTNING_SHIELD = GetSpellInfo(324);
VUHDO_SPELL_ID_BUFF_WATER_SHIELD     = GetSpellInfo(52127);

VUHDO_SPELL_ID_BUFF_TIDAL_FORCE = GetSpellInfo(55198);

VUHDO_SPELL_ID_BUFF_NATURES_SWIFTNESS = GetSpellInfo(16188);


-- Paladin
VUHDO_SPELL_ID_BUFF_GREATER_BLESSING_OF_MIGHT     = GetSpellInfo(25782);
VUHDO_SPELL_ID_BUFF_BLESSING_OF_MIGHT             = GetSpellInfo(19740);
VUHDO_SPELL_ID_BUFF_GREATER_BLESSING_OF_WISDOM    = GetSpellInfo(25894);
VUHDO_SPELL_ID_BUFF_BLESSING_OF_WISDOM            = GetSpellInfo(19742);
VUHDO_SPELL_ID_BUFF_GREATER_BLESSING_OF_SANCTUARY = GetSpellInfo(25899);
VUHDO_SPELL_ID_BUFF_BLESSING_OF_SANCTUARY         = GetSpellInfo(20911);
VUHDO_SPELL_ID_BUFF_GREATER_BLESSING_OF_THE_KINGS = GetSpellInfo(25898);
VUHDO_SPELL_ID_BUFF_BLESSING_OF_THE_KINGS         = GetSpellInfo(20217);

VUHDO_SPELL_ID_BUFF_RIGHTEOUS_FURY          = GetSpellInfo(25780);
VUHDO_SPELL_ID_BUFF_CRIMSON_CHAMPION        = GetSpellInfo(977730);

VUHDO_SPELL_ID_BUFF_DEVOTION_AURA           = GetSpellInfo(465);
VUHDO_SPELL_ID_BUFF_RETRIBUTION_AURA        = GetSpellInfo(7294);
VUHDO_SPELL_ID_BUFF_CONCENTRATION_AURA      = GetSpellInfo(19746);
VUHDO_SPELL_ID_BUFF_SHADOW_RESISTANCE_AURA  = GetSpellInfo(19876);
VUHDO_SPELL_ID_BUFF_FROST_RESISTANCE_AURA   = GetSpellInfo(19888);
VUHDO_SPELL_ID_BUFF_FIRE_RESISTANCE_AURA    = GetSpellInfo(19891);
VUHDO_SPELL_ID_BUFF_CRUSADER_AURA           = GetSpellInfo(32223);

VUHDO_SPELL_ID_BUFF_SEAL_OF_RIGHTEOUSNESS = GetSpellInfo(21084);
VUHDO_SPELL_ID_BUFF_SEAL_OF_BLOOD         = GetSpellInfo(31892);
VUHDO_SPELL_ID_BUFF_SEAL_OF_CORRUPTION    = GetSpellInfo(53736);
VUHDO_SPELL_ID_BUFF_SEAL_OF_MARTYR        = GetSpellInfo(53720);
VUHDO_SPELL_ID_BUFF_SEAL_OF_VENGEANCE     = GetSpellInfo(31801);
VUHDO_SPELL_ID_BUFF_SEAL_OF_JUSTICE       = GetSpellInfo(20164);
VUHDO_SPELL_ID_BUFF_SEAL_OF_LIGHT         = GetSpellInfo(20165);
VUHDO_SPELL_ID_BUFF_SEAL_OF_WISDOM        = GetSpellInfo(20166);
VUHDO_SPELL_ID_BUFF_SEAL_OF_COMMAND       = GetSpellInfo(20375);

VUHDO_SPELL_ID_BUFF_BEACON_OF_LIGHT = GetSpellInfo(53563);


-- Druid
VUHDO_SPELL_ID_BUFF_MARK_OF_THE_WILD = GetSpellInfo(1126);
VUHDO_SPELL_ID_BUFF_GIFT_OF_THE_WILD = GetSpellInfo(21849);
VUHDO_SPELL_ID_BUFF_THORNS           = GetSpellInfo(467);
VUHDO_SPELL_ID_BUFF_BEAR_FORM        = GetSpellInfo(5487);
VUHDO_SPELL_ID_BUFF_DIRE_BEAR_FORM   = GetSpellInfo(9634);


-- Warlock
VUHDO_SPELL_ID_BUFF_DEMON_SKIN = GetSpellInfo(687);
VUHDO_SPELL_ID_BUFF_DEMON_ARMOR = GetSpellInfo(706);
VUHDO_SPELL_ID_BUFF_FEL_ARMOR = GetSpellInfo(28176);
VUHDO_SPELL_ID_BUFF_DETECT_INVISIBILITY = GetSpellInfo(132);


-- Mage
VUHDO_SPELL_ID_BUFF_ARCANE_BRILLIANCE  = GetSpellInfo(23030);
VUHDO_SPELL_ID_BUFF_ARCANE_INTELLECT   = GetSpellInfo(1459);
VUHDO_SPELL_ID_BUFF_DALARAN_BRILLIANCE = GetSpellInfo(61316);
VUHDO_SPELL_ID_BUFF_DALARAN_INTELLECT  = GetSpellInfo(61024);
VUHDO_SPELL_ID_BUFF_ICE_BLOCK          = GetSpellInfo(45438);
VUHDO_SPELL_ID_BUFF_MOLTEN_ARMOR       = GetSpellInfo(30482);
VUHDO_SPELL_ID_BUFF_FROST_ARMOR        = GetSpellInfo(168);
VUHDO_SPELL_ID_BUFF_ICE_ARMOR          = GetSpellInfo(7302);
VUHDO_SPELL_ID_BUFF_MAGE_ARMOR         = GetSpellInfo(6117);
VUHDO_SPELL_ID_BUFF_FOCUS_MAGIC        = GetSpellInfo(54646);
VUHDO_SPELL_ID_BUFF_COMBUSTION         = GetSpellInfo(11129);
VUHDO_SPELL_ID_BUFF_AMPLIFY_MAGIC      = GetSpellInfo(1008);
VUHDO_SPELL_ID_BUFF_DAMPEN_MAGIC       = GetSpellInfo(604);
VUHDO_SPELL_ID_BUFF_SLOW_FALL          = GetSpellInfo(130);


-- Death Knight
VUHDO_SPELL_ID_BUFF_HORN_OF_WINTER  = GetSpellInfo(57330);
VUHDO_SPELL_ID_BUFF_BONE_SHIELD     = GetSpellInfo(49222);
VUHDO_SPELL_ID_BUFF_BLOOD_PRESENCE  = GetSpellInfo(48266);
VUHDO_SPELL_ID_BUFF_FROST_PRESENCE  = GetSpellInfo(48263);
VUHDO_SPELL_ID_BUFF_UNHOLY_PRESENCE = GetSpellInfo(48265);


-- Warrior
VUHDO_SPELL_ID_BUFF_BATTLE_SHOUT     = GetSpellInfo(6673);
VUHDO_SPELL_ID_BUFF_COMMANDING_SHOUT = GetSpellInfo(469);

VUHDO_SPELL_ID_BUFF_VIGILANCE = GetSpellInfo(50720);

-- Hunter
VUHDO_SPELL_ID_BUFF_TRUESHOT_AURA = GetSpellInfo(19506);

VUHDO_SPELL_ID_BUFF_ASPECT_OF_THE_BEAST = GetSpellInfo(13161);
VUHDO_SPELL_ID_BUFF_ASPECT_OF_THE_DRAGONHAWK = GetSpellInfo(61846);
VUHDO_SPELL_ID_BUFF_ASPECT_OF_THE_HAWK = GetSpellInfo(13165);
VUHDO_SPELL_ID_BUFF_ASPECT_OF_THE_MONKEY = GetSpellInfo(13163);
VUHDO_SPELL_ID_BUFF_ASPECT_OF_THE_PACK = GetSpellInfo(13159);
VUHDO_SPELL_ID_BUFF_ASPECT_OF_THE_VIPER = GetSpellInfo(34074);
VUHDO_SPELL_ID_BUFF_ASPECT_OF_THE_WILD = GetSpellInfo(20043);

----------
-- Debuffs
----------


VUHDO_SPELL_ID_DEBUFF_WEAKENED_SOUL = GetSpellInfo(6788);
VUHDO_SPELL_ID_DEBUFF_FROST_BLAST = GetSpellInfo(27808);
VUHDO_SPELL_ID_DEBUFF_ANCIENT_HYSTERIA = GetSpellInfo(19372);
VUHDO_SPELL_ID_DEBUFF_IGNITE_MANA = GetSpellInfo(19659);
VUHDO_SPELL_ID_DEBUFF_TAINTED_MIND = GetSpellInfo(16567);
VUHDO_SPELL_ID_DEBUFF_VIPER_STING = GetSpellInfo(67991);
VUHDO_SPELL_ID_DEBUFF_SILENCE = GetSpellInfo(30225);
VUHDO_SPELL_ID_DEBUFF_MAGMA_SHACKLES = GetSpellInfo(19496);
VUHDO_SPELL_ID_DEBUFF_FROSTBOLT = GetSpellInfo(116);
VUHDO_SPELL_ID_DEBUFF_PSYCHIC_HORROR = GetSpellInfo(64044);
VUHDO_SPELL_ID_DEBUFF_HUNTERS_MARK = GetSpellInfo(1130);
VUHDO_SPELL_ID_DEBUFF_SLOW = GetSpellInfo(31589);
VUHDO_SPELL_ID_DEBUFF_ARCANE_BLAST = GetSpellInfo(30451);
VUHDO_SPELL_ID_DEBUFF_IMPOTENCE = GetSpellInfo(51340);
VUHDO_SPELL_ID_DEBUFF_DECAYED_STR = GetSpellInfo(35760);
VUHDO_SPELL_ID_DEBUFF_DECAYED_INT = GetSpellInfo(31555);
VUHDO_SPELL_ID_DEBUFF_CRIPPLE = GetSpellInfo(18381);
VUHDO_SPELL_ID_DEBUFF_CHILLED = GetSpellInfo(12484);
VUHDO_SPELL_ID_DEBUFF_CONEOFCOLD = GetSpellInfo(120);
VUHDO_SPELL_ID_DEBUFF_CONCUSSIVESHOT = GetSpellInfo(5116);
VUHDO_SPELL_ID_DEBUFF_THUNDERCLAP = GetSpellInfo(8147);
VUHDO_SPELL_ID_DEBUFF_DAZED = GetSpellInfo(1604);
VUHDO_SPELL_ID_DEBUFF_FALTER = GetSpellInfo(32859);
VUHDO_SPELL_ID_DEBUFF_UNSTABLE_AFFL = GetSpellInfo(30108);
VUHDO_SPELL_ID_DEBUFF_DREAMLESS_SLEEP = GetSpellInfo(15822);
VUHDO_SPELL_ID_DEBUFF_GREATER_DREAMLESS = GetSpellInfo(24360);
VUHDO_SPELL_ID_DEBUFF_MAJOR_DREAMLESS = GetSpellInfo(28504);
VUHDO_SPELL_ID_DEBUFF_FROST_SHOCK = GetSpellInfo(46180);
VUHDO_SPELL_ID_DEBUFF_DELUSIONS_OF_JINDO = GetSpellInfo(24306);
VUHDO_SPELL_ID_DEBUFF_MIND_VISION = GetSpellInfo(2096);
VUHDO_SPELL_ID_DEBUFF_MUTATING_INJECTION = GetSpellInfo(28169);
VUHDO_SPELL_ID_DEBUFF_BANISH = GetSpellInfo(8994);
VUHDO_SPELL_ID_DEBUFF_PHASE_SHIFT = GetSpellInfo(4511);
