if (GetLocale() ~= "zhCN") then
	return;
end


-- New Options
-- @EXACT = false
VUHDO_I18N_SCANNERS = "监视器";
VUHDO_I18N_RESURRECT_SHORT = "监视器";
VUHDO_I18N_GENERAL = "基本设置";
VUHDO_I18N_CONFIG = "设置";
VUHDO_I18N_REBUFF = "补BUFF";
VUHDO_I18N_FORMAT = "格式";
VUHDO_I18N_BUFF_NAMES = "增益名称";
VUHDO_I18N_EMPTY_GROUPS = "无队员";
VUHDO_I18N_STATES = "状态";
VUHDO_I18N_CD_FLASHING = "冷却闪烁";
VUHDO_I18N_TIMERS = "计时器";
VUHDO_I18N_WHATEVER_FIRST = "... 或者... (优先执行第一条)";
VUHDO_I18N_SMART_DOTS = "智能...";
VUHDO_I18N_GROUP_BUFFS = "团队增益";
VUHDO_I18N_MODES = "模式";
VUHDO_I18N_EMERGENCY_MODE = "紧急模式";
VUHDO_I18N_NORMAL_MODE = "普通模式";
VUHDO_I18N_DETECT = "侦测";
VUHDO_I18N_RANGE = "范围";
VUHDO_I18N_ADD_NEW_PANEL = "添加面板";
VUHDO_I18N_HOLD_TO_TEST = "按住测试";
VUHDO_I18N_OWN_HOTS = "自身HOTS";
VUHDO_I18N_BAR_TEXTURE = "血条材质";
VUHDO_I18N_OTHER_POWERS = "其他";
VUHDO_I18N_MANA_BARS = "法力条";
VUHDO_I18N_LOSE = "损失";
VUHDO_I18N_ORDERING = "排序";
VUHDO_I18N_HIDE_EMPTY = "隐藏空面板";
VUHDO_I18N_ANCHOR = "锚点";
VUHDO_I18N_UNIT_ID = "目标 ID";
VUHDO_I18N_HEADER_TEXT = "标题材质";
VUHDO_I18N_TOOLTIPS = "提示";
VUHDO_I18N_SIZING = "缩放";
VUHDO_I18N_BUTTON_SIZE = "按键缩放";
VUHDO_I18N_TARGET_NAME = "目标名字";
VUHDO_I18N_PERCENT = "百分比";
VUHDO_I18N_MISSING = "损失";
VUHDO_I18N_REMAINING = "剩余";
VUHDO_I18N_HITPOINTS = "血量";
VUHDO_I18N_BAR_TEXT = "血条文字";
VUHDO_I18N_MAX_SWATCHES_PER_LINE = "每行最多";
VUHDO_I18N_MAX_BUFFS_PER_ROW = "每行最多显示增益";
VUHDO_I18N_REFRESH_RATE = "刷新率";
VUHDO_I18N_INDICATE_REBUFF_BELOW = "低于提示REBUFF";
VUHDO_I18N_IF_AT_LEAST = "... 至少";
VUHDO_I18N_PLAYERS_LOW = " 名队友.";
VUHDO_I18N_SIZE = "大小";
VUHDO_I18N_TEXTURE_NUM = "材质 #";
VUHDO_I18N_TEXT_SIZE = "文字大小";
VUHDO_I18N_X_SPACING = "X-间距";
VUHDO_I18N_Y_SPACING = "Y-间距";
VUHDO_I18N_X_GAP = "X-间隙";
VUHDO_I18N_Y_GAP = "Y-间隙";

-- General Labels
-- @EXACT = false
VUHDO_I18N_CANCEL = "取消";
VUHDO_I18N_SHOW = "显示";
VUHDO_I18N_BARS = "条"
VUHDO_I18N_COLOR = "颜色";
VUHDO_I18N_COLORS = "颜色";
VUHDO_I18N_GENERAL_SHORT = "基本设置";
VUHDO_I18N_CUSTOM = "自定义";
VUHDO_I18N_MOUSE = "鼠标";
VUHDO_I18N_STANDARD = "标准";
VUHDO_I18N_POSITION = "位置";
VUHDO_I18N_SCALE = "缩放";
VUHDO_I18N_ENABLE = "开启";
VUHDO_I18N_BACKGROUND = "背景";
VUHDO_I18N_GROUPED = "数值";
VUHDO_I18N_SORT_BY = "按...排列";
VUHDO_I18N_NAME = "名字";
VUHDO_I18N_MAX_HP = "最大血量";
VUHDO_I18N_MAX_COLUMNS = "最大列数";
VUHDO_I18N_MAX_ROWS = "最大行数";
VUHDO_I18N_CLEAR_PANELS_CONFIRM = "清除面板设定!\nYA'确定?";
VUHDO_I18N_BUFF_NAME = "增益名称";
VUHDO_I18N_BUFF_ON_PLAYER = "玩家名字:";
VUHDO_I18N_ALWAYS = "总是";
VUHDO_I18N_NEVER = "从不";
VUHDO_I18N_BUFF_PANEL_BG = "面板";


-- VuhDoOptionsGeneral.lua
-- @EXACT = false
VUHDO_I18N_CLEANSE = "驱散";
VUHDO_I18N_RESURRECT = "复活";
VUHDO_I18N_SMART_CAST_OO_COMBAT = "智能施法";
VUHDO_I18N_IGNORE_IRRELEVANT = "将被忽略的减益法术";
VUHDO_I18N_BY_CLASS = "职业";
VUHDO_I18N_MOVEMENT_IMPAIRING = "减速";
VUHDO_I18N_BY_DURATION = "短周期";
VUHDO_I18N_BY_NON_HARMFUL = "无害的";
VUHDO_I18N_SHOW_ALL = "Show All";
VUHDO_I18N_ESTIMATE = "标准距离";
VUHOD_I18N_BY_SPELL = "指定技能";
VUHDO_I18N_SHOW_INC = "治疗输入";
VUHDO_I18N_SHOW_OWN_HEAL = "自己";
VUHDO_I18N_SHOW_OVERHEAL = "过量治疗";
VUHDO_I18N_OPERATION_MODE = "显示方式";
VUHDO_I18N_MAX_EMERGENCIES = "最大高亮";
VUHDO_I18N_RELVEVANCE = "高于则不高亮";
VUHDO_I18N_NEUTRAL_HEALBOT = "正常显示";
VUHDO_I18N_EMERGENCY_PERCENT = "血量低于设定数值";
VUHDO_I18N_EMERGENCY_MOST_MISSING = "最多损失";
VUHDO_I18N_EMERGENCY_LEAST_LEFT = "最少剩余血量";



-- VuhDoFormButtonColor.lua
-- @EXACT = false
-- Labels
VUHDO_I18N_TEXT = "文本";
VUHDO_I18N_DEBUFFS = "减益";
VUHDO_I18N_ANOMALIES = "时间";
VUHDO_I18N_OPACITY = "透明度";



-- VuhDoFormButtonSize.lua
-- @EXACT = false
VUHDO_I18N_PANEL = "面板";
VUHDO_I18N_SPACING = "填白";
VUHDO_I18N_BAR_HEIGHT = "高度";
VUHDO_I18N_TARGETS = "目标";
VUHDO_I18N_BAR_TEXTURE = "材质";
VUHDO_I18N_HEIGHT = "高度";
VUHDO_I18N_BAR_WIDTH = "宽度";
VUHDO_I18N_WIDTH = "宽度";
VUHDO_I18N_HEADERS = "标题";
VUHDO_I18N_CLASS_COL = "职业 Col.";
--



-- VuhDoOptionsSpell.lua
-- @EXACT = false
VUHDO_I18N_KEY_MODIFIES = "组合键";
VUHDO_I18N_KEY_NONE = "无";
VUHDO_I18N_ALT = "Alt";
VUHDO_I18N_CTRL = "Ctrl";
VUHDO_I18N_SHIFT = "Shift";
VUHDO_I18N_LEFT_BUTTON = "鼠标左键";
VUHDO_I18N_RIGHT_BUTTON = "鼠标右键";
VUHDO_I18N_MIDDLE_BUTTON = "鼠标中键";
VUHDO_I18N_BUTTON_4 = "鼠标键4";
VUHDO_I18N_BUTTON_5 = "鼠标键5";
VUHDO_I18N_MOUSE_KEY = "鼠标键位";
VUHDO_I18N_IN_MACROS_USE = "(在宏中用 \"vuhdo\" 替代目标名称)";
VUHDO_I18N_SPELL_STATIC = "或target(目标)/focus(焦点)/assist(协助)/menu(菜单)/tell(密语)/dropdown(下拉)";
VUHDO_I18N_NAME_TIP = "可填写法术、宏或物品名称";
VUHDO_I18N_PLUS_SHIFT = "+Shift";
VUHDO_I18N_PLUS_CTRL_SHIFT = "+Ctrl+Shift";
VUHDO_I18N_PLUS_CTRL = "+Ctrl";



-- VuhDoTooltipConfig.lua
-- @EXACT = false
VUHDO_I18N_AROUND_PANEL = "周边面板";
VUHDO_I18N_SHOW_IN_FIGHT = "战斗中";




-- New Options - Tooltips
-- @EXACT = false
VUHDO_I18N_TT_001 = "设定你需要VuhDo处理的增益";
VUHDO_I18N_TT_002 = "选择增益显示面板外观";
VUHDO_I18N_TT_003 = "选择增益材质和不同计时器条件的颜色";
VUHDO_I18N_TT_004 = "调整计时器设置和选择增益版本";

VUHDO_I18N_TT_005 = "调节VuhDo增益监视全局缩放";
VUHDO_I18N_TT_006 = "设置每行最大增益个数";
VUHDO_I18N_TT_007 = "设置每列最大增益个数";
VUHDO_I18N_TT_008 = "设置增益显示的刷新率";
VUHDO_I18N_TT_009 = "在标题栏显示增益名称";
VUHDO_I18N_TT_010 = "显示空白小组的增益";
VUHDO_I18N_TT_011 = "开启增益监视";

VUHDO_I18N_TT_012 = "选择增益持续时间充足的提示颜色";
VUHDO_I18N_TT_013 = "选择增益剩余时间较短的提示颜色";
VUHDO_I18N_TT_014 = "选择增益（部分）缺失的提示颜色";
VUHDO_I18N_TT_015 = "选择颜色以提示所有可释放增益目标均不在施法范围内，无法提供增益";
VUHDO_I18N_TT_016 = "选择增益技能冷却中的提示颜色";
VUHDO_I18N_TT_017 = "选择颜色以提示该小组目前无成员";
VUHDO_I18N_TT_018 = "选择增益面板背景颜色";
VUHDO_I18N_TT_019 = "选择增益边界颜色";
VUHDO_I18N_TT_020 = "选择增益监视面板边界颜色";

VUHDO_I18N_TT_021 = "增益法术冷却结束立即刷新增益";
VUHDO_I18N_TT_022 = "选择判定增益剩余时间低的临界百分值（相对增益总时长的百分比）";
VUHDO_I18N_TT_023 = "选择判定增益剩余时间低的临界值（绝对时间长度）";
VUHDO_I18N_TT_024 = "根据以下滑块为团队成员补充增益.";
VUHDO_I18N_TT_025 = "总是使用单人版增益法术. (比如施法材料用尽的情况下...)";
VUHDO_I18N_TT_026 = "总是使用队伍/团队版增益法术";
VUHDO_I18N_TT_027 = "至少有……名队友增益剩余时间低时才使用队伍/团队版增益法术.";

VUHDO_I18N_TT_028 = "根据玩家所处状态设置颜色.";
VUHDO_I18N_TT_029 = "根据已选定显示模式设定颜色.";

VUHDO_I18N_TT_031 = "点击修改紧急指示颜色 (注意：必须在有一个紧急情况被激活的情况下).";
VUHDO_I18N_TT_032 = "点击修改玩家处于非紧急状态下的指示颜色 (注意：必须在有一个紧急情况被激活的情况下).";
VUHDO_I18N_TT_033 = "点击修改满血玩家颜色. (参见: 主设置面板中的 \"Irrelevant\" 滑条)";
VUHDO_I18N_TT_034 = "点击修改玩家正获得治疗颜色. (注意：需要获得治疗显示开启)";
VUHDO_I18N_TT_035 = "点击修改施法距离之外玩家颜色. (注意：需要距离检测开启)";

VUHDO_I18N_TT_036 = "变色指示死亡玩家.";
VUHDO_I18N_TT_037 = "变色指示离线玩家.";
VUHDO_I18N_TT_038 = "变色指示被精神控制的玩家.";
VUHDO_I18N_TT_039 = "改变获得仇恨指示颜色.";
VUHDO_I18N_TT_040 = "变色指示中毒玩家.";
VUHDO_I18N_TT_041 = "变色指示中疾病玩家.";
VUHDO_I18N_TT_042 = "变色指示中诅咒玩家.";
VUHDO_I18N_TT_043 = "变色指示受魔法减益影响的玩家.";

VUHDO_I18N_TT_044 = "设置VuhDo的基本行为.";
VUHDO_I18N_TT_045 = "选择VuhDo监测的信息.";

VUHDO_I18N_TT_046 = "让VuhDo在自动选择合适的治疗法术.";
VUHDO_I18N_TT_047 = "自动选择合适的法术等级（2.3后已经没用了）";
VUHDO_I18N_TT_048 = "治疗前自动驱散.";
VUHDO_I18N_TT_049 = "自动救人.";
VUHDO_I18N_TT_050 = "开启智能施法.";
VUHDO_I18N_TT_051 = "监测玩家获得仇恨.";
VUHDO_I18N_TT_052 = "战斗记录分析. 分析战斗记录对提高很有帮助.";
VUHDO_I18N_TT_053 = "整体治疗视觉效果选择. 大型团队活动以外情况下，建议选择 \"正常显示\".";
VUHDO_I18N_TT_054 = "设定最大血量危急玩家显示数目. 默认无限制";
VUHDO_I18N_TT_055 = "设定一个健康血量百分比临界值，意味着血量高于这个百分比的玩家将被认为是健康的，其血条也将被一定程度上淡化";

VUHDO_I18N_TT_056 = "忽略无害的减益魔法(根据减益性质判定).";
VUHDO_I18N_TT_057 = "忽略降低移动速度的减益.";
VUHDO_I18N_TT_058 = "忽略作用周期非常短的减益.";
VUHDO_I18N_TT_059 = "忽略与职业无关的减益(例如盗贼--法力燃烧).";
VUHDO_I18N_TT_060 = "只显示你可以驱散的减益. 不勾选则显示全部减益.";
VUHDO_I18N_TT_061 = "开启一般减益侦测.";
VUHDO_I18N_TT_062 = "过量治疗时血条闪烁.";
VUHDO_I18N_TT_063 = "显示你对自己的治疗，这可能对某些玩家造成误导.";
VUHDO_I18N_TT_064 = "指示正在获得的（未读完的）治疗输入. 可能对降低过量治疗有所帮助.";
VUHDO_I18N_TT_065 = "选择检查玩家是否在治疗范围内的刷新率. 注意：较低的设定值可能导致系统表现的下降.";
VUHDO_I18N_TT_066 = "检查一个 \"典型的\" 治疗法术的距离. 如果您不具有任何增益法术也选此项.";
VUHDO_I18N_TT_067 = "输入一个法术名称,该法术将被用于检测距离.";
VUHDO_I18N_TT_068 = "用右边的法术施放距离进行距离检测.";
VUHDO_I18N_TT_069 = "开启距离检测.";

VUHDO_I18N_TT_070 = "选择HOT图标基于条高度的缩放百分比";
VUHDO_I18N_TT_071 = "血条内部右侧显示HOT图标";
VUHDO_I18N_TT_072 = "血条内部左侧显示HOT图标";
VUHDO_I18N_TT_073 = "血条外部右侧显示HOT图标";
VUHDO_I18N_TT_074 = "血条外部左侧显示HOT图标";
VUHDO_I18N_TT_075 = "在血条侧显示自己的HOT";
VUHDO_I18N_TT_076 = "通过名字选择你最喜欢的条背景.";
VUHDO_I18N_TT_077 = "移动修改条的背景纹理.";
VUHDO_I18N_TT_078 = "修改面板背景颜色.";
VUHDO_I18N_TT_079 = "修改面板边界颜色.";
VUHDO_I18N_TT_080 = "在法力条之外单独显示能量条.";
VUHDO_I18N_TT_081 = "拖动缩放法力条.";
VUHDO_I18N_TT_082 = "在面板中显示法力条";

VUHDO_I18N_TT_083 = "在 \"队伍\" 选项开启时，设置每行最大小组数.";
VUHDO_I18N_TT_084 = "在治疗面板上松散显示所有玩家按钮，而不进行队伍或职业排序，开启此选项将自动隐藏标题.";
VUHDO_I18N_TT_085 = "在选定面板中显示所有玩家按钮并按他们的小队/职业排列";
VUHDO_I18N_TT_086 = "勾选后，团队中的无成员小队将被隐藏. (仅在 \"队伍\" 选项开启时有效).";
VUHDO_I18N_TT_087 = "选择每行的最大列数Selects the max. number of columns per row before a line break.";
VUHDO_I18N_TT_088 = "面板锚点左上方.";
VUHDO_I18N_TT_089 = "面板锚点在右上方.";
VUHDO_I18N_TT_090 = "面板锚点在左下方.";
VUHDO_I18N_TT_091 = "面板锚点在右下方.";
VUHDO_I18N_TT_092 = "使玩家在面板中按默认团队界面排列.";
VUHDO_I18N_TT_093 = "使玩家在面板中按最大血量排列.";
VUHDO_I18N_TT_094 = "使玩家在面板中按姓氏字母排列.";

VUHDO_I18N_TT_095 = "拖动修改标题高度.";
VUHDO_I18N_TT_096 = "拖动修改标题与生命/法力条间距.";
VUHDO_I18N_TT_097 = "显示标题. (注意: 必须先选择 \"基本选项\"=>\"队伍\".)";
VUHDO_I18N_TT_098 = "移动修改标题背景材质.";
VUHDO_I18N_TT_099 = "按名字选择标题背景材质.";
VUHDO_I18N_TT_100 = "移动调节标题背景基于条宽的百分比.";
VUHDO_I18N_TT_101 = "标题文本缩放.";
VUHDO_I18N_TT_102 = "按职业颜色显示标题文本. (注意: 仅当标题与职业关联时有效)";
VUHDO_I18N_TT_103 = "修改标题背景与文本颜色.";

VUHDO_I18N_TT_104 = "设置面板标题外观";
VUHDO_I18N_TT_105 = "设置面板基础外观.";
VUHDO_I18N_TT_106 = "设置提示样式";
VUHDO_I18N_TT_107 = "血条文本内容与显示方式配置.";
VUHDO_I18N_TT_108 = "选择是否在面板中显示玩家目标以及它们的样式.";
VUHDO_I18N_TT_109 = "设置血条的宽度、高度以及填白、空隙.";
VUHDO_I18N_TT_110 = "设置血条外观、面板背景及边界颜色.";
VUHDO_I18N_TT_111 = "点击将使当前子菜单设置应用于你所有的面板！";

VUHDO_I18N_TT_112 = "设置血条水平间隙.";
VUHDO_I18N_TT_113 = "设置血条纵向间隙.";
VUHDO_I18N_TT_114 = "设定边界与血条间的纵向距离.";
VUHDO_I18N_TT_115 = "设定边界与血条间的水平距离.";
VUHDO_I18N_TT_116 = "设定面板血条高度.";
VUHDO_I18N_TT_117 = "设定面板血条宽度.";

VUHDO_I18N_TT_118 = "调节目标条与血条间隙.";
VUHDO_I18N_TT_119 = "显示当前面板中玩家的目标.";
VUHDO_I18N_TT_120 = "移动修改当前面板目标条宽度.";
VUHDO_I18N_TT_121 = "同时显示团队图标与目标名字.";
VUHDO_I18N_TT_122 = "显示团队图标而不显示目标名字. (如果存在团队图标)";
VUHDO_I18N_TT_123 = "总是显示目标名字而不显示团队图标";
VUHDO_I18N_TT_124 = "目标名字文本缩放.";

VUHDO_I18N_TT_126 = "血量文本百分比显示.";
VUHDO_I18N_TT_127 = "血量文本按损失数值显示.";
VUHDO_I18N_TT_128 = "血量文本按剩余数值显示.";
VUHDO_I18N_TT_129 = "血量文本在玩家名字右边";
VUHDO_I18N_TT_130 = "血量文本在玩家名字左边";
VUHDO_I18N_TT_131 = "血量文本在玩家名字下边.";
VUHDO_I18N_TT_132 = "血量文本在玩家名字上边.";
VUHDO_I18N_TT_133 = "在血条上显示血量文本.";
VUHDO_I18N_TT_134 = "血条文本缩放.";
VUHDO_I18N_TT_135 = "玩家名字用职业颜色显示.";
VUHDO_I18N_TT_136 = "修改血条文本颜色.";
VUHDO_I18N_TT_137 = "修改各血条背景颜色. (注意：不是面板背景颜色！).";

VUHDO_I18N_TT_138 = "解锁提示面板，可随意移动. 拖动提示面板并决定其位置.";
VUHDO_I18N_TT_139 = "开启工具提示鼠标指针跟随. (注意：可能会影响操作)";
VUHDO_I18N_TT_140 = "使用暴雪标准界面工具提示位置.";
VUHDO_I18N_TT_141 = "通常显示工具提示.";
VUHDO_I18N_TT_142 = "在战斗中也显示工具提示";
VUHDO_I18N_TT_143 = "工具提示全局缩放";
VUHDO_I18N_TT_144 = "选择工具提示背景颜色.";
VUHDO_I18N_TT_145 = "选择工具提示边界颜色.";

VUHDO_I18N_TT_146 = "设定组合键 \"ALT+SHIFT\"绑定技能.";
VUHDO_I18N_TT_147 = "设定组合键 \"CTRL\".绑定技能";
VUHDO_I18N_TT_148 = "设定组合键 \"CTRL+SHIFT\".绑定技能";
VUHDO_I18N_TT_149 = "设定组合键 \"ALT+CTRL+SHIFT\".绑定技能";
VUHDO_I18N_TT_150 = "设定无组合键使用时的绑定技能";
VUHDO_I18N_TT_151 = "设定组合键 \"ALT\".绑定技能";
VUHDO_I18N_TT_152 = "设定组合键 \"SHIFT\".绑定技能";
VUHDO_I18N_TT_153 = "设定组合键 \"ALT+CTRL\".绑定技能";

VUHDO_I18N_TT_154 = "设置完成. 确认所有修改.";
VUHDO_I18N_TT_155 = "中止设置. 放弃所有修改.";

VUHDO_I18N_TT_156 = "当增益剩余次数大于一次（如心灵之火）时，隐藏计数.";
VUHDO_I18N_TT_157 = "修改法力、能量或怒气颜色."
VUHDO_I18N_TT_158 = "选择法力条颜色."
VUHDO_I18N_TT_159 = "选择怒气条颜色."
VUHDO_I18N_TT_160 = "选择能量条颜色."
VUHDO_I18N_TT_161 = "选择符文能量颜色."
VUHDO_I18N_TT_162 = "打开仇恨、获得仇恨显示设置面板"
VUHDO_I18N_TT_163 = "杂项设置."
VUHDO_I18N_TT_164 = "保存或读取皮肤便于外观快速设置."
VUHDO_I18N_TT_165 = "不再在队伍/职业面板中显示主坦克."
VUHDO_I18N_TT_166 = "不再显示队伍/职业面板显示玩家目标."
VUHDO_I18N_TT_167 = "不再将自己所在小队作为常规小队进行显示. (通常你会有本小队框体或者开启了VuhDo队伍选项中的 \"我的小队\" )"
VUHDO_I18N_TT_168 = "在玩家名字前方显示暂离、离线或死亡标签"
VUHDO_I18N_TT_169 = "隐藏暴雪队伍框体."
VUHDO_I18N_TT_170 = "隐藏暴雪玩家框体."
VUHDO_I18N_TT_171 = "只在法术的施放目标显示多目标HOT."
VUHDO_I18N_TT_172 = "多目标HOT显示在所有受影响者上. 警告：开启此项可能导致系统表现下降!"
VUHDO_I18N_TT_173 = "选择HOT更新的刷新率" -- 173
VUHDO_I18N_TT_174 = "输入已存在的皮肤名称进行读取、覆盖或删除操作，或将当前皮肤另存为..."
VUHDO_I18N_TT_175 = "选择皮肤. 皮肤是对视觉效果的总体设置，如颜色、材质等."
VUHDO_I18N_TT_176 = "输入已存在的皮肤名称进行读取、覆盖或删除操作，或将当前皮肤另存为..."
VUHDO_I18N_TT_177 = "选择一套布局. 这些设置包括了缩放、格式和布局."
VUHDO_I18N_TT_178 = "选择目标仇恨的相对临界值, 仇恨超过这个临界值的玩家在仇恨条上的显示由青色转为红色"
VUHDO_I18N_TT_179 = "设置仇恨条高度"
VUHDO_I18N_TT_180 = "在每个治疗按键的上下方用脉动线显示仇恨过高（橙色）和获得仇恨目标（红色）"
VUHDO_I18N_TT_181 = "在治疗按键上方显示仇恨情况条（百分比）."
VUHDO_I18N_TT_182 = "仇恨情况整体监视" -- 182
VUHDO_I18N_TT_183 = "选择仇恨目标/仇恨监视刷新率"
VUHDO_I18N_TT_184 = "选择要在仇恨目标名字左旁边显示的文字"
VUHDO_I18N_TT_185 = "在仇恨目标名字上添加文字提示"
VUHDO_I18N_TT_186 = "在仇恨目标单元按键下方作划线指示"
VUHDO_I18N_TT_187 = "由VuhDo进行仇恨目标监测"
VUHDO_I18N_TT_188 = "选择要在仇恨目标名字右旁边显示的文字" -- 188
VUHDO_I18N_TT_189 = "使用当前小队/团队进行测试."
VUHDO_I18N_TT_190 = "选择以显示测试5人队伍/团队."
VUHDO_I18N_TT_191 = "选择以显示测试10人团队."
VUHDO_I18N_TT_192 = "选择以显示测试25人团队."
VUHDO_I18N_TT_193 = "选择以显示测试40人团队." -- 193
VUHDO_I18N_TT_194 = "开启此项则血条颜色不再根据玩家血量发生变化（从绿到红）而是始终显示职业颜色."
VUHDO_I18N_TT_195 = "选择标题字体"
VUHDO_I18N_TT_196 = "标题背景颜色使用职业颜色."
VUHDO_I18N_TT_197 = "选择目标姓名文本颜色." -- 197
VUHDO_I18N_TT_198 = "选择使用鼠标点击施放的法术."
VUHDO_I18N_TT_199 = "选择鼠标滑过时通过键盘施放的法术."
VUHDO_I18N_TT_200 = "选择在其变为可用时立即使用的饰品/瞬发技能."
VUHDO_I18N_TT_201 = "输入要在施放治疗法术前使用的瞬发技能名称. 注意：这个技能不能有公共冷却!"
VUHDO_I18N_TT_202 = "输入要在施放治疗法术前使用的瞬发技能名称. 注意：这个技能不能有公共冷却!"
VUHDO_I18N_TT_203 = "在施放治疗法术前先使用右边的技能. 注意：这个技能不能有公共冷却!"
VUHDO_I18N_TT_204 = "在施放治疗法术前先使用右边的技能. 注意：这个技能不能有公共冷却!" -- 204
VUHDO_I18N_TT_205 = "施放治疗法术前使用二号饰品（人物界面中下面的饰品）. 注意：这个技能不能有公共冷却!"
VUHDO_I18N_TT_206 = "施放治疗法术前使用一号饰品（人物界面中上面的饰品）. 注意：这个技能不能有公共冷却!"
VUHDO_I18N_TT_207 = "不在战斗中时也能自动触发饰品."
VUHDO_I18N_TT_208 = "当技能为周期性治疗法术时也能自动触发饰品."
VUHDO_I18N_TT_209 = "开启/关闭饰品或技能的自动使用或施放."
VUHDO_I18N_TT_210 = "输入开始复活时要说的话，用 \"vuhdo\" 代替名字";
VUHDO_I18N_TT_211 = "启用复活时说话，用 \"vuhdo\" 代替名字";
VUHDO_I18N_TT_212 = "完全隐藏空面板";
VUHDO_I18N_TT_213 = "不在 \"辅助坦克\" 面板显示焦点目标.";
VUHDO_I18N_TT_214 = "不在常规团队/小队面板中显示协助坦克.";
VUHDO_I18N_TT_215 = "脱离战斗时对正在消失的BUFF进行补充。必须先在VuhDo增益监视中启用该增益并为其指定颜色.";
VUHDO_I18N_TT_216 = "显示从团队/小队其他玩家获得的治疗.";
VUHDO_I18N_TT_217 = "在血条生命值文本中添加正在获得/过量治疗";
VUHDO_I18N_TT_218 = "调整过量治疗文本缩放.";
VUHDO_I18N_TT_219 = "在血条上用额外的白字显示过量治疗.";
VUHDO_I18N_TT_220 = "在获得仇恨目标的玩家周围显示红色边框.";
VUHDO_I18N_TT_221 = "在战斗中也显示正在消失的增益条";
VUHDO_I18N_TT_222 = "以文本颜色显示正在消失的增益";
VUHDO_I18N_TT_223 = "以条颜色显示正在消失的增益";
VUHDO_I18N_TT_224 = "HOT方块基本颜色设定菜单";
VUHDO_I18N_TT_225 = "HOT方块颜色高级设置菜单";
VUHDO_I18N_TT_226 = "设置职业颜色";
VUHDO_I18N_TT_227 = "选择条背景职业颜色与条颜色的相对亮度.";
VUHDO_I18N_TT_228 = "以职业颜色显示宠物.";
VUHDO_I18N_TT_229 = "选择战士颜色";
VUHDO_I18N_TT_230 = "选择盗贼颜色";
VUHDO_I18N_TT_231 = "选择猎人颜色";
VUHDO_I18N_TT_232 = "选择圣骑士颜色";
VUHDO_I18N_TT_233 = "选择术士颜色";
VUHDO_I18N_TT_234 = "选择萨满颜色";
VUHDO_I18N_TT_235 = "选择德鲁伊颜色";
VUHDO_I18N_TT_236 = "选择牧师颜色";
VUHDO_I18N_TT_237 = "选择法师颜色";
VUHDO_I18N_TT_238 = "选择死亡骑士颜色";
VUHDO_I18N_TT_239 = "选择宠物颜色";
VUHDO_I18N_TT_240 = "显示HOT剩余次数，如果选择了方块而不是HOT图标，则显示四个小三角形作为指示.";
VUHDO_I18N_TT_241 = "在左侧以文本颜色显示HOT剩余次数.";
VUHDO_I18N_TT_242 = "以背景颜色在左侧显示HOT叠加层数Check to display number of HoT appliances by background color to the left.";
VUHDO_I18N_TT_243 = "选择HOT第二跳的颜色";
VUHDO_I18N_TT_244 = "选择HOT第三跳的颜色";
VUHDO_I18N_TT_245 = "选择HOT第四跳的颜色";
VUHDO_I18N_TT_246 = "选择1号HOT条颜色";
VUHDO_I18N_TT_247 = "选择2号HOT条颜色";
VUHDO_I18N_TT_248 = "选择3号HOT条颜色";
VUHDO_I18N_TT_249 = "选择1号HOT方块颜色";
VUHDO_I18N_TT_250 = "选择2号HOT方块颜色";
VUHDO_I18N_TT_251 = "选择3号HOT方块颜色";
VUHDO_I18N_TT_252 = "选择4号HOT方块颜色";
VUHDO_I18N_TT_253 = "选择5号HOT方块颜色";
VUHDO_I18N_TT_254 = "选择剩余时间较短的HOT颜色";
VUHDO_I18N_TT_255 = "选择应用时间警报颜色并显示高速侦测（0.1秒）的时间.";
VUHDO_I18N_TT_256 = "显示HOT计数器和计时器文本轮廓.";
VUHDO_I18N_TT_257 = "在HOT计数器和计时器文本后添加阴影.";
VUHDO_I18N_TT_258 = "HOT剩余时间低于左侧设定值时显示警报颜色.";
VUHDO_I18N_TT_259 = "显示HOT方块/图标. 不选则只显示文本.";
VUHDO_I18N_TT_260 = "当HOT剩余时间很短时图标/方块淡出显示.";
VUHDO_I18N_TT_261 = "选择自定义减益颜色";
VUHDO_I18N_TT_262 = "减益图标浮动.";
VUHDO_I18N_TT_263 = "选择需要显示的减益.";
VUHDO_I18N_TT_264 = "选择需要显示的自定义增、减益.";
VUHDO_I18N_TT_265 = "面板向导帮助你快速设置面板组.";
VUHDO_I18N_TT_266 = "用图标显示自定义增、减益.";
VUHDO_I18N_TT_267 = "用条颜色显示自定义增、减益.";
VUHDO_I18N_TT_268 = "在图标上显示动画效果.";
VUHDO_I18N_TT_269 = "图标显示剩余时间.";
VUHDO_I18N_TT_270 = "移动缩放自定义增、减益图标.";
VUHDO_I18N_TT_271 = "选择同时显示自定义增、减益的最大数量.";
VUHDO_I18N_TT_272 = "选择获得自定义增益时的提示声音.";
VUHDO_I18N_TT_273 = "用图标显示自定义增、减益.";
VUHDO_I18N_TT_274 = "用条颜色显示自定义增、减益.";
VUHDO_I18N_TT_275 = "在图标上显示动画效果.";
VUHDO_I18N_TT_276 = "图标显示剩余时间.";
VUHDO_I18N_TT_277 = "选择血条周边的玩家目标边框颜色.";
VUHDO_I18N_TT_278 = "选择所有血条边框颜色.";
VUHDO_I18N_TT_279 = "选择玩家获得减益提示声音";
VUHDO_I18N_TT_280 = "应用已选定面板设定";
VUHDO_I18N_TT_281 = "开启额外的载具面板. 宠物也将在此面板显示. 所有鼠标点击都只是选定载具/宠物为目标.";
VUHDO_I18N_TT_282 = "开启额外的宠物面板.";
VUHDO_I18N_TT_283 = "开启额外的玩家目标面板. 玩家目标类似主坦克显示，但扔保留辅助坦克.";
VUHDO_I18N_TT_284 = "开启额外的主坦克面板.";
VUHDO_I18N_TT_285 = "无组别显示所有团队单元Select this to show all raid units ungrouped. 这是一种简约而不简单的显示方式.";
VUHDO_I18N_TT_286 = "团队按职责分组：: 近战输出, 近战坦克, 远程输出, 治疗.";
VUHDO_I18N_TT_287 = "团队按职业分组.";
VUHDO_I18N_TT_288 = "团队中所有小队按队号排列 (1-8).";
VUHDO_I18N_TT_289 = "隐藏暴雪标准宠物框体.";
VUHDO_I18N_TT_290 = "隐藏暴雪标准目标框体.";
VUHDO_I18N_TT_291 = "放开鼠标按键而不是按下鼠标按键时开始施法.";
VUHDO_I18N_TT_292 = "开启暴雪标准工具提示并关闭VuhDo工具提示.";
VUHDO_I18N_TT_293 = "在所有玩家条周围显示一个框体.";
VUHDO_I18N_TT_294 = "在当前选定目标周围显示一个框体.";
VUHDO_I18N_TT_295 = "鼠标划过单位高亮显示.";
VUHDO_I18N_TT_296 = "高亮显示鼠标划过组员.";
VUHDO_I18N_TT_297 = "选择鼠标划过紧凑小队时高亮显示的方式";
VUHDO_I18N_TT_298 = "设定当前布局为未组队时自动启用.";
VUHDO_I18N_TT_299 = "设定当前布局为五人队时自动启用.";
VUHDO_I18N_TT_300 = "设定当前布局为十人团队时自动启用.";
VUHDO_I18N_TT_301 = "设定当前布局为二十五人团队时自动启用.";
VUHDO_I18N_TT_302 = "设定当前布局为超过二十五人团队时自动启用.";
VUHDO_I18N_TT_303 = "条颜色根据生命值红绿变化.";
VUHDO_I18N_TT_304 = "固定使用右侧设定颜色显示血条.";
VUHDO_I18N_TT_305 = "血条背景使用职业颜色.";
VUHDO_I18N_TT_306 = "修改你的血条颜色.";
VUHDO_I18N_TT_307 = "放大显示受伤害者血条（不选则收缩）.";
VUHDO_I18N_TT_308 = "血条按竖直（而不是水平）方向变化.";
VUHDO_I18N_TT_309 = "在血条中显示团队图标.";
VUHDO_I18N_TT_310 = "使血条呈水平（而不是竖直）排列";
VUHDO_I18N_TT_311 = "总是在小队顶端（第一位）显示自己.";
VUHDO_I18N_TT_312 = "设定面板锚点为顶端中点.";
VUHDO_I18N_TT_313 = "设定面板锚点为底部中点.";
VUHDO_I18N_TT_314 = "设定面板锚点为左边中点.";
VUHDO_I18N_TT_315 = "设定面板锚点为右边中点.";
VUHDO_I18N_TT_316 = "按最大血量排列组员.";
VUHDO_I18N_TT_317 = "按职业分组";
VUHDO_I18N_TT_318 = "选择HOT条宽度.";
VUHDO_I18N_TT_319 = "开启HOT条";
VUHDO_I18N_TT_320 = "为第三槽位指定HOT.";
VUHDO_I18N_TT_321 = "为第二槽位指定HOT.";
VUHDO_I18N_TT_322 = "为第一槽位指定HOT.";
VUHDO_I18N_TT_323 = "设定条收缩为从左至右.";
VUHDO_I18N_TT_324 = "设定条收缩为竖直方向而非水平方向";
VUHDO_I18N_TT_325 = "在血条左上显示HOT图标";
VUHDO_I18N_TT_326 = "在血条右下显示HOT图标";
VUHDO_I18N_TT_327 = "在血条左下显示HOT图标";
VUHDO_I18N_TT_328 = "在血条右下显示HOT图标";
VUHDO_I18N_TT_329 = "在血条左下显示HOT图标";
VUHDO_I18N_TT_330 = "在可施放 \"迅捷治愈\" (限德鲁伊) 的目标血条上显示一个小红圈.";
VUHDO_I18N_TT_331 = "使HOT方块材质苍白";
VUHDO_I18N_TT_332 = "指定5号槽位HOT. 如选择颜色方块而不是HOT图标，则不能显示";
VUHDO_I18N_TT_333 = "指定4号槽位HOT.";
VUHDO_I18N_TT_334 = "指定3号槽位HOT.";
VUHDO_I18N_TT_335 = "指定2号槽位HOT.";
VUHDO_I18N_TT_336 = "指定号槽位HOT.";
VUHDO_I18N_TT_337 = "配置HOT图标样式.";
VUHDO_I18N_TT_338 = "配置HOT条样式.";
VUHDO_I18N_TT_339 = "面板整体缩放.";
VUHDO_I18N_TT_340 = "不以千为单位显示生命值. 例如 14537 而不是 14.5k";
VUHDO_I18N_TT_341 = "在血条上显示玩家名字.";
VUHDO_I18N_TT_342 = "在血条上显示玩家职业";
VUHDO_I18N_TT_343 = "选择按名字显示的最大玩家数.";
VUHDO_I18N_TT_344 = "选择玩家血条姓名字体.";
VUHDO_I18N_TT_345 = "点击血条和目标单元框时保持姿态不变. 不选择此项可能使你自动切换姿态.";
VUHDO_I18N_TT_346 = "开启法术工具提示信息";
VUHDO_I18N_TT_347 = "使点击 \"穿透\" 面板背景以允许选定目标、移动等. 开启此项将不能通过右键点击显示谁是团长等等...";
VUHDO_I18N_TT_348 = "锁定治疗面板.";
VUHDO_I18N_TT_349 = "针对敌对目标的法术选项目";
VUHDO_I18N_TT_350 = "在自定义减益图标上显示堆叠层数.";
VUHDO_I18N_TT_351 = "设定自定义减益锚点为血条左上.";
VUHDO_I18N_TT_352 = "设定自定义减益锚点为血条右上.";
VUHDO_I18N_TT_353 = "设定自定义减益锚点为血条左下.";
VUHDO_I18N_TT_354 = "设定自定义减益锚点为血条右下.";
VUHDO_I18N_TT_355 = "竖向调节自定义减益图标位置.";
VUHDO_I18N_TT_356 = "横向调节自定义减益图标位置.";
VUHDO_I18N_TT_357 = "用名字文本显示宠物/载具主人";
VUHDO_I18N_TT_358 = "设置非战斗状态下的智能施法功能";
VUHDO_I18N_TT_359 = "为智能施法指定一个组合按键.";
VUHDO_I18N_TT_360 = "战斗中自动触发战复 (限德鲁伊)";
VUHDO_I18N_TT_361 = "在血条左边显示目标条."
VUHDO_I18N_TT_362 = "在血条右边显示目标条."
VUHDO_I18N_TT_363 = "选择伤害闪烁灵敏度. 较大的数值意味着(对更低的伤害)更强的闪烁.";
VUHDO_I18N_TT_364 = "生命值高于警戒线时隐藏生命值文本.";
VUHDO_I18N_TT_365 = "法术布局变动时起用HOT设置(选项=>面板=>HoTs).";
VUHDO_I18N_TT_366 = "自动切换目标至当前治疗目标.";
VUHDO_I18N_TT_367 = "通过这个菜单选择需要侦测的治疗输入类型.";
VUHDO_I18N_TT_368 = "选择上个点显示直接法术的治疗输入.";
VUHDO_I18N_TT_369 = "显示来自直接施放的治疗法术输入.";
VUHDO_I18N_TT_370 = "选择上个点显示来自引导法术的治疗输入.";
VUHDO_I18N_TT_371 = "显示来自引导法术的治疗输入.";
VUHDO_I18N_TT_372 = "选择上个点显示来自HoTs的治疗输入.";
VUHDO_I18N_TT_373 = "显示来自HOT的治疗输入.";
VUHDO_I18N_TT_374 = "选择上个点显示来自爆发性法术的治疗输入 (譬如: 生命绽放爆发).";
VUHDO_I18N_TT_375 = "显示爆发性治疗法术的治疗输入 (譬如: 生命绽放爆发).";
VUHDO_I18N_TT_376 = "将组放置于面板底部 (当选择了右边的\"水平\"时 ).";
VUHDO_I18N_TT_377 = "Select a panel border texture.";
VUHDO_I18N_TT_378 = "Select a size for panel border edges.";
VUHDO_I18N_TT_379 = "Select an inset size for panel borders.";
VUHDO_I18N_TT_380 = "Check this to not show yourself in regular raid/party frames.";
VUHDO_I18N_TT_381 = "Check to apply background bar brightness setting to health bar instead of background bar when debuff color is applied. Useful if your background bar color is brighter than your health bar color.";
VUHDO_I18N_TT_382 = "Check to show an outline around name and life text instead of a shadow.";
VUHDO_I18N_TT_383 = "Ignore Pets in buff tracking.";
VUHDO_I18N_TT_384 = "Sorts raid by the order given in \"Move!\". Selecting this will only work if order is set to \"loose\" above.";

VUHDO_I18N_TT_385 = "Select a health bar color that will be applied if this buff is missing on the player.";
VUHDO_I18N_TT_386 = "Enable to change bar color if this buff is missing.";
VUHDO_I18N_TT_387 = "Increase priority for this buff.";
VUHDO_I18N_TT_388 = "Decrease priority for this buff.";
VUHDO_I18N_TT_389 = "Select a color for HoT Square 6";
VUHDO_I18N_TT_390 = "Check to invert sorting.";
VUHDO_I18N_TT_391 = "Select a size for your raid icons.";
VUHDO_I18N_TT_392 = "Set component anchor to the top-left.";
VUHDO_I18N_TT_393 = "Set component anchor to the top-right.";
VUHDO_I18N_TT_394 = "Set component anchor to the bottom-left.";
VUHDO_I18N_TT_395 = "Set component anchor to the bottom-right.";
VUHDO_I18N_TT_396 = "Set component anchor to the left.";
VUHDO_I18N_TT_397 = "Set component anchor to the top.";
VUHDO_I18N_TT_398 = "Set component anchor to the bottom";
VUHDO_I18N_TT_399 = "Set component anchor to the right.";
VUHDO_I18N_TT_400 = "Adjust component placement in horizontal direction.";
VUHDO_I18N_TT_401 = "Adjust component placement in vertical direction.";
VUHDO_I18N_TT_402 = "Setup raid icons and overheal texts.";
VUHDO_I18N_TT_403 = "Save current spell assignments.";
VUHDO_I18N_TT_404 = "Select a saved spell assignment.";
VUHDO_I18N_TT_405 = "Hide standard Blizzard focus frame.";
VUHDO_I18N_TT_406 = "The remaining stacks a HoT has will not be shown.";
VUHDO_I18N_TT_407 = "The remaining stacks a HoT has will be shown by a text counter.";
VUHDO_I18N_TT_408 = "The remaining stacks a HoT has will be shown by up to four (= four stacks or more) triangles around the HoT icon.";
VUHDO_I18N_TT_409 = "Hides panels when you are solo.";
VUHDO_I18N_TT_410 = "Hides panels when you are in a party of up to five";
VUHDO_I18N_TT_411 = "Setup colors for raid target icons";
VUHDO_I18N_TT_412 = "Click to copy these default settings to all custom debuffs";
VUHDO_I18N_TT_413 = "Select a color for this custom debuff";
VUHDO_I18N_TT_414 = "Select which raid icons to show";
VUHDO_I18N_TT_415 = "Select a text color for overheal text";
VUHDO_I18N_TT_416 = "Check to show raid icons by bar color/text color.";
VUHDO_I18N_TT_417 = "Check to only show raid icons by color that are enabled in Panels=>Misc";
VUHDO_I18N_TT_418 = "Select a color for this raid icon.";
VUHDO_I18N_TT_419 = "Tank mode will only watch the threat situation for aggro detection. Enemies occasionally targeting players will be ignored";
VUHDO_I18N_TT_420 = "Priest only option: Show remaining capacity icon of shields. This is EXPERIMENTAL.";

VUHDO_I18N_TT_421 = "Select color if unit is at full health.";
VUHDO_I18N_TT_422 = "Select color if unit life is medium.";
VUHDO_I18N_TT_423 = "Select color if unit life is low."
VUHDO_I18N_TT_424 = "Enables cluster checking. A cluster is a number of persons within a certain range like needed for Circle of Healing or Chain Heal";
VUHDO_I18N_TT_425 = "Set the rate at which clusters will be refreshed. May have impact on system performance";
VUHDO_I18N_TT_426 = "Select a range in which two units are considered to be a cluster";
VUHDO_I18N_TT_427 = "Select a max. health level above which a unit is considered to be no worthwile target for a cluster healing spell";
VUHDO_I18N_TT_428 = "Select a minimum number of persons clustering up to be a fair target of your cluster heal.";
VUHDO_I18N_TT_429 = "Select a minimum number of persons clustering up to be a good target of your cluster heal."
VUHDO_I18N_TT_430 = "Select this if your cluster healing spell goes off from you (not from the target of the spell itself)";
VUHDO_I18N_TT_431 = "Select this if your cluster healing spell goes off from the target you are casting on (not from you, e.g. Circle of Healing)";
VUHDO_I18N_TT_432 = "Select this if all raid members will be affected by the spell (Chain Heal, Circle of Healing).";
VUHDO_I18N_TT_433 = "Select if only raid members in the spell target's group will benefit from your spell (Prayer of Healing)";
VUHDO_I18N_TT_434 = "Enable to draw a border around raid members which are in cluster with the unit you currently hover your mouse over.";
VUHDO_I18N_TT_435 = "Select to show the number of worthwile units currently clustering up (in cluster hot icon of each unit)";
VUHDO_I18N_TT_436 = "Shows global cooldown as bar.";
VUHDO_I18N_TT_437 = "Detects clusters directly around the target.";
VUHDO_I18N_TT_438 = "Detects clusters jumping from target to to the nearby target with most health deficit."
VUHDO_I18N_TT_439 = "Select the maximum number of times your chained heal will jump to another target.";
VUHDO_I18N_TT_440 = "Select color for number of players in a cluster is rated fair.";
VUHDO_I18N_TT_441 = "Select color for number of players in a cluster is rated good.";
VUHDO_I18N_TT_442 = "Select color for mouse-over cluster border.";
VUHDO_I18N_TT_443 = "Select color for global cooldown bar."
VUHDO_I18N_TT_444 = "If you check this button the currently selected arrangement will automatically enabled if you are in a raid of up to 15 players.";
VUHDO_I18N_TT_445 = "Check to also load HoT setup with arrangements. Don't do this if the arrangement has been saved on another class!";
VUHDO_I18N_TT_446 = "Select debuffs from the ignore list.";
VUHDO_I18N_TT_447 = "Check to rate players assigned as tanks by dungeon finder tool as MTs and show them in MT list.";
VUHDO_I18N_TT_448 = "Setup cluster detection for your mass healing spells";
VUHDO_I18N_TT_449 = "Select a color for threat indicator bar when threat is high.";
VUHDO_I18N_TT_450 = "Select a color for threat indicator bar when threat is low.";
VUHDO_I18N_TT_451 = "Enable to auto-rebuff all missing buffs using the mouse-wheel on a buff swatch.";
VUHDO_I18N_TT_452 = "Select a saved bouquet or type in a new name.";
VUHDO_I18N_TT_453 = "Select a special trigger or enter the name of a buff or debuff.";
VUHDO_I18N_TT_454 = "Select a color for this event/trigger.";
VUHDO_I18N_TT_455 = "Select a default icon for this event. If this is needed or not depends on the type of bouquet indicator.";
VUHDO_I18N_TT_456 = "Setup the bars indicators like icons and status bars.";
VUHDO_I18N_TT_457 = "Setup Bouquets. Bouquets are groups of Buffs, Debuffs and other occasions in a priorization order. You can setup a bouquet e.g. as a HoT icon";
VUHDO_I18N_TT_458 = "Will display buffs in a more screen estate saving way.";
VUHDO_I18N_TT_459 = "Enter a new boquet name to create or copy current bouquet to.";
VUHDO_I18N_TT_460 = "Enter a debuff, buff or hot name.";
VUHDO_I18N_TT_461 = "Select a color to show if statusbar value is low";
VUHDO_I18N_TT_462 = "Select a color to show if statusbar value is medium";
VUHDO_I18N_TT_463 = "Select a color to show if statusbar value is high.";
VUHDO_I18N_TT_464 = "Select a bouquet to show via this indicator";
VUHDO_I18N_TT_465 = "Enables Clique compatibility mode. Requires to reload UI after changing.";
VUHDO_I18N_TT_466 = "Scans all units no matter how far away";
VUHDO_I18N_TT_467 = "Only scans units which are in the same map with you.";
VUHDO_I18N_TT_468 = "Only scans units in a range of max. 100 yards.";
VUHDO_I18N_TT_469 = "Only scans units in a range of max. 40 yards.";
VUHDO_I18N_TT_470 = "Scans talent trees for raid role estimation. May conflict with other addons.";
VUHDO_I18N_TT_471 = "Makes bars grow from right to left.";
VUHDO_I18N_TT_472 = "Indicates units taking severe damage by flashing the health bars.";
VUHDO_I18N_TT_473 = "Enable this to show HoT squares using the original icon.";
VUHDO_I18N_TT_474 = "Enable this to show HoT squares using a glossy texture.";
VUHDO_I18N_TT_475 = "Auto-Enable profile whenever switching to primary specc";
VUHDO_I18N_TT_476 = "Auto-Enable profile whenever switching to secondaray specc";
VUHDO_I18N_TT_477 = "In this Menu you can reset several aspects of your configuration to factory defaults";
VUHDO_I18N_TT_478 = "Click to return to where you came from.";
VUHDO_I18N_TT_479 = "Only if the spell in this edit box has no cooldown clusters will be shown. Leave empty to always show clusters.";
VUHDO_I18N_TT_480 = "Move to change options screen scale";
VUHDO_I18N_TT_481 = "Setup HoT counter / timer font";
VUHDO_I18N_TT_482 = "Adjust HoT text size";
VUHDO_I18N_TT_483 = "Select a bouquet for the selected panel to override general health bar bouquet.";
VUHDO_I18N_TT_484 = "Enables PallyPower compatible remote blessing and aura setup communications";
VUHDO_I18N_TT_485 = "Check this to not show your target in \"Private Tanks\" panel.";
-- 2.17
VUHDO_I18N_TT_486 = "Enable to lock a profile so it can't be overwritten accidentally.";
VUHDO_I18N_TT_487 = "Enable to auto-overwrite existing profile instead of showing overwrite / copy / abort confirmation dialog.";
VUHDO_I18N_TT_488 = "Enable to only show direction if player is dead.";
VUHDO_I18N_TT_489 = "Enable to show distance to oor raid members.";
VUHDO_I18N_TT_490 = "Enable to show direction of out of range players by an arrow.";
VUHDO_I18N_TT_491 = "Check to display custom debuff name for about 2 secs after applied.";
-- 2.18
VUHDO_I18N_TT_492 = "Uncheck to enable creation of macros for emergency raid roster restoration after logging back in mid fight after a d/c. 2 free toon individual macro slots needed."
VUHDO_I18N_TT_493 = "Select direction arrow size."
VUHDO_I18N_TT_494 = "Select destination profile";
VUHDO_I18N_TT_495 = "Exports all custom debuffs of current profile to all profiles of this toon.";
VUHDO_I18N_TT_496 = "Exports all custom debuffs of current profile to selected profile.";
VUHDO_I18N_TT_497 = "Exports all custom debuffs of current profile to ALL other profiles.";

VUHDO_I18N_APPLY_TO_ALL = "全部应用";
VUHDO_I18N_TEST = "测试";
VUHDO_I18N_ADD = "添加";
VUHDO_I18N_SELECT = "选择";
VUHDO_I18N_NEW_COLOR = "新颜色";
VUHDO_I18N_OLD_COLOR = "旧颜色";
VUHDO_I18N_HIDE_CHARGES = "隐藏消耗";
VUHDO_I18N_POWERS = "能量";
VUHDO_I18N_HOTS = "HoT";
VUHDO_I18N_HOT_COLORS = "HoT 颜色";
VUHDO_I18N_ICONS = "图标";
VUHDO_I18N_COUNTDOWN = "倒计时";
VUHDO_I18N_APPLIANCES = "装置";
VUHDO_I18N_FADE_OUT = "淡出";
VUHDO_I18N_POWER_TYPES = "能量类型";
VUHDO_I18N_THREAT = "仇恨";
VUHDO_I18N_MISC = "杂项";
VUHDO_I18N_SKINS = "皮肤";
VUHDO_I18N_PANEL_WIZARD = "设置向导";
VUHDO_I18N_PRIV_TANKS = "辅助坦克";
VUHDO_I18N_CUSTOM_DE_BUFFS = "自定义增/减益";
VUHDO_I18N_CHANGE_COLOR = "变色";
VUHDO_I18N_ICON = "图标";
VUHDO_I18N_ANIMATION = "动画";
VUHDO_I18N_STORE = "储存";
VUHDO_I18N_SAVE = "保存";
VUHDO_I18N_DELETE = "删除";
VUHDO_I18N_APPLY = "应用";
VUHDO_I18N_ADDITIONAL_PANELS = "附加面板";
VUHDO_I18N_UNSORT = "不排序";
VUHDO_I18N_ROLES = "职责";
VUHDO_I18N_CLASSES = "职业";
VUHDO_I18N_GROUPS = "队伍";
VUHDO_I18N_MAIN_PANEL = "主面板";
VUHDO_I18N_PARTY = "队伍";
VUHDO_I18N_PET = "宠物";
VUHDO_I18N_TARGET = "目标";
VUHDO_I18N_HIDE_STANDARD = "界面隐藏";
VUHDO_I18N_PLAYER_TARGET = "玩家目标";
VUHDO_I18N_SINGLE = "单一";
VUHDO_I18N_MULTI = "多个";
VUHDO_I18N_HOT_TARGETING = "HoT 监视";
VUHDO_I18N_COLORS_FONTS = "(颜色/字体)";
VUHDO_I18N_ARRANGEMENT = "布局";
VUHDO_I18N_SELECT_AN_ARRANGEMENT = "选择布局";
VUHDO_I18N_OR_ENTER_PROFILE_NAME = "... 或输入布局名称";
VUHDO_I18N_GROUPS_SIZES = "(组/大小)";
VUHDO_I18N_SYMBOL = "标记";
VUHDO_I18N_TOP_BAR = "仇恨条";
VUHDO_I18N_MONITOR_THREAT = "仇恨监视";
VUHDO_I18N_USE_ADD_BAR = "使用附加仇恨条";
VUHDO_I18N_LINE = "划线";
VUHDO_I18N_LEFT = "左";
VUHDO_I18N_RIGHT = "右";
VUHDO_I18N_CHECK_FOR_AGGRO = "获得仇恨监视";
VUHDO_I18N_CURR = "当前.";
VUHDO_I18N_BAR_COLOR = "条颜色";
VUHDO_I18N_PLUS_BG = "+背景";
VUHDO_I18N_INV_GROWTH = "Invert";
VUHDO_I18N_VERTICAL = "竖";
VUHDO_I18N_RAID_ICON = "团队图标";
VUHDO_I18N_YOU_FIRST = "第一个显示你";
VUHDO_I18N_IICONSI = "[图标]";
VUHDO_I18N_ISQUARESI = "[方形]";
VUHDO_I18N_HOT_ORDER = "HoT 排序";
VUHDO_I18N_SLOT_5 = "位置 5 (多数不显示)";
VUHDO_I18N_SLOT_4 = "位置 4";
VUHDO_I18N_SLOT_3 = "位置 3";
VUHDO_I18N_SLOT_2 = "位置 2";
VUHDO_I18N_SLOT_1 = "位置 1 (基本都显示)";
VUHDO_I18N_TEXT_POSITION = "文本位置";
VUHDO_I18N_FLAGS = "标记";
VUHDO_I18N_SHOW_TEXT = "显示文本";
VUHDO_I18N_KEYS = "按键设置";
VUHDO_I18N_SPEC_2 = "配置 2";
VUHDO_I18N_SPEC_1 = "配置 1";
VUHDO_I18N_MANAGE_KEYS = "管理按键配置";
VUHDO_I18N_INSTANT_2 = "替换 2";
VUHDO_I18N_INSTANT_1 = "替换 1";
VUHDO_I18N_TRINKET_2 = "饰品 2";
VUHDO_I18N_TRINKET_1 = "饰品 1";
VUHDO_I18N_TRIGGER_WHAT = "触发...";
VUHDO_I18N_ALSO_OUT_FIGHT = "非战斗状态";
VUHDO_I18N_ALSO_HOTS = "HoTs类技能";
VUHDO_I18N_KEEP_STANCE = "保持姿态";
VUHDO_I18N_AUTO_TRIGGER = "自动触发";
VUHDO_I18N_SPELL_ADVICE = "使用WOW标准按键绑定设置为以下法术分配按键. (滚动至'VuhDo'下.)";
VUHDO_I18N_SAVE_AS = "另存为...";
VUHDO_I18N_MOVE = "移动！";
VUHDO_I18N_SPELLS = "法术";
VUHDO_I18N_PANELS = "面板";
VUHDO_I18N_BUFFS = "增益";
VUHDO_I18N_ICON_SCALE = "图标缩放";
VUHDO_I18N_THICKNESS = "边框粗细";
VUHDO_I18N_WARNING_COLOR_AT = "警戒线";
VUHDO_I18N_THREAT_BAR_HEIGHT = "仇恨条高度";
VUHDO_I18N_REFRESH_AGGRO = "获得仇恨监视器刷新率";
VUHDO_I18N_PANEL_SCALE = "面板缩放";
VUHDO_I18N_MAX_CHARS = "最大人物数 (0=全部)";

-- #+v1.178
VUHDO_I18N_HOSTILE = "敌对";
VUHDO_I18N_HOSTILE_TITLE = "[敌对]";
VUHDO_I18N_HOSTILE_ADVICE_1 = "输入法术名称或目标/焦点/协助"
VUHDO_I18N_HOSTILE_ADVICE_2 = "不要输入宏名称或者其他东西！！！"
VUHDO_I18N_HOSTILE_ADVICE_3 = "饰品/瞬发技能不会自动触发/施放！！！"


-- Slider
VUHDO_I18N_BACKG_BRIGHTNESS = "背景亮度";
VUHDO_I18N_WARN_PREC_AT = "警告 / 侦测 ……";
VUHDO_I18N_MAX_NO_DE_BUFFS = "最大增、减益数量";
VUHDO_I18N_DEBUFF_SOUND = "减益声音";
VUHDO_I18N_BRIGHTNESS = "亮度";
VUHDO_I18N_RAID_ICON_SCALE = "团队图标缩放";
VUHDO_I18N_NAME_TEXT_SIZE = "名字文本缩放";
VUHDO_I18N_LIFE_TEXT_SIZE = "生命值文本缩放";
-- Color swatches
VUHDO_I18N_BUFF_OKAY = "Buff 良好";
VUHDO_I18N_BUFF_LOW = "Buff 持续时间低";
VUHDO_I18N_BUFF_MISSING = "Buff 正在消失";
VUHDO_I18N_OUT_OF_RANGE = "超出距离";
VUHDO_I18N_COOLDOWN = "冷却";
VUHDO_I18N_EMPTY_GROUP = "空小队";
VUHDO_I18N_PANEL_BACKGROUND = "面板背景";
VUHDO_I18N_SWATCH_BORDER = "Swatch Border";
VUHDO_I18N_PANEL_BORDER = "面板边界";
VUHDO_I18N_2ND_CHARGE = "第二跳";
VUHDO_I18N_3RD_CHARGE = "第三跳";
VUHDO_I18N_4TH_CHARGE = "第四跳";
VUHDO_I18N_BAR_1 = "条 1";
VUHDO_I18N_BAR_2 = "条 2";
VUHDO_I18N_BAR_3 = "条 3";
VUHDO_I18N_SQUARE_1 = "方块 1";
VUHDO_I18N_SQUARE_2 = "方块 2";
VUHDO_I18N_SQUARE_3 = "方块 3";
VUHDO_I18N_SQUARE_4 = "方块 4";
VUHDO_I18N_SQUARE_5 = "方块 5";
VUHDO_I18N_EMERGENCY = "紧急";
VUHDO_I18N_NO_EMEGENCY = "不紧急";
VUHDO_I18N_IRRELEVANT = "无关";
VUHDO_I18N_INCOMING = "输入";
VUHDO_I18N_MANA = "法力";
VUHDO_I18N_RAGE = "怒气";
VUHDO_I18N_ENERGY = "能量";
VUHDO_I18N_RUNES = "符文";
VUHDO_I18N_DEAD = "死亡";
VUHDO_I18N_OFFLINE = "离线";
VUHDO_I18N_CHARMED = "被控制";
VUHDO_I18N_AGGRO_BAR = "仇恨目标条";
VUHDO_I18N_BAR_FRAME = "条框体";
VUHDO_I18N_POISON = "毒";
VUHDO_I18N_DISEASE = "疾病";
VUHDO_I18N_CURSE = "诅咒";
VUHDO_I18N_MAGIC = "魔法";
VUHDO_I18N_HEADER = "标题";
VUHDO_I18N_TARGET_NAME = "目标名字";
VUHDO_I18N_BORDER = "边界";

VUHDO_I18N_AUTO_ENABLE = "超过X名玩家时自动开启:";

VUHDO_I18N_ANOUNCE_RESURRECTION = "复活通知";
VUHDO_I18N_FILTER = "过滤";
VUHDO_I18N_FOCUS = "焦点";
VUHDO_I18N_BUFF = "增益";
VUHDO_I18N_OTHERS = "其他";
VUHDO_I18N_LIFE_TEXT = "生命值文本";
VUHDO_I18N_EXTRA_TEXT = "Extra Text";
VUHDO_I18N_FRAME = "框体";
VUHDO_I18N_1 = " 1";
VUHDO_I18N_2 = " 2";
VUHDO_I18N_3 = " 3";
VUHDO_I18N_4 = " 4";
VUHDO_I18N_5 = " 5";
VUHDO_I18N_6 = " 6";
VUHDO_I18N_7 = " 7";
VUHDO_I18N_8 = " 8";
VUHDO_I18N_10 = " 10";
VUHDO_I18N_25 = " 25";
VUHDO_I18N_40 = " 40";
VUHDO_I18N_NUM_TRIANGLES = "# / 三角形";
VUHDO_I18N_DEBUFF_DEFAULTS = "增、减益默认";
VUHDO_I18N_ITEXTUREI = "[材质]";
VUHDO_I18N_BAR = "条";
VUHDO_I18N_HOTS_2 = "HoTs #2";
VUHDO_I18N_PET_CLASS = "宠物颜色";
VUHDO_I18N_CLASS_COLORS = "职业颜色";
VUHDO_I18N_HOT_CHARGES = "HoT 次数";
VUHDO_I18N_TEXT_COLOR = "文本颜色";
VUHDO_I18N_BACK_COLOR = "背景颜色";
VUHDO_I18N_HOT_BARS = "HoT 条";
VUHDO_I18N_OUTLINE = "轮廓";
VUHDO_I18N_SHADOW = "阴影";
VUHDO_I18N_WARNING = "警告";
VUHDO_I18N_MISC_TEXT = "杂项. 文本";
VUHDO_I18N_EXPIRY_WARNING = "期满警告";
VUHDO_I18N_COUNTDOWN_OFF = "Countdown: Off";
VUHDO_I18N_SECS = "秒";
VUHDO_I18N_SECS_10 = "0.1秒";
VUHDO_I18N_FULL_DURATION = "满持续时间";
VUHDO_I18N_TOOLS = "工具";
VUHDO_I18N_TIMER = "计时器";
VUHDO_I18N_DEBUFF_OPTIONS = "增、减益选项";
VUHDO_I18N_SOUND = "声音";
VUHDO_I18N_STORE_DELETE = "保存 / 删除";
VUHDO_I18N_DEBUFF_SOUND = "减益声音";
VUHDO_I18N_MOUSE_UP = "Mouse Up";
VUHDO_I18N_REACTION_ON = "Reaction on...";
VUHDO_I18N_TOOLTIP_TYPE = "工具提示类型";
VUHDO_I18N_BAR_BORDER = "条边框";
VUHDO_I18N_UNIT = "单元";
VUHDO_I18N_MOUSE_OVER_HIGH = "鼠标滑过高亮";
VUHDO_I18N_FLOAT = "浮动";
VUHDO_I18N_SOLIDD = "固定:";
VUHDO_I18N_HORIZONTAL = "水平";
VUHDO_I18N_SLOT_1_2 = "Slot 1";
VUHDO_I18N_INVERT_X = "Invert X";
VUHDO_I18N_INVERT_Y = "Invert Y";
VUHDO_I18N_FLAT_TEXTURE = "平滑材质";
VUHDO_I18N_HOT_ICONS = "HoT 图标";
VUHDO_I18N_TARGET_OF_TARGET = "目标的目标";
VUHDO_I18N_VERBOSE = "Verbose";
VUHDO_I18N_1_DOT = "1.";
VUHDO_I18N_2_DOT = "2.";
VUHDO_I18N_3_DOT = "3.";
VUHDO_I18N_4_DOT = "4.";
VUHDO_I18N_5_DOT = "5.";
VUHDO_I18N_6_DOT = "6.";
VUHDO_I18N_7_DOT = "7.";
VUHDO_I18N_8_DOT = "8.";
VUHDO_I18N_9_DOT = "9.";
VUHDO_I18N_10_DOT = "10.";
VUHDO_I18N_11_DOT = "11.";
VUHDO_I18N_12_DOT = "12.";
VUHDO_I18N_13_DOT = "13.";
VUHDO_I18N_14_DOT = "14.";
VUHDO_I18N_15_DOT = "15.";
VUHDO_I18N_16_DOT = "16.";
VUHDO_I18N_KEY_BINDINGS = "按键绑定";
VUHDO_I18N_MOUSE_WHEEL = "鼠标滑轮";
VUHDO_I18N_TOOLTIP_INFO = "提示工具信息";

-- #+1.197
VUHDO_I18N_EDGE_SIZE = "Edge Size";
VUHDO_I18N_EDGE_INSETS = "Edge Insets";

-- #+1.203
VUHDO_I18N_SWAP_WHEN_DEBUFFED = "Swap Debuff";

-- #+1.204
VUHDO_I18N_IGNORE_PETS = "Ignore Pets";
VUHDO_I18N_PANEL_MODEL = "Panel Model";

-- #+1.207
VUHDO_I18N_OVERHEAL_TEXT = "Overheal Text";

-- #+1.210
VUHDO_I18N_NO_STACKS = "Stacks: Off";
VUHDO_I18N_NUMBER_STACKS = "Text";
VUHDO_I18N_TRIANGLE_STACKS = "Triangles";
VUHDO_I18N_HIDE_PANELS = "Hide Panels";
VUHDO_I18N_SOLO = "Solo";

VUHDO_I18N_CLICK_THROUGH = "+ 不点击";
VUHDO_I18N_IHEALTH_BARI = "[血条]";
VUHDO_I18N_SLOT_6 = "位置 6";
VUHDO_I18N_SQUARE_6 = "方块 6";
VUHDO_I18N_GLOSSY = "光泽";
VUHDO_I18N_DAMAGE_FLASH = "伤害闪烁";
VUHDO_I18N_SENSIVITY = "灵敏度";
VUHDO_I18N_HIDE_IRRELEVANT = "Hide irrel.";
VUHDO_I18N_LOAD_HOTS = "读取HoTs";
VUHDO_I18N_CASTED = "直接";
VUHDO_I18N_CHANNELLED = "引导";
VUHDO_I18N_BOMBED = "爆发";
VUHDO_I18N_EVENT_HORIZON = "事件视界";
VUHDO_I18N_ALGINMENT = "对齐";
VUHDO_I18N_BOTTOM = "底部";
VUHDO_I18N_PET_OWNERS = "宠物主人";
VUHDO_I18N_BATTLE_REZ = "战复";


-- #+1.232
VUHDO_I18N_DEBUFF_LIST = "(De)Buff List";
VUHDO_I18N_DEBUFF_EDIT_BOX = "Enter new Buff or Debuff Name";

-- #+1.233
VUHDO_I18N_BUTTON_6 = "Button 6";
VUHDO_I18N_BUTTON_7 = "Button 7";
VUHDO_I18N_BUTTON_8 = "Button 8";
VUHDO_I18N_BUTTON_9 = "Button 9";
VUHDO_I18N_BUTTON_10 = "Button 10";
VUHDO_I18N_BUTTON_11 = "Button 11";
VUHDO_I18N_BUTTON_12 = "Button 12";
VUHDO_I18N_BUTTON_13 = "Button 13";
VUHDO_I18N_BUTTON_14 = "Button 14";
VUHDO_I18N_BUTTON_15 = "Button 15";
VUHDO_I18N_BUTTON_16 = "Button 16";
VUHDO_I18N_TANK_MODE = "Tank Mode";


-- #+1.237
VUHDO_I18N_CLUSTER_SCANNER = "Cluster scanner";
VUHDO_I18N_CLUSTER_PARAMS = "Cluster parameters";
VUHDO_I18N_FAIR_THRESHOLD = "Fair threshold";
VUHDO_I18N_GOOD_THRESHOLD = "Good threshold";
VUHDO_I18N_SOURCE_SPELL = "Spell Source";
VUHDO_I18N_SOURCE_MINE = "Player";
VUHDO_I18N_SOURCE_ALL = "Target";
VUHDO_I18N_DEST_SPELL = "Spell Destination";
VUHDO_I18N_DEST_RAID = "Raid";
VUHDO_I18N_DEST_PARTY = "Party";
VUHDO_I18N_CLUSTERS = "Clusters";
VUHDO_I18N_LOW = "Low";
VUHDO_I18N_FAIR = "Fair";
VUHDO_I18N_GOOD = "Good";
VUHDO_I18N_HEALTH_LEVEL = "Health Level <";
VUHDO_I18N_CLUSTER_FINDER = "Cluster Finder";
VUHDO_I18N_OTHER_HOTS = "Other player's HoTs";
VUHDO_I18N_EMPTY_HOTS = "empty";
VUHDO_I18N_MOUSE_HOVER = "Mouse Hover";
VUHDO_I18N_COUNTER = "Counter";
VUHDO_I18N_GLOBAL_COOLDOWN = "Global Cooldown";
VUHDO_I18N_GCD = "GCD";

-- #+1.238
VUHDO_I18N_DISPLAY_OPTIONS = "Display options";
VUHDO_I18N_RADIAL = "Radial";
VUHDO_I18N_CHAINED = "Chained";
VUHDO_I18N_CHAINED_MAX_JUMP = "Chained max jumps";
VUHDO_I18N_TIMES = " times";
VUHDO_I18N_SOURCE_DESTINATION = "Source/Destination";

VUHDO_I18N_HIGH = "High";


-- #+1.251
VUHDO_I18N_15 = " 15";
VUHDO_I18N_LOAD_HOTS = "Load HoTs";
VUHDO_I18N_IGNORE_LIST = "Ignore List";
VUHDO_I18N_FIVE_MAN_MTS = "5 man MTs";
VUHDO_I18N_FILTER_ONLY = "Filter only";
VUHDO_I18N_LIFE_COLORS = "Life colors";
VUHDO_I18N_SMART_WHEEL = "Smart Wheel";
VUHDO_I18N_PASTE = "Paste";
VUHDO_I18N_COPY = "Copy";

-- #+1.252
VUHDO_I18N_BOUQUETS = "Bouquets";
VUHDO_I18N_SELECT_OR_ENTER_BOUQUET = "Select a Bouquet ...";
VUHDO_I18N_NEW = "New";
VUHDO_I18N_BOUQUET_DETAILS = "Bouquet Details";
VUHDO_I18N_HIGHEST_PRIO = "Highest Priority";
VUHDO_I18N_LOWEST_PRIO = "Lowest Priority";
VUHDO_I18N_ITEM_DETAILS = "Item Details";
VUHDO_I18N_ENTER_DE_BUFF_OR_SPECIAL = "Select special event ...";
VUHDO_I18N_ITEM = "Item";
VUHDO_I18N_SELECT_DEFAULT_ICON = "Select default icon";
VUHDO_I18N_MINE = "Mine";
VUHDO_I18N_GRADIENT = "Gradient";
VUHDO_I18N_INDICATORS = "Indicators";

VUHDO_I18N_COPIED_BOUQUET = "Copied bouquet ";
VUHDO_I18N_BOUQUET_ALREADY_EXISTS = ": Bouquet already exists. Type new name first.";
VUHDO_I18N_CREATED_NEW_BOUQUET = "Created new Bouquet: ";
VUHDO_I18N_DELETED_BOUQUET = "Deleted bouquet: ";
VUHDO_I18N_BOUQUET_NOT_FOUND = ": No such bouquet found.";
VUHDO_I18N_SELECT_STORE_BOUQUET_FIRST = "Select bouquet first";
VUHDO_I18N_SELECT_ITEM_FIRST = "Select an item to remove first.";
VUHDO_I18N_SELECT_A_PROFILE = "Select a profile";
VUHDO_I18N_PROFILES = "Profiles";
VUHDO_I18N_EDIT_BUTTON = "Edit...";
VUHDO_I18N_MORE_BUTTON = "More...";
VUHDO_I18N_DONE_BUTTON = "Done";
VUHDO_I18N_BASIC = "Basic";
VUHDO_I18N_ADVANCED = "Advanced";
VUHDO_I18N_EXPERT = "Expert";
VUHDO_I18N_COMPACT = "Compact";

VUHDO_I18N_REALLY_DELETE_PROFILE = "Really delete profile";
VUHDO_I18N_MUST_ENTER_SELECT_PROFILE = "You must enter/select a name first.";
VUHDO_I18N_DELETED_PROFILE = "Successfully deleted profile";

VUHDO_I18N_TURN_AXIS = "Turn Axis";

VUHDO_I18N_OR_NEW_BOUQUET_NAME = "... or new Bouquet name";
VUHDO_I18N_OR_ENTER_DEBUFF_HOT = "... or enter Buff / Debuff / HoT name";
VUHDO_I18N_TALENT_TREES = "Talent trees";
VUHDO_I18N_SCAN = "Scan";
VUHDO_I18N_INFINITE = "Infinite";
VUHDO_I18N_SAME_ZONE = "Same Zone";
VUHDO_I18N_100_YARDS = "100 yards";
VUHDO_I18N_40_YARDS = "40 yards";
VUHDO_I18N_LIFE_TEXT = "Life Text";
VUHDO_I18N_BACK = "Back";

VUHDO_I18N_OR_NEW_BOUQUET_NAME = "... or new Bouquet name";
VUHDO_I18N_OR_ENTER_DEBUFF_HOT = "... or enter Buff / Debuff / HoT name";
VUHDO_I18N_TALENT_TREES = "Talent trees";
VUHDO_I18N_SCAN = "Scan";
VUHDO_I18N_INFINITE = "Infinite";
VUHDO_I18N_SAME_ZONE = "Same Zone";
VUHDO_I18N_100_YARDS = "100 yards";
VUHDO_I18N_40_YARDS = "40 yards";
VUHDO_I18N_LIFE_TEXT = "Life Text";
VUHDO_I18N_BACK = "Back";

VUHDO_I18N_CLIQUE_COMPAT_MODE = "Clique support";
VUHDO_I18N_RESET = "Reset";
VUHDO_I18N_DEBUFF_COLORS = "Debuff Colors";
VUHDO_I18N_BUFFS_HOTS = "Buffs/HoTs";
VUHDO_I18N_BUFF_WATCH = "Buff Watch";
VUHDO_I18N_CUSTOM_DEBUFFS = "Custom Debuffs";
VUHDO_I18N_DEFAULT_BOUQUETS = "Default Bouquets";
VUHDO_I18N_EVERYTHING = "Everything";
VUHDO_I18N_LANGUAGE = "Language";
VUHDO_I18N_PANEL_POSITIONS = "Panel Positions";
VUHDO_I18N_PER_PANEL_SETTINGS = "per Panel Settings";
VUHDO_I18N_MINUTE = "min.";
VUHDO_I18N_MSEC = "msec";
VUHDO_I18N_PEOPLE = " people";
VUHDO_I18N_RESET_CLASS_COLORS = "This will reset your custom\nCLASS COLOR settings. Proceed?" ;
VUHDO_I18N_RESET_DEBUFF_COLORS = "This will reset your custom\nDEBUFF COLOR settings. Proceed?";
VUHDO_I18N_RESET_RAID_ICON_COLORS = "This will reset your custom\nRAID TARGET COLOR settings. Proceed?";
VUHDO_I18N_RESET_BUFF_WATCH = "This will reset all your\nBUFF WATCH settings. Proceed?";
VUHDO_I18N_RESET_CUSTOM_DEBUFFS = "This will reset all your\nCUSTOM DEBUFFs + settings. Proceed?";
VUHDO_I18N_RESET_DEFAULT_BOUQUETS = "This will reset all \nDEFAULT (not: custom) BOUQUETS. Proceed?";
VUHDO_I18N_RESET_INDICATORS = "This will reset your custom\nINDICATOR CONFIG. Proceed?";
VUHDO_I18N_RESET_ALL = "!!!WARNING: This will RESET THE WHOLE\nADDON to factory defaults!!! Proceed?" ;
VUHDO_I18N_RESET_LANGUAGE = "This will reset all settings after client\nlanguage change (Heavy STUFF!!!). Proceed?";
VUHDO_I18N_RESET_PANEL_POSITIONS = "This will reset your\npanel positions. Proceed?";
VUHDO_I18N_RESET_PER_PANEL_SETTINGS = "This will reset your\nper-panel setup. Proceed?";

-- 2.17
VUHDO_I18N_LOCK = "Lock";
VUHDO_I18N_QUIET_MODE = "Quiet Mode";
VUHDO_I18N_SETTINGS = "Settings";
VUHDO_I18N_ACTIVATE_DUE_GRP_SIZE = "Activate due to group size";
VUHDO_I18N_CUSTOM_HEALTH_BAR_BOUQUET = "Custom Health Bar Bouquet";
VUHDO_I18N_CUSTOM_SETTINGS = "Custom settings";
VUHDO_I18N_DISTANCE = "Distance";
VUHDO_I18N_DEAD_ONLY = "dead only";
VUHDO_I18N_DIRECTION = "Direction";
VUHDO_I18N_IF_OOR_SHOW = "If unit is out of range show...";
VUHDO_I18N_DEBUFF_NAME = "Debuff Name";
-- 2.18
VUHDO_I18N_DISABLE = "Disable";
VUHDO_I18N_DC_RESTORE = "D/C Restore";
VUHDO_I18N_EXPORT_CUSTOM_DEBUFFS = "Export Custom Debuffs";
VUHDO_I18N_EXPORT_TO_PROFILE = "Export to profile:";
VUHDO_I18N_THIS_TOONS = "This Toon's";
VUHDO_I18N_SELECTED = "Selected";
VUHDO_I18N_ALL = "All";
VUHDO_I18N_REPLACE = "Replace";
