if (GetLocale() ~= "frFR") then
	return;
end


-- New Options
-- @EXACT = false
VUHDO_I18N_SCANNERS = "Scanners";
VUHDO_I18N_RESURRECT_SHORT = "Ressusciter";
VUHDO_I18N_GENERAL = "G\195\169n\195\169ral";
VUHDO_I18N_CONFIG = "Configuration";
VUHDO_I18N_REBUFF = "Rebuff";
VUHDO_I18N_FORMAT = "Format";
VUHDO_I18N_BUFF_NAMES = "Noms des buffs";
VUHDO_I18N_EMPTY_GROUPS = "Groupes vides";
VUHDO_I18N_STATES = "States";
VUHDO_I18N_CD_FLASHING = "CD-Flashing";
VUHDO_I18N_TIMERS = "Timers";
VUHDO_I18N_WHATEVER_FIRST = "... OU... (quelque soit le premier)";
VUHDO_I18N_SMART_DOTS = "Smart...";
VUHDO_I18N_GROUP_BUFFS = "Buffs de groupe";
VUHDO_I18N_MODES = "Modes";
VUHDO_I18N_EMERGENCY_MODE = "Mode Urgence";
VUHDO_I18N_NORMAL_MODE = "Mode normal";
VUHDO_I18N_DETECT = "D\195\169tection";
VUHDO_I18N_RANGE = "Distance";
VUHDO_I18N_ADD_NEW_PANEL = "Ajouter un nouveau panneau";
VUHDO_I18N_HOLD_TO_TEST = "Maintenir pour tester";
VUHDO_I18N_OWN_HOTS = "HoTs personnel";
VUHDO_I18N_BAR_TEXTURE = "Texture des barres";
VUHDO_I18N_OTHER_POWERS = "Autre";
VUHDO_I18N_MANA_BARS = "Barres de Mana";
VUHDO_I18N_LOSE = "Perte";
VUHDO_I18N_ORDERING = "Ordonner";
VUHDO_I18N_HIDE_EMPTY = "Masque les \nemplacements vides";
VUHDO_I18N_ANCHOR = "Ancre";
VUHDO_I18N_UNIT_ID = "Unit ID";
VUHDO_I18N_HEADER_TEXT = "Texte de l'ent\195\170te";
VUHDO_I18N_TOOLTIPS = "Aide contextuelle";
VUHDO_I18N_SIZING = "Dimensions";
VUHDO_I18N_BUTTON_SIZE = "Taille des barres";
VUHDO_I18N_TARGET_NAME = "Nom de la cible";
VUHDO_I18N_PERCENT = "Pourcentage";
VUHDO_I18N_MISSING = "Manquant";
VUHDO_I18N_REMAINING = "Restant";
VUHDO_I18N_HITPOINTS = "Hitpoints";
VUHDO_I18N_BAR_TEXT = "Texte des barres";
VUHDO_I18N_MAX_SWATCHES_PER_LINE = "Max.Indicateurs par Ligne";
VUHDO_I18N_MAX_BUFFS_PER_ROW = "Max.Buffs par Ligne";
VUHDO_I18N_REFRESH_RATE = "Taux de \nrafraichissement";
VUHDO_I18N_INDICATE_REBUFF_BELOW = "Indique de rebuffer en dessous de";
VUHDO_I18N_IF_AT_LEAST = "... si au moins";
VUHDO_I18N_PLAYERS_LOW = " joueurs bas.";
VUHDO_I18N_SIZE = "Taille";
VUHDO_I18N_TEXTURE_NUM = "Texture #";
VUHDO_I18N_TEXT_SIZE = "Taille du texte";
VUHDO_I18N_X_SPACING = "X-Espacement";
VUHDO_I18N_Y_SPACING = "Y-Espacement";
VUHDO_I18N_X_GAP = "X-Ecart";
VUHDO_I18N_Y_GAP = "Y-Ecart";

-- General Labels
-- @EXACT = false
VUHDO_I18N_CANCEL = "Annuler";
VUHDO_I18N_SHOW = "Afficher";
VUHDO_I18N_BARS = "Barres"
VUHDO_I18N_COLOR = "Couleur";
VUHDO_I18N_COLORS = "Couleurs";
VUHDO_I18N_GENERAL_SHORT = "G\195\169n\195\169ral";
VUHDO_I18N_CUSTOM = "Personalisation";
VUHDO_I18N_MOUSE = "Souris";
VUHDO_I18N_STANDARD = "Standard";
VUHDO_I18N_POSITION = "Position";
VUHDO_I18N_SCALE = "�chelle";
VUHDO_I18N_ENABLE = "Actif";
VUHDO_I18N_BACKGROUND = "Arri\195\168re plan";
VUHDO_I18N_GROUPED = "Group\195\169";
VUHDO_I18N_SORT_BY = "Trier par...";
VUHDO_I18N_NAME = "Nom";
VUHDO_I18N_MAX_HP = "Max. PV";
VUHDO_I18N_MAX_COLUMNS = "max. Colonnes";
VUHDO_I18N_MAX_ROWS = "max. Lignes";
VUHDO_I18N_CLEAR_PANELS_CONFIRM = "Supprimer le mod\195\168le de panneau?!";
VUHDO_I18N_BUFF_NAME = "Nom du buff";
VUHDO_I18N_BUFF_ON_PLAYER = "sur le nom du joueur:";
VUHDO_I18N_ALWAYS = "Toujours";
VUHDO_I18N_NEVER = "Jamais";
VUHDO_I18N_BUFF_PANEL_BG = "Panneau";


-- VuhDoOptionsGeneral.lua
-- @EXACT = false
VUHDO_I18N_CLEANSE = "Nettoyer";
VUHDO_I18N_RESURRECT = "Ressusciter";
VUHDO_I18N_SMART_CAST_OO_COMBAT = "S\195\169lection automatique du sort";
VUHDO_I18N_IGNORE_IRRELEVANT = "Ignorer les cas inutiles...";
VUHDO_I18N_BY_CLASS = "Classe";
VUHDO_I18N_MOVEMENT_IMPAIRING = "Mouvement";
VUHDO_I18N_BY_DURATION = "Dur\195\169e";
VUHDO_I18N_BY_NON_HARMFUL = "non offensifs";
VUHDO_I18N_SHOW_ALL = "Show All";
VUHDO_I18N_ESTIMATE = "Estim\195\169";
VUHOD_I18N_BY_SPELL = "par sort";
VUHDO_I18N_SHOW_INC = "Soins en court";
VUHDO_I18N_SHOW_OWN_HEAL = "personnel";
VUHDO_I18N_SHOW_OVERHEAL = "Soins exc\195\169dentaire";
VUHDO_I18N_OPERATION_MODE = "Mode op\195\169ratoire";
VUHDO_I18N_MAX_EMERGENCIES = "max. Urgences";
VUHDO_I18N_RELVEVANCE = "Inutile si + de";
VUHDO_I18N_NEUTRAL_HEALBOT = "Neutre";
VUHDO_I18N_EMERGENCY_PERCENT = "Urgence - PV %";
VUHDO_I18N_EMERGENCY_MOST_MISSING = "Le plus de PV manquants";
VUHDO_I18N_EMERGENCY_LEAST_LEFT = "Le moins de PV restants";



-- VuhDoFormButtonColor.lua
-- @EXACT = false
-- Labels
VUHDO_I18N_TEXT = "Texte";
VUHDO_I18N_DEBUFFS = "Debuffs";
VUHDO_I18N_ANOMALIES = "Anomalies";
VUHDO_I18N_OPACITY = "Opacit\195\169e";


-- VuhDoFormButtonSize.lua
-- @EXACT = false
VUHDO_I18N_PANEL = "Panneau";
VUHDO_I18N_SPACING = "Espacement";
VUHDO_I18N_BAR_HEIGHT = "Hauteur";
VUHDO_I18N_TARGETS = "Cibles";
VUHDO_I18N_BAR_TEXTURE = "Texture des barres";
VUHDO_I18N_HEIGHT = "Hauteur";
VUHDO_I18N_BAR_WIDTH = "Largueur";
VUHDO_I18N_WIDTH = "Largueur";
VUHDO_I18N_HEADERS = "Ent\195\170tes";
VUHDO_I18N_CLASS_COL = "Col. de classe";
--



-- VuhDoOptionsSpell.lua
-- @EXACT = false
VUHDO_I18N_KEY_MODIFIES = "Touche modificatrice";
VUHDO_I18N_KEY_NONE = "Aucun";
VUHDO_I18N_ALT = "Alt";
VUHDO_I18N_CTRL = "Ctrl";
VUHDO_I18N_SHIFT = "Shift";
VUHDO_I18N_LEFT_BUTTON = "Clique gauche";
VUHDO_I18N_RIGHT_BUTTON = "Clique droit";
VUHDO_I18N_MIDDLE_BUTTON = "Clique milieu";
VUHDO_I18N_BUTTON_4 = "Bouton 4";
VUHDO_I18N_BUTTON_5 = "Bouton 5";
VUHDO_I18N_MOUSE_KEY = "Touche pour la souris";
VUHDO_I18N_IN_MACROS_USE = "(dans les macros utiliser \"vuhdo\" \195\160 la place du nom de la cible)";
VUHDO_I18N_SPELL_STATIC = "ou target/focus/assist/menu/tell/dropdown";
VUHDO_I18N_NAME_TIP = "Nom du sort, Macro ou Item,";
VUHDO_I18N_PLUS_SHIFT = "+Shift";
VUHDO_I18N_PLUS_CTRL_SHIFT = "+Ctrl+Shift";
VUHDO_I18N_PLUS_CTRL = "+Ctrl";



-- VuhDoTooltipConfig.lua
-- @EXACT = false
VUHDO_I18N_AROUND_PANEL = "Autour du panneau";
VUHDO_I18N_SHOW_IN_FIGHT = "en combat";

-- New Options - Tooltips
-- @EXACT = false
VUHDO_I18N_TT_001 = "Configure les buffs que vuhdo va g\195\169rer.";
VUHDO_I18N_TT_002 = "Choisir l'apparence g\195\169n\195\169ral du panneau de suivi des buffs.";
VUHDO_I18N_TT_003 = "Choisir la couleur des diff\195\169rents indicateurs.";
VUHDO_I18N_TT_004 = "Ajuster le param\195\169trage des timers et s\195\169lectionner la version des buffs.";

VUHDO_I18N_TT_005 = "Ajuster la taille g\195\169n\195\169ral du panneau de suivi des buffs.";
VUHDO_I18N_TT_006 = "Fixer le nombre maximum d'indicateurs de buff par ligne.";
VUHDO_I18N_TT_007 = "Fixer le nombre maximum d'indicateurs de buff par colonne.";
VUHDO_I18N_TT_008 = "Fixer le taux de rafraichissement des indicateurs de buff.";
VUHDO_I18N_TT_009 = "Indiquer le nom du buff dans le titre.";
VUHDO_I18N_TT_010 = "Afficher les buffs de groupe qui sont vides.";
VUHDO_I18N_TT_011 = "Activer le suivi de buffs.";

VUHDO_I18N_TT_012 = "Choisir une couleur pour les buffs dont la dur\195\169e restante est satisfaisante.";
VUHDO_I18N_TT_013 = "Choisir une couleur pour les buffs qui vont bient\195\180t expirer.";
VUHDO_I18N_TT_014 = "Choisir une couleur pour les buffs manquants.";
VUHDO_I18N_TT_015 = "Choisir une couleur pour indiquer que la cible est hors de port\195\169e et le buff ne peut \195\170tre appliqu\195\169.";
VUHDO_I18N_TT_016 = "Choisir une couleur pour indiquer que la comp\195\169tence de buff n'est pas encore disponible (cooldown).";
VUHDO_I18N_TT_017 = "Choisir une couleur pour les buff groups qui sont actuellement vides.";
VUHDO_I18N_TT_018 = "Choisir une couleur pour le fond du panneau de buff.";
VUHDO_I18N_TT_019 = "Choisir une couleur pour le contour des indicateurs de buff.";
VUHDO_I18N_TT_020 = "Choisir une couleur pour le contour du panneau de suivi des buffs.";

VUHDO_I18N_TT_021 = "Cochez pour faire clignoter le buff quand la comp\195\169tence est disponible.";
VUHDO_I18N_TT_022 = "D\195\169finir \195\160 quel pourcentage de la dur\195\169e de l'indicateur de buff passe de OK \195\160 BAS";
VUHDO_I18N_TT_023 = "D\195\169finir la dur\195\169e restante en minutes pour laquelle l'\195\169tat du buff va passer de OK \195\160 BAS.";
VUHDO_I18N_TT_024 = "Rebuffer les membres du raid en fonction du curseur ci-dessous.";
VUHDO_I18N_TT_025 = "Toujours utiliser la version individuelle de votre buff (ex. si vous n'avez plus de composants).";
VUHDO_I18N_TT_026 = "Toujours utiliser la version raid de votre buff.";
VUHDO_I18N_TT_027 = "Fixer le nombre de joueurs dont le buff est BAS \195\160 partir duquel la version raid de votre buff sera utilis\195\169e \195\160 la place de la version individuelle.";

VUHDO_I18N_TT_028 = "Choisir les couleurs affich\195\169es suivant l'\195\169tat du joueur.";
VUHDO_I18N_TT_029 = "Choisir les couleurs en fonction du mode d'affichage s\195\169lectionn\195\169.";

VUHDO_I18N_TT_031 = "Changer la couleur qui indique une urgence (un des modes d'urgence doit \195\170tre activ\195\169).";
VUHDO_I18N_TT_032 = "Changer la couleur qui indique qu'un joueur n'est pas en urgence (un des modes d'urgence doit \195\170tre activ\195\169).";
VUHDO_I18N_TT_033 = "Changer la couleur qui indique qu'un joueur ne requiert aucune action au sens ou sa vie est suffisante. (cf.: Inidice de pertinence dans le panneau des options de base)";
VUHDO_I18N_TT_034 = "Changer la couleur des soins en cours sur un joueur (La visualisation des soins en cours doit \195\170tre activ\195\169e)";
VUHDO_I18N_TT_035 = "Changer la couleur des joueurs hors de port\195\169e (La v\195\169rification de la port\195\169e doit \195\170tre activ\195\169e)";

VUHDO_I18N_TT_036 = "Changer la couleur indiquant les joueurs morts.";
VUHDO_I18N_TT_037 = "Changer la couleur indiquant les joueurs hors ligne.";
VUHDO_I18N_TT_038 = "Changer la couleur indiquant les joueurs qui sont sous contr\195\180le mental";
VUHDO_I18N_TT_039 = "Changer la couleur de bar d'aggro.";
VUHDO_I18N_TT_040 = "Changer la couleur indiquant les joueurs empoisonn\195\169s.";
VUHDO_I18N_TT_041 = "Changer la couleur des joueurs malades.";
VUHDO_I18N_TT_042 = "Changer la couleur des joueurs maudits.";
VUHDO_I18N_TT_043 = "Changer la couleur des joueurs affect\195\169s par un debuff magiques.";

VUHDO_I18N_TT_044 = "Configurer les comportements de base de VuhDo.";
VUHDO_I18N_TT_045 = "S\195\169lectionner quelles informations VuhDo va rechercher.";

VUHDO_I18N_TT_046 = "Laisser VuhDo s\195\169lectionner le sort appropri\195\169 hors de combat.";
VUHDO_I18N_TT_047 = "S\195\169lectionner automatiquement le rang du sort le plus adapt\195\169 hors de combat (inutile depuis la 2.3)";
VUHDO_I18N_TT_048 = "Debuff automatiquement avant de soigner si hors combat.";
VUHDO_I18N_TT_049 = "Ressuciter automatiquement les joueurs morts si hors combat.";
VUHDO_I18N_TT_050 = "Activer le lancer de sort intelligent quand hors combat.";
VUHDO_I18N_TT_051 = "Detecter l'aggro sur les joueurs.";
VUHDO_I18N_TT_052 = "S\195\169lectionner pour inspecter les logs de combat. Augmente consid\195\169rablement les performances.";
VUHDO_I18N_TT_053 = "Sp\195\169cifier le type d'affichage g\195\169n\195\169ral. Pr\195\169f\195\169rer \"Neutre\" a moins d'\195\170tre dans un grand raid.";
VUHDO_I18N_TT_054 = "Fixer le nombre maximum de joueurs avec la vie la plus basse affich\195\169. Non applicable si le mode est \"Neutre\"";
VUHDO_I18N_TT_055 = "Fixer un pourcentage max. de vie au-del� duquel les joueurs sont consid\195\169r\195\169s bien portants, ce qui signifie qu'ils seront l\195\169g\195\169rement translucide (configurable).";

VUHDO_I18N_TT_056 = "Ignorer les debuffs non offensifs (d� \195\160 leur nature m\195\170me).";
VUHDO_I18N_TT_057 = "Ignorer les debuffs qui ne font que ralentir les d\195\169placements.";
VUHDO_I18N_TT_058 = "Ignorer les debuffs qui ont une dur\195\169e tr\195\169s courte.";
VUHDO_I18N_TT_059 = "Ignorer les debuffs qui n'ont aucun impact sur la classe du joueur (ie. drain de mana sur un voleur).";
VUHDO_I18N_TT_060 = "Montrer uniquement les debufs qui peuvent \195\170tre enlev\195\169 par votre classe. Tous les debuffs seront montr\195\169s sinon.";
VUHDO_I18N_TT_061 = "Si s\195\169lectionn\195\169, la d\195\169tection des debuffs est g\195\169n\195\169ralement engag\195\169.";
VUHDO_I18N_TT_062 = "L'\"Overheal\" illuminera la barre de vie si s\195\169lectionn\195\169.";
VUHDO_I18N_TT_063 = "Voir aussi les soins en cours fait par vous m\195\170me. Ceci est per\195\167u comme d\195\169concertant par certains joueurs.";
VUHDO_I18N_TT_064 = "Indiquer les soins pr\195\169vus. Ceci peut aider \195\160 r\195\169duire l'overheal.";
VUHDO_I18N_TT_065 = "Fixer le taux de rafraichissement si le joueur est \195\160 port\195\169e. Info: Une valeur basse peut r\195\169duire les performances du syst\195\168me.";
VUHDO_I18N_TT_066 = "V\195\169rifier la port\195\169e \195\160 l'aide d'un sort standard. S\195\169lectionner cette option si vous n'avez pas de sort b\195\169n\195\169fique.";
VUHDO_I18N_TT_067 = "Indiquer le nom du sort permettant de v\195\169rifier la port\195\169e.";
VUHDO_I18N_TT_068 = "Utiliser le sort sp\195\169cifi\195\169 afin de v\195\169rifier la port\195\169e.";
VUHDO_I18N_TT_069 = "Activer la v\195\169rification de port\195\169e.";

VUHDO_I18N_TT_070 = "Pourcentage de la hauteur d'une barre pour la taille des HoT.";
VUHDO_I18N_TT_071 = "Afficher les HoTs \195\160 DROITE, \195\160 l'INTERIEUR de la barre de vie.";
VUHDO_I18N_TT_072 = "Afficher les HoTs \195\160 GAUCHE, \195\160 l'INTERIEUR de la barre de vie.";
VUHDO_I18N_TT_073 = "Afficher les HoTs \195\160 GAUCHE, \195\160 l'EXTERIEUR de la barre de vie.";
VUHDO_I18N_TT_074 = "Afficher les HoTs \195\160 DROITE, \195\160 l'EXTERIEUR de la barre de vie.";
VUHDO_I18N_TT_075 = "Afficher vos propres HoTS par barre de vie.";
VUHDO_I18N_TT_076 = "Selectionner la texture de fond de vos barres \195\160 partir de leur nom.";
VUHDO_I18N_TT_077 = "D\195\169placer pour changer la texture de fond des barres.";
VUHDO_I18N_TT_078 = "Changer la couleur de fond des panneaux.";
VUHDO_I18N_TT_079 = "Changer la couleur des bordures des panneaux.";
VUHDO_I18N_TT_080 = "Cochez pour afficher les types de pouvoir autres que la mana.";
VUHDO_I18N_TT_081 = "Glisser pour changer la taille des barres de mana.";
VUHDO_I18N_TT_082 = "Cochez pour afficher les barres de mana dans le panneau.";

VUHDO_I18N_TT_083 = "S\195\169lectionner le nombre max. de groupes par ligne avant un retour \195\160 la ligne quand \"group\195\169\" est s\195\169lectionn\195\169.";
VUHDO_I18N_TT_084 = "Afficher les joueurs dans le panneau de soins s\195\169lectionn\195\169 sans les trier par groupe ou par classe. Ceci va masquer automatiquement les titres.";
VUHDO_I18N_TT_085 = "Afficher les joueurs dans le panneau de soins s\195\169lectionn\195\169 tri\195\169s par groupe ou par classe";
VUHDO_I18N_TT_086 = "Masquer les groupes vides dans votre raid. (Seulement si \"group\195\169\" est s\195\169lectionn\195\169).";
VUHDO_I18N_TT_087 = "Selectionner le nombre max. de colonnes par ligne avant un retour \195\160 la ligne.";
VUHDO_I18N_TT_088 = "Placer l'ancre du panneau en haut \195\160 gauche.";
VUHDO_I18N_TT_089 = "Placer l'ancre du panneau en haut \195\160 droite.";
VUHDO_I18N_TT_090 = "Placer l'ancre du panneau en bas \195\160 gauche.";
VUHDO_I18N_TT_091 = "Placer l'ancre du panneau en bas \195\160 droite.";
VUHDO_I18N_TT_092 = "Trier les joueurs au sein du panneau comme il appara�t dans l'interface de raid Blizzard.";
VUHDO_I18N_TT_093 = "Trier les joueurs au sein du panneau par leur nombre de points de vie.";
VUHDO_I18N_TT_094 = "Trier les joueurs au sein du panneau par ordre alphab\195\169tique en fonction de leur nom.";

VUHDO_I18N_TT_095 = "Glisser pour changer la hauteur des titres.";
VUHDO_I18N_TT_096 = "Glisser pour changer l'espacement entre les titres et les barres.";
VUHDO_I18N_TT_097 = "Afficher les titres. (Note: \"Basic\"=>\"group\195\169\" doit \195\170tre s\195\169lectionn\195\169.)";
VUHDO_I18N_TT_098 = "D\195\169placer pour changer la texture de fond des titres.";
VUHDO_I18N_TT_099 = "S\195\169lectionner la texture de fond des titres par leur nom.";
VUHDO_I18N_TT_100 = "D\195\169placer pour ajuster le fond des titres en tant que pourcentage de la largeur des barres.";
VUHDO_I18N_TT_101 = "D\195\169placer pour ajuster la taille du texte des titres.";
VUHDO_I18N_TT_102 = "Cochez pour afficher le texte titres en fonction de la couleur des classes. (Note: Seulement si le titre repr\195\169snte une classe)";
VUHDO_I18N_TT_103 = "Changer le fond des titres et la couleur du texte.";

VUHDO_I18N_TT_104 = "Configurer l'apparence des panneaux de titre.";
VUHDO_I18N_TT_105 = "Configurer l'apparence de base des panneaux.";
VUHDO_I18N_TT_106 = "Configurer l'apparence de l'aide contextuelle.";
VUHDO_I18N_TT_107 = "Configurer le format et l'apparence du texte sur les barres de vie.";
VUHDO_I18N_TT_108 = "Configurer la pr\195\169sence et l'apparence de la cible du joueur dans le panneau.";
VUHDO_I18N_TT_109 = "Configurer la hauteur et la largeur des barres de vie, ainsi que la distance des bordures et l'espacement.";
VUHDO_I18N_TT_110 = "Configurer l'apparence des barres de vie, le fond du panneau et la couleur des bordures.";
VUHDO_I18N_TT_111 = "Cliquer pour avoir le SOUS-MENU COURANT de configuration appliqu\195\169 \195\160 l'ensemble de vos panneaux.";

VUHDO_I18N_TT_112 = "S\195\169lectionner l'espacement horizontal entre les barres de vie.";
VUHDO_I18N_TT_113 = "S\195\169lectionner l'espacement vertical entre les barres de vie.";
VUHDO_I18N_TT_114 = "S\195\169lectioner l'espacement vertical entre les bordures et la barre de vie.";
VUHDO_I18N_TT_115 = "S\195\169lectioner l'espacement horizontal entre les bordures et la barre de vie.";
VUHDO_I18N_TT_116 = "S\195\169lectionner la hauteur de la barre de vie dans le panneau.";
VUHDO_I18N_TT_117 = "S\195\169lectionner la largeur de la barre de vie dans le panneau.";

VUHDO_I18N_TT_118 = "D\195\169placer pour ajuster l'espacement entre la barre de vie et la barre de la cible.";
VUHDO_I18N_TT_119 = "Afficher la cible du jouer dans le panneau courant.";
VUHDO_I18N_TT_120 = "D\195\169placer pour modifier la largeur de la cible du joueur dans le panneau courant.";
VUHDO_I18N_TT_121 = "S\195\169lectionner l'affichage simultan\195\169 de l'ic\195\180nes de raid et du nom de la cible.";
VUHDO_I18N_TT_122 = "S\195\169lectionner l'affichage seul de l'ic\195\180nes de raid \195\160 la place du nom de la cible. (si il y a une ic\195\180ne de raid)";
VUHDO_I18N_TT_123 = "S\195\169lectionner l'affichage seul du nom de la cible sans ic\195\180ne de raid";
VUHDO_I18N_TT_124 = "Ajuster la taille du texte du nom de la cible.";

VUHDO_I18N_TT_126 = "Afficher les points de vie sous forme de pourcentage.";
VUHDO_I18N_TT_127 = "Afficher les points de vie en fonction du nombre de points de vie manquants.";
VUHDO_I18N_TT_128 = "Afficher les points de vie en fonction du nombre de points de vie restants.";
VUHDO_I18N_TT_129 = "Afficher le texte des points de vie \195\160 droites du nom du joueur.";
VUHDO_I18N_TT_130 = "Afficher le texte des points de vie \195\160 gauche du nom du joueur";
VUHDO_I18N_TT_131 = "Afficher le texte des points de vie sous du nom du joueur.";
VUHDO_I18N_TT_132 = "Afficher le texte des points de vie sur du nom du joueur.";
VUHDO_I18N_TT_133 = "Afficher le texte des points de vie sur la barre de vie.";
VUHDO_I18N_TT_134 = "Ajuster la taille du texte sur la barre de vie.";
VUHDO_I18N_TT_135 = "Afficher le nom du joueur en fonction de la couleur de sa classe.";
VUHDO_I18N_TT_136 = "Change la couleur du texte de la barre de vie.";
VUHDO_I18N_TT_137 = "Change la couleur du fond de chaque barre de vie. (Note: ceci n'est PAS la couleur de fond du panneau).";

VUHDO_I18N_TT_138 = "D\195\169placer librement l'aide contextuelle autour du panneau. Glisser ensuite l'aide pour d\195\169finir sa position.";
VUHDO_I18N_TT_139 = "Toujours placer l'aide contextuelle sous le curseur de la souris. (Note: ceci peut impacter les performances)";
VUHDO_I18N_TT_140 = "Afficher l'aide contextuelle \195\160 sa position habituelle.";
VUHDO_I18N_TT_141 = "Afficher l'aide contextuelle.";
VUHDO_I18N_TT_142 = "Afficher \195\169galement l'aide contextuelle en vol.";
VUHDO_I18N_TT_143 = "Adjuster la taille globale de l'aide contextuelle.";
VUHDO_I18N_TT_144 = "Selectionner la couleur de fond de l'aide contextuelle.";
VUHDO_I18N_TT_145 = "Selectionner la couleur de la bordure de l'aide contextuelle.";

VUHDO_I18N_TT_146 = "S\195\169lectionner un sort sur la combinaison de touche \"ALT+SHIFT\".";
VUHDO_I18N_TT_147 = "S\195\169lectionner un sort sur la combinaison de touche \"CTRL\".";
VUHDO_I18N_TT_148 = "S\195\169lectionner un sort sur la combinaison de touche \"CTRL+SHIFT\".";
VUHDO_I18N_TT_149 = "S\195\169lectionner un sort sur la combinaison de touche \"ALT+CTRL+SHIFT\".";
VUHDO_I18N_TT_150 = "S\195\169lectionner un sort sans combinaison de touche";
VUHDO_I18N_TT_151 = "S\195\169lectionner un sort sur la combinaison de touche \"ALT\".";
VUHDO_I18N_TT_152 = "S\195\169lectionner un sort sur la combinaison de touche \"SHIFT\".";
VUHDO_I18N_TT_153 = "S\195\169lectionner un sort sur la combinaison de touche \"ALT+CTRL\".";

VUHDO_I18N_TT_154 = "Terminer la configuration en confirmant l'ensemble des modifications.";
VUHDO_I18N_TT_155 = "Annuler la configuration. Aucune modification ne sera appliqu\195\169e.";

VUHDO_I18N_TT_156 = "Masquer les charges restantes pour les buffs avec une charge > 1.";
VUHDO_I18N_TT_157 = "Change la couleur des pouvoirs tels que mana, �nergie ou rage."
VUHDO_I18N_TT_158 = "S\195\169lectionner la couleur de la barre de mana."
VUHDO_I18N_TT_159 = "S\195\169lectionner la couleur de la barre de rage."
VUHDO_I18N_TT_160 = "S\195\169lectionner la couleur de la barre d'�nergie."
VUHDO_I18N_TT_161 = "S\195\169lectionner la couleur de la barre de pouvoir runique."
VUHDO_I18N_TT_162 = "Configurer l'affichage de l'aggro/menace"
VUHDO_I18N_TT_163 = "Configurer les autres options."
VUHDO_I18N_TT_164 = "Charger ou sauvegarder une apparence afin de simplifier les modifications d'affichage."
VUHDO_I18N_TT_165 = "Masquer les tanks principaux dans les panneaux de groupes/classes afin d'\195\169viter un affichage redondant."
VUHDO_I18N_TT_166 = "Masquer les cibles personnelles dans les panneaux de groupes/classes afin d'\195\169viter un affichage redondant."
VUHDO_I18N_TT_167 = "Masquer votre groupe de l'affichage standard. (Vous devez avoir un panneau groupe \"Mon groupe\" selectionn\195\169 comme groupe dans VuhDo)"
VUHDO_I18N_TT_168 = "Montrer les status afk, d/c, ou dead sur le nom du joueur"
VUHDO_I18N_TT_169 = "Masquer l'affichage Blizzard standard des groupes."
VUHDO_I18N_TT_170 = "Masquer l'affichage Blizzard standard des joueurs."
VUHDO_I18N_TT_171 = "Afficher les HoTs multiples seulement sur la personne sur laquelle se trouve le HoT."
VUHDO_I18N_TT_172 = "Afficher les HoTs multiples sur toute personne affect\195\169 par le HoT. ATTENTION: Cette option peut d\195\169grader les performances du syst\195\168me!"
VUHDO_I18N_TT_173 = "Selectionner le taux de rafra�chissement pour la mise \195\160 jour des HoTs" -- 173
VUHDO_I18N_TT_174 = "Entrer le nom d'une apparence existante \195\160 charger, \195\169craser ou supprimer, ou entrer un nouveau nom afin de sauvegarder l'apparence courante."
VUHDO_I18N_TT_175 = "Selectionner une apparence. Une apparence est l'ensemble des param\195\169trage visuels comme les couleurs, les textures, etc."
VUHDO_I18N_TT_176 = "Entrer le nom d'une apparence existante \195\160 charger, \195\169craser ou supprimer, ou entrer un nouveau nom afin de sauvegarder l'apparence courante."
VUHDO_I18N_TT_177 = "Selectionner un arrangement. Un arrangement est l'ensemble des param\195\169trage de taille, forme, position d\195\169finis."
VUHDO_I18N_TT_178 = "S\195\169lectionner le pourcentage de menace \195\160 partir duquel la barre des d\195\169tenteur d'aggro passera de cyan \195\160 magenta"
VUHDO_I18N_TT_179 = "Fixer la hauteur des barres de menace"
VUHDO_I18N_TT_180 = "Afficher les d\195\169g\195\162ts excessifs et le gain d'aggro sous la forme de lignes de faibles pulsations \195\160 cot\195\169 de chaque bouton de soin."
VUHDO_I18N_TT_181 = "Afficher la menace g\195\169n\195\169r\195\169e par un joueur sous la forme d'une barre sous les boutons de soins."
VUHDO_I18N_TT_182 = "V\195\169rifier l'aggro/menace" -- 182
VUHDO_I18N_TT_183 = "S\195\169lectionner une fr\195\169quence en ms pour le rafra�chissement de l'aggro/menace."
VUHDO_I18N_TT_184 = "S\195\169lectionner le texte \195\160 afficher \195\160 gauche du joueur qui a l'aggro."
VUHDO_I18N_TT_185 = "Indiquer l'aggro par une texte associer au joueur."
VUHDO_I18N_TT_186 = "Indiquer l'aggro par une ligne sous le bouton du joueur."
VUHDO_I18N_TT_187 = "Laisser VuhDo v\195\169rifier l'aggro"
VUHDO_I18N_TT_188 = "S\195\169lectionner le texte \195\160 afficher \195\160 droite du joueur qui a l'aggro." -- 188
VUHDO_I18N_TT_189 = "Afficher le groupe/raid pour test."
VUHDO_I18N_TT_190 = "Afficher un groupe de 5 joueurs pour test."
VUHDO_I18N_TT_191 = "Afficher un raid de 10 joueurs pour test."
VUHDO_I18N_TT_192 = "Afficher un raid de 25 joueurs pour test."
VUHDO_I18N_TT_193 = "Afficher un raid de 40 joueurs pour test." -- 193
VUHDO_I18N_TT_194 = "S\195\169lectionner afin de remplacer la couleur de la barre de vie des joueurs (de vert \195\160 rouge) par la couleur de leur classe."
VUHDO_I18N_TT_195 = "S\195\169lectionner une fonte pour le texte des titres"
VUHDO_I18N_TT_196 = "Afficher \195\169galement le fond des titres en fonction de la couleur de la classe."
VUHDO_I18N_TT_197 = "S\195\169lectionner la couleur du texte du nom de la cible." -- 197
VUHDO_I18N_TT_198 = "S\195\169lectionner les sorts \195\160 assigner aux boutons de la souris."
VUHDO_I18N_TT_199 = "S\195\169lectionner les sorts \195\160 assigner aux raccourcis clavier (mouseover)."
VUHDO_I18N_TT_200 = "Selectionner les bijoux/sorts \195\160 d\195\169clencher automatiquement d\195\169s qu'ils sont activable."
VUHDO_I18N_TT_201 = "Entrer le nom du sort instantan\195\169 \195\160 d\195\169clencher avant le soin. Note: Ce sort ne doit pas d\195\169clencher le GCD!"
VUHDO_I18N_TT_202 = "Entrer le nom du sort instantan\195\169 \195\160 d\195\169clencher avant le soin. Note: Ce sort ne doit pas d\195\169clencher le GCD!"
VUHDO_I18N_TT_203 = "D\195\169clencher le sort d\195\169fini \195\160 droites avant le soin. Note: Ce sort ne doit pas d\195\169clencher le GCD!"
VUHDO_I18N_TT_204 = "D\195\169clencher le sort d\195\169fini \195\160 droites avant le soin. Note: Ce sort ne doit pas d\195\169clencher le GCD!" -- 204
VUHDO_I18N_TT_205 = "D\195\169clencher le bijou 2 (en bas sur votre feuille de personnage) avant le soin. Note: Ce sort ne doit pas d\195\169clencher le GCD!"
VUHDO_I18N_TT_206 = "D\195\169clencher le bijou 1 (en haut sur votre feuille de personnage) avant le soin. Note: Ce sort ne doit pas d\195\169clencher le GCD!"
VUHDO_I18N_TT_207 = "D\195\169clenchement automatique des bijoux hors combat."
VUHDO_I18N_TT_208 = "D\195\169clenchement automatique des bijoux \195\169galement sur les HoTs."
VUHDO_I18N_TT_209 = "Active/D\195\169sactive le d\195\169clenchement automatique des bijoux/sorts."
VUHDO_I18N_TT_210 = "Entrez un texte qui sera montr� dans le chat lorsque vous d�marrez ressusciter quelqu'un. Utilisez \"vuhdo\" comme espace r�serv� pour le nom";
VUHDO_I18N_TT_211 = "Cochezz pour voir le texte du chat, lorsque vous d�marrez une r�surrection. Utilisez \"vuhdo\" comme espace r�serv� au texte pour le nom";
VUHDO_I18N_TT_212 = "Cochezz enti�rement les panneaux cacher et vides.";
VUHDO_I18N_TT_213 = "Cochez cette case pour ne pas montrer le focus de votre cible dans \"Private Tanks\" Panneau de configuration.";
VUHDO_I18N_TT_214 = "Cochez cette case pour ne pas montrer les assistants r�guli�rement dans les cadres raid/groupe.";
VUHDO_I18N_TT_215 = "Cochez cette option pour rebuff les buffs manquants en hors-combat. Buffs doit �tre activ� et a une couleur attribu�e � VuhDo BuffWatch.";
VUHDO_I18N_TT_216 = "S�lectionnez cette option pour afficher les heals entrants, provenant du raid/membres.";
VUHDO_I18N_TT_217 = "Cochez pour ajouter entrants/overheal en texte de la vie sur les barres";
VUHDO_I18N_TT_218 = "Modifier cette barre pour r�gler l'�chelle du texte de l'overheal.";
VUHDO_I18N_TT_219 = "Contr�le l'affichage du texte de l'overheal dans un texte (blanc) suppl�mentaire sur les barres.";
VUHDO_I18N_TT_220 = "Cliquez pour voir un cadre rouge autour de joueurs ayant l'aggro.";
VUHDO_I18N_TT_221 = "Cochez cette case pour montrer les buffs manquants � mi-combat.";
VUHDO_I18N_TT_222 = "Cochez cette case pour montrer les buffs manquants par la couleur du texte.";
VUHDO_I18N_TT_223 = "Cochez cette case pour montrer les buffs manquants dans une barre de couleur.";
VUHDO_I18N_TT_224 = "S�lectionnez ce menu pour configurer les couleurs de base pour les carr�s des HoT";
VUHDO_I18N_TT_225 = "S�lectionnez ce menu pour une configuration avanc�e des couleurs pour les carr�s HoT";
VUHDO_I18N_TT_226 = "Organisation des couleurs de classe";
VUHDO_I18N_TT_227 = "S�lectionnez la luminosit� des couleurs de l'arri�re-plan des barres de classe comme le pourcentage des couleurs de la barre.";
VUHDO_I18N_TT_228 = "Cochez cette case si vous avez des couleurs de classe du familier au lieu de couleurs personnalis�es.";
VUHDO_I18N_TT_229 = "Choisir une couleur - Tank";
VUHDO_I18N_TT_230 = "Choisir une couleur - Voleur";
VUHDO_I18N_TT_231 = "Choisir une couleur - Chasseur";
VUHDO_I18N_TT_232 = "Choisir une couleur - Paladin";
VUHDO_I18N_TT_233 = "Choisir une couleur - d�monise";
VUHDO_I18N_TT_234 = "Choisir une couleur - chaman";
VUHDO_I18N_TT_235 = "Choisir une couleur - Druide";
VUHDO_I18N_TT_236 = "Choisir une couleur - Pr�tre";
VUHDO_I18N_TT_237 = "Choisir une couleur - Mage";
VUHDO_I18N_TT_238 = "Choisir une couleur - Chavalier de la mort";
VUHDO_I18N_TT_239 = "Choisir une couleur - familier";
VUHDO_I18N_TT_240 = "Cochez l'affichage du num�ro des appliances of the HoT. Si la carr� est s�lectionn� � la place des ic�nes, il y aura quatre petits triangles d'indiquer.";
VUHDO_I18N_TT_241 = "Cochez l'affichage du num�ro des HoT par la couleur du texte � gauche.";
VUHDO_I18N_TT_242 = "Cochez l'affichage du num�ro des HoT par la couleur de fond vers la gauche.";
VUHDO_I18N_TT_243 = "Choisir une couleur pour les HoTs ayant 2 charges appliqu�es";
VUHDO_I18N_TT_244 = "Choisir une couleur pour les HoTs ayant 3 charges appliqu�es";
VUHDO_I18N_TT_245 = "Choisir une couleur pour les HoTs ayant 4 charges appliqu�es";
VUHDO_I18N_TT_246 = "Choisirune couleur pour les HoT barre 1";
VUHDO_I18N_TT_247 = "Choisir une couleur pour les HoT barre 2";
VUHDO_I18N_TT_248 = "Choisir une couleur pour les HoT barre 3";
VUHDO_I18N_TT_249 = "Choisir une couleur pour les HoT carr�s 1";
VUHDO_I18N_TT_250 = "Choisir une couleur pour les HoT carr�s 2";
VUHDO_I18N_TT_251 = "Choisir une couleur pour les HoT carr�s 3";
VUHDO_I18N_TT_252 = "Choisir une couleur pour les HoT carr�s 4";
VUHDO_I18N_TT_253 = "Choisir une couleur pour les HoT carr�s 5";
VUHDO_I18N_TT_254 = "Choisir une couleur pour les HoTs avec une faible dur�e";
VUHDO_I18N_TT_255 = "Choisir la dur�e de l'avertissement et de la couleur qui sera appliqu�e et la pr�cision (secs/10) qui sera affich�e.";
VUHDO_I18N_TT_256 = "Cochez pour avoir un contour autour du compteur des HoT et du texte de la minuterie.";
VUHDO_I18N_TT_257 = "Cochez pour avoir une ombre derri�re le compteur des HoT et du texte de la minuterie.";
VUHDO_I18N_TT_258 = "Cochez pour voir la dur�e de couleur de l'alerte des HoT restants est inf�rieur � configur� pour la gauche.";
VUHDO_I18N_TT_259 = "Cochez pour afficher les carr�s / ic�nes pour les Hots. Seul le texte sera affich� autrement.";
VUHDO_I18N_TT_260 = "Cochez pour la disparition des ic�nes/carr�s quand les Hot sont presque �puis�s";
VUHDO_I18N_TT_261 = "Choisissez une couleur pour vos debuffs autod�finis";
VUHDO_I18N_TT_262 = "Cochez pour avoir aussi les ic�nes des debuff volant dedans.";
VUHDO_I18N_TT_263 = "Cette option permet de s�lectionner que les debuffs que vous voulez voir.";
VUHDO_I18N_TT_264 = "S�lectionnez cette option pour les buffs et debuffs personnalis�s que vous voulez voir.";
VUHDO_I18N_TT_265 = "Les panneaux Wizards vous permettent de cr�er vos groupes de panneau avec seulement quelques clics.";
VUHDO_I18N_TT_266 = "Cochez l'affichage personnalis� des (de)buffs par ic�nes.";
VUHDO_I18N_TT_267 = "Cochez l'affichage personnalis� des (de)buffs par barre de couleur";
VUHDO_I18N_TT_268 = "Cochez pour voir l'effet d'animation sur les ic�nes.";
VUHDO_I18N_TT_269 = "Cochez pour voir le compteur de dur�e restant sur les ic�nes.";
VUHDO_I18N_TT_270 = "D�placer pour changer l'�chelle des ic�nes de (de)buff.";
VUHDO_I18N_TT_271 = "D�placer pour d�terminer le max. nombre de (de)buffs � montrer � la fois.";
VUHDO_I18N_TT_272 = "S�lectionnez un son qui sera jou� pour un debuff personnalis�.";
VUHDO_I18N_TT_273 = "Cochez pour montrer le mode de (de)buffs par ic�ne.";
VUHDO_I18N_TT_274 = "Cochez pour montrer le mode de (de)buffs par une barre de couleur.";
VUHDO_I18N_TT_275 = "Cochez pour voir l'effet d'animation sur les ic�nes.";
VUHDO_I18N_TT_276 = "Cochez pour voir le compteur de dur�e restant sur les ic�nes.";
VUHDO_I18N_TT_277 = "Choisissez une couleur pour la bordure du joueur en cible dans les barres de sant�.";
VUHDO_I18N_TT_278 = "Choisissez une couleur pour la bordure autour de chaque barre de sant�.";
VUHDO_I18N_TT_279 = "S�lectionnez un son qui sera jou� quand un joueur gagne un debuff";
VUHDO_I18N_TT_280 = "Cliquez ici pour appliquer le programme d'installation choisi pour vos panneaux";
VUHDO_I18N_TT_281 = "Cochez cette case pour avoir un panneau suppl�mentaire pour les v�hicules les familiers. Tous les clics de souris cibleront le v�hicule/familier.";
VUHDO_I18N_TT_282 = "Cochez cette case pour avoir un panneau suppl�mentaire pour les familiers";
VUHDO_I18N_TT_283 = "Cochez cette option pour avoir un panneau suppl�mentaire pour les joueurs en cible, mais gard� secret pour vous.";
VUHDO_I18N_TT_284 = "Cochez cette case pour avoir un panneau suppl�mentaire pour les Tanks";
VUHDO_I18N_TT_285 = "S�lectionnez cette option pour afficher toutes les unit�s RAID non group�es. Il s'agit d'un point de vue simple, mais clair.";
VUHDO_I18N_TT_286 = "S�lectionnez cette option pour afficher toutes les unit�s RAID regroup�es selon leur r�le: DPS m�l�e, m�l�e Tanks, DPS distance, Gu�risseurs.";
VUHDO_I18N_TT_287 = "S�lectionnez cette option pour afficher toutes les unit�s RAID regroup�es selon leur classe.";
VUHDO_I18N_TT_288 = "S�lectionnez cette option pour afficher toutes les unit�s RAID group�es par num�ro de groupe (1-8).";
VUHDO_I18N_TT_289 = "Cochez pour cacher l'affichage standard de blizzard du le cadre des familiers.";
VUHDO_I18N_TT_290 = "Cochez pour cacher l'affichage standard de blizzard du cadre des cibles.";
VUHDO_I18N_TT_291 = "Cochez pour commencer votre cast en rel�chant le bouton de la souris au lieu de la pression.";
VUHDO_I18N_TT_292 = "Cochez pour afficher l'info-bulles standard au lieu de VuhDo.";
VUHDO_I18N_TT_293 = "Cochez pour afficher un cadre autour de toutes les barres des joueurs.";
VUHDO_I18N_TT_294 = "Cochez pour afficher un cadre autour de votre cible actuellement s�lectionn�e.";
VUHDO_I18N_TT_295 = "Cochez pour mettre en �vidence l'unit� sur la souris.";
VUHDO_I18N_TT_296 = "Cochez pour mettre en �vidence les membres du groupe sur la souris.";
VUHDO_I18N_TT_297 = "S�lectionnez le mode intense groupe qui sera allum� sur la souris";
VUHDO_I18N_TT_298 = "Si vous cochez ce bouton, l'arrangement actuel s�lectionn� va automatiquement s'activer si vous �tes en SOLO.";
VUHDO_I18N_TT_299 = "Si vous cochez ce bouton, l'arrangement actuel s�lectionn� va automatiquement s'activer si vous �tes dans un groupe, maximum 5 joueurs.";
VUHDO_I18N_TT_300 = "Si vous cochez ce bouton, l'arrangement actuel s�lectionn� va automatiquement s'activer si vous �tes dans un raid maximum 10 joueurs.";
VUHDO_I18N_TT_301 = "Si vous cochez ce bouton, l'arrangement actuel s�lectionn� va automatiquement s'activer si vous �tes dans un raid maximum 25 joueurs.";
VUHDO_I18N_TT_302 = "Si vous cochez ce bouton, l'arrangement actuel s�lectionn� va automatiquement s'activer si vous �tes dans un raid de plus de 25 joueurs.";
VUHDO_I18N_TT_303 = "S�lectionnez cette option pour changer la couleur en fonction de la barre de vie des unit�s du vert au rouge.";
VUHDO_I18N_TT_304 = "S�lectionnez pour afficher les barres de couleurs dans la couleur fixe � droite.";
VUHDO_I18N_TT_305 = "Cochez pour afficher une barre avec un fond de couleur en fonction des classes.";
VUHDO_I18N_TT_306 = "Cliquez pour changer la couleur de votre barre en couleur de sant�.";
VUHDO_I18N_TT_307 = "Cochez pour avoir la croissance au lieu de faire r�tr�cir les barres si un joueur perd de la vie.";-------review
VUHDO_I18N_TT_308 = "Cochez pour avoir une barre de sant� � la verticale au lieu d'horizontale.";-------
VUHDO_I18N_TT_309 = "Cochez cette case pour afficher l'ic�ne dans la barre de sant� du raid.";
VUHDO_I18N_TT_310 = "Cochez cette option pour aligner les barres de sant� en horizontale plut�t que verticalement";
VUHDO_I18N_TT_311 = "S�lectionnez cette option pour toujours vous montrer au dessus de votre groupe (barre de sant� en premier).";
VUHDO_I18N_TT_312 = "D�finis l'ancrage des panneaux dans la partie sup�rieure centrale.";
VUHDO_I18N_TT_313 = "D�finis les panneaux d'ancrage au centre en bas.";
VUHDO_I18N_TT_314 = "D�finis les panneaux d'ancrage au centre gauche.";
VUHDO_I18N_TT_315 = "D�finis les panneaux d'ancrage au centre droit.";
VUHDO_I18N_TT_316 = "Trier le joueur dans un groupe par leur max. HP.";
VUHDO_I18N_TT_317 = "S�lection pour trier par groupe de classes";
VUHDO_I18N_TT_318 = "S�lectionnez la largeur de vos barres de Hot";
VUHDO_I18N_TT_319 = "Cocher pour activer les barres HoT";
VUHDO_I18N_TT_320 = "Choisir le Hot pour votre 3e emplacement.";
VUHDO_I18N_TT_321 = "Choisir le Hot pour votre 2e emplacement.";
VUHDO_I18N_TT_322 = "Choisir le Hot pour votre 1e emplacement.";
VUHDO_I18N_TT_323 = "Cochez pour r�tr�cir la barre de gauche � droite.";
VUHDO_I18N_TT_324 = "Cochez pour diminuer la barre verticale au lieu de l'horizontale";
VUHDO_I18N_TT_325 = "Cochez pour afficher HoT ic�nes en haut � gauche de la barre de sant�";
VUHDO_I18N_TT_326 = "Cochez pour afficher HoT ic�nes en bas � droite de la barre de sant�";
VUHDO_I18N_TT_327 = "Cochez pour afficher HoT ic�nes � gauche dessous la barre de sant�";
VUHDO_I18N_TT_328 = "Cochez pour afficher HoT ic�nes en bas � droite de la barre de sant�";
VUHDO_I18N_TT_329 = "Cochez pour afficher HoT ic�nes � gauche dessous la barre de sant�";
VUHDO_I18N_TT_330 = "Activez cette marque si possible d'utiliser \"Prompte gu�rison\" (Druides seulement) par un petit cercle rouge sur la barre.";
VUHDO_I18N_TT_331 = "Activer cette option pour afficher des Hot carr�s utiliser mats au lieu de la texture brillante";
VUHDO_I18N_TT_332 = "S�lectionnez un Hot pour votre 5e logement. Le logement num�ro 5 ne sera pas affich� quand les carr�s en couleur sont choisis au lieu des ic�nes";
VUHDO_I18N_TT_333 = "S�lectionnez un Hot pour votre 4e logement.";
VUHDO_I18N_TT_334 = "S�lectionnez un Hot pour votre 3e logement.";
VUHDO_I18N_TT_335 = "S�lectionnez un Hot pour votre 2e logement.";
VUHDO_I18N_TT_336 = "S�lectionnez un Hot pour votre 1e logement.";
VUHDO_I18N_TT_337 = "Configure la fa�on dont vous voulez que vos ic�nes Hot se ressemblent.";
VUHDO_I18N_TT_338 = "Configure la fa�on dont vous voulez que vos barres HoT se ressemblent.";
VUHDO_I18N_TT_339 = "D�placer pour changer l'�chelle de la totalit� des panneaux.";
VUHDO_I18N_TT_340 = "Activez cette option pour ne pas afficher le texte de la vie e, mille.";
VUHDO_I18N_TT_341 = "Cochez pour afficher nom du joueur sur les barres.";
VUHDO_I18N_TT_342 = "Cochez pour afficher nom de la classe du joueur sur les barres ";
VUHDO_I18N_TT_343 = "S�lectionnez le nombre max. de caract�res pour le nom du joueur.";
VUHDO_I18N_TT_344 = "S�lectionnez une police pour les noms des joueurs sur les barres de sant�.";
VUHDO_I18N_TT_345 = "Cochez cette option pour rester dans votre position actuelle au lieu de cliquer sur la barre de sant� et de l'unit�. Vous changerez automatiquement votre position";
VUHDO_I18N_TT_346 = "Cocher pour activer les infos-bulles des infos de sort";
VUHDO_I18N_TT_347 = "Cochez cette option pour faire des clics de souris \"partout\" � l'arri�re-plan du panneau pour permettre le ciblage, en mouvement. Si cette option est s�lectionn�e, vous ne serez pas en mesure de montrer qui est le chef de raid, etc. en utilisant le clique droit.";
VUHDO_I18N_TT_348 = "Cochez cette option pour verrouiller les panneaux des soins";
VUHDO_I18N_TT_349 = "Options pour les sorts sur les cibles hostiles";
VUHDO_I18N_TT_350 = "Cochez pour afficher le nombre de piles sur les ic�nes personnalis�es des debuff.";
VUHDO_I18N_TT_351 = "S�lectionnez pour l'ancrage des debuffs personnalis� en haut � gauche des barres de sant�.";
VUHDO_I18N_TT_352 = "S�lectionnez pour l'ancrage des debuffs personnalis� en haut � droite des barres de sant�.";
VUHDO_I18N_TT_353 = "S�lectionnez pour l'ancrage des debuffs personnalis� en bas � gauche des barres de sant�.";
VUHDO_I18N_TT_354 = "S�lectionnez pour l'ancrage des debuffs personnalis� en bas � droite des barres de sant�.";
VUHDO_I18N_TT_355 = "Ajustez la position des ic�nes personnalis�es des debuff dans le sens vertical.";
VUHDO_I18N_TT_356 = "Ajustez la position des ic�nes personnalis�es des debuff dans le sens horizontal";
VUHDO_I18N_TT_357 = "S�lectionnez cette option pour afficher le nom du familier/v�hicule dans le nom du texte.";
VUHDO_I18N_TT_358 = "S�lectionnez cette option en hors de combat fonctionnalit� de ciblage intelligent";
VUHDO_I18N_TT_359 = "S�lectionnez une touche de modification pour l'associer avec un cast vif et avec.";
VUHDO_I18N_TT_360 = "S�lectionnez cette option pour d�clencher automatiquement le rez combat sur les joueurs morts (druides seulement)";
VUHDO_I18N_TT_361 = "S�lectionnez pour afficher les barres cible � gauche des barres de sant�."
VUHDO_I18N_TT_362 = "S�lectionnez pour afficher les barres cible � droite des barres de sant�."
VUHDO_I18N_TT_363 = "S�lectionnez la sensibilit� du flash dommages. Une valeur plus grande signifie plus de clignotement (en bas/dommages).";
VUHDO_I18N_TT_364 = "Cochez pour cacher le texte de vie si la vie est au-dessus de d�clenchement.";
VUHDO_I18N_TT_365 = "Cochez pour appliquer le syst�me des Hot (Options=>Paneaux=>HoTs) quand la disposition des sorts change.";
VUHDO_I18N_TT_366 = "Cochez cette case pour viser l'unit� que vous gu�rissez en m�me temps";
VUHDO_I18N_TT_367 = "Ce menu vous permet de choisir, quel type de soin entrant sera d�tect�.";
VUHDO_I18N_TT_368 = "Choisissez le dernier point dans l'avenir dont vous voulez voir directement les cast � partir de.";
VUHDO_I18N_TT_369 = "Cochez pour afficher les nouveaux soins arrivant en direct des cast.";
VUHDO_I18N_TT_370 = "S�lectionnez le dernier point � l'avenir que vous voulez voir canalis� gu�rit de.";
VUHDO_I18N_TT_371 = "Cochez pour afficher des soins entrants provenant des soins canalis�s.";
VUHDO_I18N_TT_372 = "Select the latest point in the future you want to see HoTs from.";
VUHDO_I18N_TT_373 = "Cochez pour afficher les soins entrants des Hots.";
VUHDO_I18N_TT_374 = "Select the latest point in the future you want to see bombed heals from.";
VUHDO_I18N_TT_375 = "Cochez pour afficher incoming heals from bombed heals (atm: Life Bloom effect).";
VUHDO_I18N_TT_376 = "Select to align groups at the bottom of the panel (at the right, when \"horizontal\" is selected above).";
VUHDO_I18N_TT_377 = "S�lectionnez une texture pour les bordures du panneau.";
VUHDO_I18N_TT_378 = "S�lectionnez une taille pour le panneau des bordures de fronti�re.";
VUHDO_I18N_TT_379 = "Select an inset size for panel borders.";
VUHDO_I18N_TT_380 = "Cochez cette case pour ne pas vous voir dans un raid r�guli�rement.";
VUHDO_I18N_TT_381 = "Cocher pour appliquer la luminosit� de la barre de l'arri�re-plan � la barre de sant� au lieu de la barre de l'arri�re-plan, lorsque la couleur debuff est appliqu�. Utile si votre couleur de la barre d'arri�re-plan est plus clair que votre couleur de la barre de sant�.";
VUHDO_I18N_TT_382 = "Cochez pour afficher an outline around name and life text instead of a shadow.";
VUHDO_I18N_TT_383 = "Ignore le suivi des buff des familiers.";
VUHDO_I18N_TT_384 = "Sort du Raid trier par ordre donn� en \"d�placer!\". Cette s�lection ne fonctionnera que si l'arrangement est \"d�tacher\" est � �t� s�lectionn� ci-dessus.";
VUHDO_I18N_TT_385 = "Choisissez une couleur de la barre de sant� qui sera appliqu�e si cette am�lioration est manquante sur le joueur.";
VUHDO_I18N_TT_386 = "Permets de changer la couleur de la barre si cette am�lioration est manquante.";
VUHDO_I18N_TT_387 = "Augmenter la priorit� de cette am�lioration.";
VUHDO_I18N_TT_388 = "Diminuer la priorit� pour cette am�lioration.";
VUHDO_I18N_TT_389 = "Choisissez une couleur pour les HoT carr�s 6";
VUHDO_I18N_TT_390 = "V�rifiez pour inverser le tri.";
VUHDO_I18N_TT_391 = "Select a size for your raid icons.";
VUHDO_I18N_TT_392 = "Set component anchor to the top-left.";
VUHDO_I18N_TT_393 = "Set component anchor to the top-right.";
VUHDO_I18N_TT_394 = "Set component anchor to the bottom-left.";
VUHDO_I18N_TT_395 = "Set component anchor to the bottom-right.";
VUHDO_I18N_TT_396 = "Fixe les composants d'ancrage � gauche.";
VUHDO_I18N_TT_397 = "Fixe les composants d'ancrage en haut.";
VUHDO_I18N_TT_398 = "Fixe les composants d'ancrage en bas";
VUHDO_I18N_TT_399 = "Fixe les composants d'ancrage � droite.";
VUHDO_I18N_TT_400 = "Ajuste le placement des composants dans le sens horizontal.";
VUHDO_I18N_TT_401 = "Ajuste le placement des composants dans le sens vertical.";
VUHDO_I18N_TT_402 = "Setup raid icons and overheal texts.";
VUHDO_I18N_TT_403 = "Save current spell assignments.";
VUHDO_I18N_TT_404 = "Select a saved spell assignment.";
VUHDO_I18N_TT_405 = "Hide standard Blizzard focus frame.";
VUHDO_I18N_TT_406 = "The remaining stacks a HoT has will not be shown.";
VUHDO_I18N_TT_407 = "The remaining stacks a HoT has will be shown by a text counter.";
VUHDO_I18N_TT_408 = "The remaining stacks a HoT has will be shown by up to four (= four stacks or more) triangles around the HoT icon.";
VUHDO_I18N_TT_409 = "Cache les panneaux lorsque vous �tes en solo.";
VUHDO_I18N_TT_410 = "Hides panels when you are in a party of up to five";
VUHDO_I18N_TT_411 = "Organisation des couleurs pour les ic�nes cibles du raid";
VUHDO_I18N_TT_412 = "Cliquez ici pour copier ces param�tres par d�faut � tous les debuffs personnalis�s";
VUHDO_I18N_TT_413 = "Choisissez une couleur pour les debuff personnalis�s";
VUHDO_I18N_TT_414 = "S�lectionnez les ic�nes de raid � afficher";
VUHDO_I18N_TT_415 = "Choisissez une couleur pour le texte de l'overheal";
VUHDO_I18N_TT_416 = "Cochez pour afficher les ic�nes de raid par couleur de la barre/couleur du texte.";
VUHDO_I18N_TT_417 = "V�rifiez pour n'afficher que les ic�nes de raid par la couleur qui sont activ�es dans Panneaux=>Misc";
VUHDO_I18N_TT_418 = "Choisissez une couleur pour cette ic�ne de raid.";
VUHDO_I18N_TT_419 = "Mode Tank ne regarde que la situation de menace pour la d�tection d'aggro. les ennemis occasionnels qui font un ciblage sur les joueurs seront ignor�s";
VUHDO_I18N_TT_420 = "Option unique Pr�tre: Afficher l'ic�ne capacit� restante de boucliers. Ceci est exp�rimental.";
VUHDO_I18N_TT_421 = "Choisissez une couleur si l'unit� est en pleine sant�.";
VUHDO_I18N_TT_422 = "Choisissez une couleur si la vie de l'unit� est de taille moyenne.";
VUHDO_I18N_TT_423 = "Choisissez une couleur si la vie est faible."
VUHDO_I18N_TT_424 = "contr�le du groupe. heal de groupe, pour Cercle de soins ou Salve de gu�rison";
VUHDO_I18N_TT_425 = "R�glez la vitesse � laquelle les groupes seront rafra�chis. Peuvent avoir un impact sur les performances du syst�me";
VUHDO_I18N_TT_426 = "Choisissez une gamme dans laquelle deux unit�s sont consid�r�es comme un groupe";
VUHDO_I18N_TT_427 = "S�lectionnez un max. niveau de sant� au-dessus duquel est consid�r�e une unit� comme une cible qui m�rite un sort de soin";
VUHDO_I18N_TT_428 = "S�lectionnez un nombre minimum de personnes qui pour �tre une cible l�gitime de votre groupe de soins";
VUHDO_I18N_TT_429 = "S�lectionnez un nombre minimum de personnes qui pour �tre une bonne cible de votre groupe de soins.";
VUHDO_I18N_TT_430 = "S�lectionnez cette option si votre sort de soins de groupe part de vous (pas de la cible elle-m�me)";----review
VUHDO_I18N_TT_431 = "S�lectionnez cette option si votre sort de gu�rison de groupe part de la cible (pas de vous, par ex. Le cercle de Gu�rison)";----review
VUHDO_I18N_TT_432 = "S�lectionnez cette option si tous les membres du raid sont affect�s par le sort(Salve de gu�rison, Cercle de soins).";
VUHDO_I18N_TT_433 = "S�lectionnez si seulement les membres du raid dans le groupe de la cible b�n�ficieront de votre sort (Pri�re de soins)";
VUHDO_I18N_TT_434 = "S�lectionnez cette option pour tous les joueurs (sous le niveau en sant�) pour dessiner un cadre, qui sont dans le m�me groupe que le joueur sous la souris.";
VUHDO_I18N_TT_435 = "Cette option active l'affichage du nombre de personnes dans le p�le situ� dans l'ic�ne HoT";
VUHDO_I18N_TT_436 = "Affiche la recharge global sur la barre.";
VUHDO_I18N_TT_437 = "D�tecte le groupe directement autour de la cible.";
VUHDO_I18N_TT_438 = "D�tecte le groupe de la cible � proximit� avec un d�ficit de sant�."
VUHDO_I18N_TT_439 = "S�lectionnez le nombre maximal de fois o� votre cha�ne de soins passera � une autre cible.";
VUHDO_I18N_TT_440 = "Choisissez une couleur pour le nombre de joueurs dans un groupe est class� juste.";
VUHDO_I18N_TT_441 = "Choisissez une couleur pour le nombre de joueurs dans un groupe qui est jug�e bonne.";
VUHDO_I18N_TT_442 = "Choisissez une couleur pour passer la souris sur la bordure du groupe";
VUHDO_I18N_TT_443 = "Choisissez une couleur pour la barre de temps de recharge global."
VUHDO_I18N_TT_444 = "If you check this button the currently selected arrangement will automatically enabled if you are in a raid of up to 15 players.";
VUHDO_I18N_TT_445 = "Check to also load HoT setup with arrangements. Don't do this if the arrangement has been saved on another class!";
VUHDO_I18N_TT_446 = "Select debuffs from the ignore list.";
VUHDO_I18N_TT_447 = "Check to rate players assigned as tanks by dungeon finder tool as MTs and show them in MT list.";
VUHDO_I18N_TT_448 = "Setup cluster detection for your mass healing spells";
VUHDO_I18N_TT_449 = "Select a color for threat indicator bar when threat is high.";
VUHDO_I18N_TT_450 = "Select a color for threat indicator bar when threat is low.";
VUHDO_I18N_TT_451 = "Enable to auto-rebuff all missing buffs using the mouse-wheel on a buff swatch.";
VUHDO_I18N_TT_452 = "Select a saved bouquet or type in a new name.";
VUHDO_I18N_TT_453 = "Select a special trigger or enter the name of a buff or debuff.";
VUHDO_I18N_TT_454 = "Select a color for this event/trigger.";
VUHDO_I18N_TT_455 = "Select a default icon for this event. Select \"- none / Default -\" to show a buff's/debuff's own icon.";
VUHDO_I18N_TT_456 = "Setup the bars indicators like icons and status bars.";
VUHDO_I18N_TT_457 = "Setup Bouquets. Bouquets are groups of Buffs, Debuffs and other occasions in a priorization order. You can setup a bouquet e.g. as a HoT icon";
VUHDO_I18N_TT_458 = "Will display buffs in a more screen estate saving way.";
VUHDO_I18N_TT_459 = "Enter a new boquet name to create or copy current bouquet to.";
VUHDO_I18N_TT_460 = "Enter a debuff, buff or hot name.";
VUHDO_I18N_TT_461 = "Select a color to show if statusbar value is low";
VUHDO_I18N_TT_462 = "Select a color to show if statusbar value is medium";
VUHDO_I18N_TT_463 = "Select a color to show if statusbar value is high.";
VUHDO_I18N_TT_464 = "Select a bouquet to show via this indicator";
VUHDO_I18N_TT_465 = "Enables Clique compatibility mode. Requires to reload UI after changing.";
VUHDO_I18N_TT_466 = "Scans all units no matter how far away";
VUHDO_I18N_TT_467 = "Only scans units which are in the same map with you.";
VUHDO_I18N_TT_468 = "Only scans units in a range of max. 100 yards.";
VUHDO_I18N_TT_469 = "Only scans units in a range of max. 40 yards.";
VUHDO_I18N_TT_470 = "Scans talent trees for raid role estimation. May conflict with other addons.";
VUHDO_I18N_TT_471 = "Makes bars grow from right to left.";
VUHDO_I18N_TT_472 = "Indicates units taking severe damage by flashing the health bars.";
VUHDO_I18N_TT_473 = "Enable this to show HoT squares using the original icon.";
VUHDO_I18N_TT_474 = "Enable this to show HoT squares using a glossy texture.";
VUHDO_I18N_TT_475 = "Auto-Enable profile whenever switching to primary specc";
VUHDO_I18N_TT_476 = "Auto-Enable profile whenever switching to secondaray specc";
VUHDO_I18N_TT_477 = "In this Menu you can reset several aspects of your configuration to factory defaults";
VUHDO_I18N_TT_478 = "Click to return to where you came from.";
VUHDO_I18N_TT_479 = "Only if the spell in this edit box has no cooldown clusters will be shown. Leave empty to always show clusters.";
VUHDO_I18N_TT_480 = "Move to change options screen scale";
VUHDO_I18N_TT_481 = "Setup HoT counter / timer font";
VUHDO_I18N_TT_482 = "Adjust HoT text size";
VUHDO_I18N_TT_483 = "Select a bouquet for the selected panel to override general health bar bouquet.";
VUHDO_I18N_TT_484 = "Enables PallyPower compatible remote blessing and aura setup communications";
VUHDO_I18N_TT_485 = "Check this to not show your target in \"Private Tanks\" panel.";
-- 2.17
VUHDO_I18N_TT_486 = "Enable to lock a profile so it can't be overwritten accidentally.";
VUHDO_I18N_TT_487 = "Enable to auto-overwrite existing profile instead of showing overwrite / copy / abort confirmation dialog.";
VUHDO_I18N_TT_488 = "Enable to only show direction if player is dead.";
VUHDO_I18N_TT_489 = "Enable to show distance to oor raid members.";
VUHDO_I18N_TT_490 = "Enable to show direction of out of range players by an arrow.";
VUHDO_I18N_TT_491 = "Check to display custom debuff name for about 2 secs after applied.";
-- 2.18
VUHDO_I18N_TT_492 = "Uncheck to enable creation of macros for emergency raid roster restoration after logging back in mid fight after a d/c. 2 free toon individual macro slots needed."
VUHDO_I18N_TT_493 = "Select direction arrow size."
VUHDO_I18N_TT_494 = "Select destination profile";
VUHDO_I18N_TT_495 = "Exports all custom debuffs of current profile to all profiles of this toon.";
VUHDO_I18N_TT_496 = "Exports all custom debuffs of current profile to selected profile.";
VUHDO_I18N_TT_497 = "Exports all custom debuffs of current profile to ALL other profiles.";


VUHDO_I18N_APPLY_TO_ALL = "appliquez � tous";
VUHDO_I18N_TEST = "Test";
VUHDO_I18N_ADD = "Ajouter";
VUHDO_I18N_SELECT = "choisir";
VUHDO_I18N_NEW_COLOR = "Nouvelle couleur";
VUHDO_I18N_OLD_COLOR = "Ancienne couleur";
VUHDO_I18N_HIDE_CHARGES = "cachez les charges";
VUHDO_I18N_POWERS = "Pouvoirs";
VUHDO_I18N_HOTS = "HoTs";
VUHDO_I18N_HOT_COLORS = "Couleurs des Hots";
VUHDO_I18N_ICONS = "Ic�nes";
VUHDO_I18N_COUNTDOWN = "Compte � rebours";
VUHDO_I18N_APPLIANCES = "Appliances";
VUHDO_I18N_FADE_OUT = "Dispara�tre";
VUHDO_I18N_POWER_TYPES = "Types d'alimentation";
VUHDO_I18N_THREAT = "Menace";
VUHDO_I18N_MISC = "Misc";
VUHDO_I18N_SKINS = "Th�mes";
VUHDO_I18N_PANEL_WIZARD = "Panneau magique";
VUHDO_I18N_PRIV_TANKS = "Priv.Tanks";
VUHDO_I18N_CUSTOM_DE_BUFFS = "Personnalis� (De)buffs";
VUHDO_I18N_CHANGE_COLOR = "Couleur de Changement";
VUHDO_I18N_ICON = "Ic�ne";
VUHDO_I18N_ANIMATION = "Animation";
VUHDO_I18N_STORE = "Conserver";
VUHDO_I18N_SAVE = "Sauver";
VUHDO_I18N_DELETE = "effacer";
VUHDO_I18N_APPLY = "Appliquer";
VUHDO_I18N_ADDITIONAL_PANELS = "Panneaux additionnels";
VUHDO_I18N_UNSORT = "Unsort";
VUHDO_I18N_ROLES = "Roles";
VUHDO_I18N_CLASSES = "Classes";
VUHDO_I18N_GROUPS = "Groupes";
VUHDO_I18N_MAIN_PANEL = "Panneau principal";
VUHDO_I18N_PARTY = "Groupe";
VUHDO_I18N_PET = "Familier";
VUHDO_I18N_TARGET = "Cible";
VUHDO_I18N_HIDE_STANDARD = "Masquer le standard";
VUHDO_I18N_PLAYER_TARGET = "Le joueur cibl�";
VUHDO_I18N_SINGLE = "Seul";
VUHDO_I18N_MULTI = "Multi";
VUHDO_I18N_HOT_TARGETING = "Scanner des Hot";
VUHDO_I18N_COLORS_FONTS = "(Couleurs/Fonts)";
VUHDO_I18N_ARRANGEMENT = "Arrangement";
VUHDO_I18N_SELECT_AN_ARRANGEMENT = "S�lection d'un arrangement";
VUHDO_I18N_OR_ENTER_ARRANGEMENT_NAME = "... o� entrer l'arrangement du nom";
VUHDO_I18N_GROUPS_SIZES = "(Groupes/Tailles)";
VUHDO_I18N_SYMBOL = "Symbole";
VUHDO_I18N_TOP_BAR = "Top Bar";
VUHDO_I18N_MONITOR_THREAT = "Surveiller la menace";
VUHDO_I18N_USE_ADD_BAR = "Utilisez barre suppl�mentaire";
VUHDO_I18N_LINE = "ligne";
VUHDO_I18N_LEFT = "Gauche";
VUHDO_I18N_RIGHT = "Droite";
VUHDO_I18N_CHECK_FOR_AGGRO = "Cochez l'Aggro";
VUHDO_I18N_CURR = "curr.";
VUHDO_I18N_BAR_COLOR = "Couleur barre";
VUHDO_I18N_PLUS_BG = "+Fond";
VUHDO_I18N_INV_GROWTH = "Inverser";
VUHDO_I18N_VERTICAL = "Verticale";
VUHDO_I18N_RAID_ICON = "Icon de raid";
VUHDO_I18N_YOU_FIRST = "You first";
VUHDO_I18N_IICONSI = "[Ic�nes]";
VUHDO_I18N_ISQUARESI = "[Carr�s]";
VUHDO_I18N_HOT_ORDER = "Ordre des Hot";
VUHDO_I18N_SLOT_5 = "Slot 5";
VUHDO_I18N_SLOT_4 = "Slot 4";
VUHDO_I18N_SLOT_3 = "Slot 3";
VUHDO_I18N_SLOT_2 = "Slot 2";
VUHDO_I18N_SLOT_1 = "Slot 1 (in-most)";
VUHDO_I18N_TEXT_POSITION = "Position du texte";
VUHDO_I18N_FLAGS = "Flags";
VUHDO_I18N_SHOW_TEXT = "Afficher le texte";
VUHDO_I18N_KEYS = "cl�";
VUHDO_I18N_SPEC_2 = "Spec 2";
VUHDO_I18N_SPEC_1 = "Spec 1";
VUHDO_I18N_MANAGE_KEYS = "Manage Key Layouts";
VUHDO_I18N_INSTANT_2 = "Instant 2";
VUHDO_I18N_INSTANT_1 = "Instant 1";
VUHDO_I18N_TRINKET_2 = "Trinket 2";
VUHDO_I18N_TRINKET_1 = "Trinket 1";
VUHDO_I18N_TRIGGER_WHAT = "Trigger what...";
VUHDO_I18N_ALSO_OUT_FIGHT = "also out fight";
VUHDO_I18N_ALSO_HOTS = "also HoTs";
VUHDO_I18N_KEEP_STANCE = "keep Stance";
VUHDO_I18N_AUTO_TRIGGER = "Auto trigger";
VUHDO_I18N_SPELL_ADVICE = "Utilisez le programme d'installation standard de WoW raccourcis clavier pour assigner des sorts ci-dessous pour les touches. (Allez � l'en-t�te de �VuhDo�.)";
VUHDO_I18N_SAVE_AS = "Enregistrer sous...";
VUHDO_I18N_MOVE = "D�placer!";
VUHDO_I18N_SPELLS = "Spells";
VUHDO_I18N_PANELS = "Panneaux";
VUHDO_I18N_BUFFS = "Buffs";
VUHDO_I18N_ICON_SCALE = "Icon Scale";
VUHDO_I18N_THICKNESS = "Thickness";
VUHDO_I18N_WARNING_COLOR_AT = "Warning Color at";
VUHDO_I18N_THREAT_BAR_HEIGHT = "Threat Bar Height";
VUHDO_I18N_REFRESH_AGGRO = "Actualiser l'Aggro";
VUHDO_I18N_PANEL_SCALE = "�chelle des panneaux";
VUHDO_I18N_MAX_CHARS = "Max.caract�re (0=All)";

-- #+v1.178
VUHDO_I18N_HOSTILE = "Hostile";
VUHDO_I18N_HOSTILE_TITLE = "[HOSTILE]";
VUHDO_I18N_HOSTILE_ADVICE_1 = "Entrez le nom du sort ou la cible/focus/assist"
VUHDO_I18N_HOSTILE_ADVICE_2 = "NE PAS entrer des noms de macro/autres constante!!!"
VUHDO_I18N_HOSTILE_ADVICE_3 = "Bijoux/Instants ne se d�clenchent pas en automatique!!!"

-- Slider
VUHDO_I18N_BACKG_BRIGHTNESS = "fond.Luminosit�";
VUHDO_I18N_WARN_PREC_AT = "Alerter / la pr�cision de";
VUHDO_I18N_MAX_NO_DE_BUFFS = "Max. # (de)buffs";
VUHDO_I18N_DEBUFF_SOUND = "Debuff Son";
VUHDO_I18N_BRIGHTNESS = "Luminosit�";
VUHDO_I18N_RAID_ICON_SCALE = "�chelle des ic�nes de raid";
VUHDO_I18N_NAME_TEXT_SIZE = "Taille du texte:nom";
VUHDO_I18N_LIFE_TEXT_SIZE = "Taille du texte:Vie";
-- Color swatches
VUHDO_I18N_BUFF_OKAY = "Buff OKAY";
VUHDO_I18N_BUFF_LOW = "Buff FAIBLE";
VUHDO_I18N_BUFF_MISSING = "Buff disparut";
VUHDO_I18N_OUT_OF_RANGE = "Hors de port�e";
VUHDO_I18N_COOLDOWN = "Recharge";
VUHDO_I18N_EMPTY_GROUP = "Groupe vide";
VUHDO_I18N_PANEL_BACKGROUND = "Fond des panneaux";
VUHDO_I18N_SWATCH_BORDER = "Swatch Bordure";
VUHDO_I18N_PANEL_BORDER = "Bordure des panneaux";
VUHDO_I18N_2ND_CHARGE = "2nd charge";
VUHDO_I18N_3RD_CHARGE = "3rd charge";
VUHDO_I18N_4TH_CHARGE = "4th charge";
VUHDO_I18N_BAR_1 = "Bar 1";
VUHDO_I18N_BAR_2 = "Bar 2";
VUHDO_I18N_BAR_3 = "Bar 3";
VUHDO_I18N_SQUARE_1 = "Carr� 1";
VUHDO_I18N_SQUARE_2 = "Carr� 2";
VUHDO_I18N_SQUARE_3 = "Carr� 3";
VUHDO_I18N_SQUARE_4 = "Carr� 4";
VUHDO_I18N_SQUARE_5 = "Carr� 5";
VUHDO_I18N_EMERGENCY = "Urgence";
VUHDO_I18N_NO_EMEGENCY = "Pas urgent";
VUHDO_I18N_IRRELEVANT = "Irrelevant";
VUHDO_I18N_INCOMING = "Incoming";
VUHDO_I18N_MANA = "Mana";
VUHDO_I18N_RAGE = "Rage";
VUHDO_I18N_ENERGY = "�nergie";
VUHDO_I18N_RUNES = "Runes";
VUHDO_I18N_DEAD = "Mort";
VUHDO_I18N_OFFLINE = "Hors-ligne";
VUHDO_I18N_CHARMED = "Charme";
VUHDO_I18N_BAR_FRAME = "Barre Frame";
VUHDO_I18N_POISON = "Poison";
VUHDO_I18N_DISEASE = "Maladie";
VUHDO_I18N_CURSE = "Mal�diction";
VUHDO_I18N_MAGIC = "Magique";
VUHDO_I18N_HEADER = "En-t�te";
VUHDO_I18N_TARGET_NAME = "Nom de la cible";
VUHDO_I18N_BORDER = "Bordure";
VUHDO_I18N_AUTO_ENABLE = "Auto activer si � x joueurs:";

VUHDO_I18N_ANOUNCE_RESURRECTION = "annoncent la r�surrection";
VUHDO_I18N_FILTER = "Filtre";
VUHDO_I18N_FOCUS = "Focus";
VUHDO_I18N_BUFF = "Buff";
VUHDO_I18N_OTHERS = "autres";
VUHDO_I18N_LIFE_TEXT = "Texte de la vie";
VUHDO_I18N_EXTRA_TEXT = "Texte suppl�mentaire";
VUHDO_I18N_FRAME = "Cadre";
VUHDO_I18N_1 = " 1";
VUHDO_I18N_2 = " 2";
VUHDO_I18N_3 = " 3";
VUHDO_I18N_4 = " 4";
VUHDO_I18N_5 = " 5";
VUHDO_I18N_6 = " 6";
VUHDO_I18N_7 = " 7";
VUHDO_I18N_8 = " 8";
VUHDO_I18N_10 = " 10";
VUHDO_I18N_25 = " 25";
VUHDO_I18N_40 = " 40";
VUHDO_I18N_NUM_TRIANGLES = "# / Triangle";
VUHDO_I18N_DEBUFF_DEFAULTS = "(De)Buff Par d�faut";
VUHDO_I18N_ITEXTUREI = "[Texture]";
VUHDO_I18N_BAR = "Barre";
VUHDO_I18N_HOTS_2 = "HoTs #2";
VUHDO_I18N_PET_CLASS = "Pet class";
VUHDO_I18N_CLASS_COLORS = "Couleur des classes";
VUHDO_I18N_HOT_CHARGES = "HoT charges";
VUHDO_I18N_TEXT_COLOR = "Couleur du texte";
VUHDO_I18N_BACK_COLOR = "Retour couleur";
VUHDO_I18N_HOT_BARS = "HoT Bars";
VUHDO_I18N_OUTLINE = "Contour";
VUHDO_I18N_SHADOW = "Ombre";
VUHDO_I18N_WARNING = "Alerte";
VUHDO_I18N_MISC_TEXT = "Misc. Texte";
VUHDO_I18N_EXPIRY_WARNING = "Avertissement d'expiration";
VUHDO_I18N_COUNTDOWN_OFF = "Compte � rebours: Off";
VUHDO_I18N_SECS = "secs";
VUHDO_I18N_SECS_10 = "sec/10";
VUHDO_I18N_FULL_DURATION = "dur�e totale";
VUHDO_I18N_TOOLS = "Outils";
VUHDO_I18N_TIMER = "Compteur";
VUHDO_I18N_DEBUFF_OPTIONS = "(De)Buff Options";
VUHDO_I18N_SOUND = "Son";
VUHDO_I18N_STORE_DELETE = "Store / Delete";
VUHDO_I18N_DEBUFF_SOUND = "Debuff Sound";
VUHDO_I18N_MOUSE_UP = "Mouse Up";
VUHDO_I18N_REACTION_ON = "Reaction on...";
VUHDO_I18N_TOOLTIP_TYPE = "type d'info-bulles";
VUHDO_I18N_BAR_BORDER = "Barre Bordure";
VUHDO_I18N_UNIT = "Unit�";
VUHDO_I18N_MOUSE_OVER_HIGH = "Votre souris en �vidence";
VUHDO_I18N_FLOAT = "Float";
VUHDO_I18N_SOLIDD = "Solid";
VUHDO_I18N_HORIZONTAL = "horizontal";
VUHDO_I18N_SLOT_1_2 = "Slot 1";
VUHDO_I18N_INVERT_X = "Inverser X";
VUHDO_I18N_INVERT_Y = "Inverser Y";
VUHDO_I18N_FLAT_TEXTURE = "Texture mat";
VUHDO_I18N_HOT_ICONS = "HoT Ic�nes";
VUHDO_I18N_TARGET_OF_TARGET = "Cible de la cible";
VUHDO_I18N_VERBOSE = "Verbose";
VUHDO_I18N_1_DOT = "1.";
VUHDO_I18N_2_DOT = "2.";
VUHDO_I18N_3_DOT = "3.";
VUHDO_I18N_4_DOT = "4.";
VUHDO_I18N_5_DOT = "5.";
VUHDO_I18N_6_DOT = "6.";
VUHDO_I18N_7_DOT = "7.";
VUHDO_I18N_8_DOT = "8.";
VUHDO_I18N_9_DOT = "9.";
VUHDO_I18N_10_DOT = "10.";
VUHDO_I18N_11_DOT = "11.";
VUHDO_I18N_12_DOT = "12.";
VUHDO_I18N_13_DOT = "13.";
VUHDO_I18N_14_DOT = "14.";
VUHDO_I18N_15_DOT = "15.";
VUHDO_I18N_16_DOT = "16.";
VUHDO_I18N_KEY_BINDINGS = "Key Bindings";
VUHDO_I18N_MOUSE_WHEEL = "roulette de la souris";
VUHDO_I18N_TOOLTIP_INFO = "Spell Info";

-- #+1.197
VUHDO_I18N_EDGE_SIZE = "Taille rebord";
VUHDO_I18N_EDGE_INSETS = "Rebord ins�rer";

-- #+1.203
VUHDO_I18N_SWAP_WHEN_DEBUFFED = "Swap Debuff";

-- #+1.204
VUHDO_I18N_IGNORE_PETS = "Ignore Pets";
VUHDO_I18N_PANEL_MODEL = "Panneau de mod�le";

-- #+1.207
VUHDO_I18N_OVERHEAL_TEXT = "Overheal Text";

-- #+1.210
VUHDO_I18N_NO_STACKS = "Piles: Off";
VUHDO_I18N_NUMBER_STACKS = "Texte";
VUHDO_I18N_TRIANGLE_STACKS = "Triangles";
VUHDO_I18N_HIDE_PANELS = "Masquer Panneaux";
VUHDO_I18N_SOLO = "Solo";

VUHDO_I18N_CLICK_THROUGH = "+ pas de clics";
VUHDO_I18N_IHEALTH_BARI = "[Barre sant� ]";
VUHDO_I18N_SLOT_6 = "Slot 6 (out-most)";
VUHDO_I18N_SQUARE_6 = "Carr� 6";
VUHDO_I18N_GLOSSY = "Brillant";
VUHDO_I18N_DAMAGE_FLASH = "Dmg.Flash";
VUHDO_I18N_SENSIVITY = "Sensibilit�";
VUHDO_I18N_HIDE_IRRELEVANT = "Hide irrel.";
VUHDO_I18N_LOAD_HOTS = "Chargement HoTs";
VUHDO_I18N_CASTED = "Direct";
VUHDO_I18N_CHANNELLED = "Canalis�s";
VUHDO_I18N_BOMBED = "Bombard�";
VUHDO_I18N_EVENT_HORIZON = "Horizon d'�v�nement";
VUHDO_I18N_ALGINMENT = "Alignement";
VUHDO_I18N_BOTTOM = "Bas";
VUHDO_I18N_PET_OWNERS = "Propri�taire P�t";
VUHDO_I18N_BATTLE_REZ = "Rez combat";


-- #+1.232
VUHDO_I18N_DEBUFF_LIST = "(De)Buff Liste";
VUHDO_I18N_DEBUFF_EDIT_BOX = "Entez un nouveau Buff ou un nom de Debuff";

-- #+1.233
VUHDO_I18N_BUTTON_6 = "Button 6";
VUHDO_I18N_BUTTON_7 = "Button 7";
VUHDO_I18N_BUTTON_8 = "Button 8";
VUHDO_I18N_BUTTON_9 = "Button 9";
VUHDO_I18N_BUTTON_10 = "Button 10";
VUHDO_I18N_BUTTON_11 = "Button 11";
VUHDO_I18N_BUTTON_12 = "Button 12";
VUHDO_I18N_BUTTON_13 = "Button 13";
VUHDO_I18N_BUTTON_14 = "Button 14";
VUHDO_I18N_BUTTON_15 = "Button 15";
VUHDO_I18N_BUTTON_16 = "Button 16";
VUHDO_I18N_TANK_MODE = "Tank Mode";

-- #+1.237
VUHDO_I18N_CLUSTER_SCANNER = "Scanner du groupe";
VUHDO_I18N_CLUSTER_PARAMS = "Parametres de groupe";
VUHDO_I18N_FAIR_THRESHOLD = "Fair threshold";
VUHDO_I18N_GOOD_THRESHOLD = "Good threshold";
VUHDO_I18N_SOURCE_SPELL = "Spell Source";
VUHDO_I18N_SOURCE_MINE = "joueur";
VUHDO_I18N_SOURCE_ALL = "cible";
VUHDO_I18N_DEST_SPELL = "Spell Destination";
VUHDO_I18N_DEST_RAID = "Raid";
VUHDO_I18N_DEST_PARTY = "Groupe";
VUHDO_I18N_CLUSTERS = "Groupes";
VUHDO_I18N_LOW = "Faible";
VUHDO_I18N_FAIR = "Passable";
VUHDO_I18N_GOOD = "Good";
VUHDO_I18N_HEALTH_LEVEL = "Niveau de Sant� <";
VUHDO_I18N_CLUSTER_FINDER = "Groupe trouv�";
VUHDO_I18N_OTHER_HOTS = "autres joueurs avec des HoTs";
VUHDO_I18N_EMPTY_HOTS = "vide";
VUHDO_I18N_MOUSE_HOVER = "Passez la souris";
VUHDO_I18N_COUNTER = "Compteur";
VUHDO_I18N_GLOBAL_COOLDOWN = "Recharge globale";
VUHDO_I18N_GCD = "GCD";

-- #+1.238
VUHDO_I18N_DISPLAY_OPTIONS = "Options d'affichage";
VUHDO_I18N_RADIAL = "Radial";
VUHDO_I18N_CHAINED = "Encha�n�";
VUHDO_I18N_CHAINED_MAX_JUMP = "Chained max jumps";
VUHDO_I18N_TIMES = " times";
VUHDO_I18N_SOURCE_DESTINATION = "Source/Destination";
VUHDO_I18N_HIGH = "�lev�";

-- #+1.251
VUHDO_I18N_15 = " 15";
VUHDO_I18N_LOAD_HOTS = "Load HoTs";
VUHDO_I18N_IGNORE_LIST = "Ignore List";
VUHDO_I18N_FIVE_MAN_MTS = "5 man MTs";
VUHDO_I18N_FILTER_ONLY = "Filter only";
VUHDO_I18N_LIFE_COLORS = "Life colors";
VUHDO_I18N_SMART_WHEEL = "Smart Wheel";
VUHDO_I18N_PASTE = "Paste";
VUHDO_I18N_COPY = "Copy";

-- #+1.252
VUHDO_I18N_BOUQUETS = "Bouquets";
VUHDO_I18N_SELECT_OR_ENTER_BOUQUET = "Select a Bouquet ...";
VUHDO_I18N_NEW = "New";
VUHDO_I18N_BOUQUET_DETAILS = "Bouquet Details";
VUHDO_I18N_HIGHEST_PRIO = "Highest Priority";
VUHDO_I18N_LOWEST_PRIO = "Lowest Priority";
VUHDO_I18N_ITEM_DETAILS = "Item Details";
VUHDO_I18N_ENTER_DE_BUFF_OR_SPECIAL = "Select special event ...";
VUHDO_I18N_ITEM = "Item";
VUHDO_I18N_SELECT_DEFAULT_ICON = "Select default icon";
VUHDO_I18N_MINE = "Mine";
VUHDO_I18N_GRADIENT = "Gradient";
VUHDO_I18N_INDICATORS = "Indicators";

VUHDO_I18N_COPIED_BOUQUET = "Copied bouquet ";
VUHDO_I18N_BOUQUET_ALREADY_EXISTS = ": Bouquet already exists. Type new name first.";
VUHDO_I18N_CREATED_NEW_BOUQUET = "Created new Bouquet: ";
VUHDO_I18N_DELETED_BOUQUET = "Deleted bouquet: ";
VUHDO_I18N_BOUQUET_NOT_FOUND = ": No such bouquet found.";
VUHDO_I18N_SELECT_STORE_BOUQUET_FIRST = "Select bouquet first";
VUHDO_I18N_SELECT_ITEM_FIRST = "Select an item to remove first.";
VUHDO_I18N_SELECT_A_PROFILE = "Select a profile";
VUHDO_I18N_PROFILES = "Profiles";
VUHDO_I18N_EDIT_BUTTON = "Edit...";
VUHDO_I18N_MORE_BUTTON = "More...";
VUHDO_I18N_DONE_BUTTON = "Done";
VUHDO_I18N_BASIC = "Basic";
VUHDO_I18N_ADVANCED = "Advanced";
VUHDO_I18N_EXPERT = "Expert";
VUHDO_I18N_COMPACT = "Compact";

VUHDO_I18N_REALLY_DELETE_PROFILE = "Really delete profile";
VUHDO_I18N_MUST_ENTER_SELECT_PROFILE = "You must enter/select a name first.";
VUHDO_I18N_DELETED_PROFILE = "Successfully deleted profile";
VUHDO_I18N_TURN_AXIS = "Turn Axis";
VUHDO_I18N_DO_NOT_EDIT_BOUQUET = "Generic: DO NOT CHANGE DETAILS !";
VUHDO_I18N_OR_NEW_BOUQUET_NAME = "... or new Bouquet name";
VUHDO_I18N_OR_ENTER_DEBUFF_HOT = "... or enter Buff / Debuff / HoT name";
VUHDO_I18N_TALENT_TREES = "Talent trees";
VUHDO_I18N_SCAN = "Scan";
VUHDO_I18N_INFINITE = "Infinite";
VUHDO_I18N_SAME_ZONE = "Same Zone";
VUHDO_I18N_100_YARDS = "100 yards";
VUHDO_I18N_40_YARDS = "40 yards";
VUHDO_I18N_LIFE_TEXT = "Life Text";
VUHDO_I18N_BACK = "Back";
VUHDO_I18N_CLIQUE_COMPAT_MODE = "Clique support";
VUHDO_I18N_RESET = "Reset";
VUHDO_I18N_DEBUFF_COLORS = "Debuff Colors";
VUHDO_I18N_BUFFS_HOTS = "Buffs/HoTs";
VUHDO_I18N_BUFF_WATCH = "Buff Watch";
VUHDO_I18N_CUSTOM_DEBUFFS = "Custom Debuffs";
VUHDO_I18N_DEFAULT_BOUQUETS = "Default Bouquets";
VUHDO_I18N_EVERYTHING = "Everything";
VUHDO_I18N_LANGUAGE = "Language";
VUHDO_I18N_PANEL_POSITIONS = "Panel Positions";
VUHDO_I18N_PER_PANEL_SETTINGS = "per Panel Settings";
VUHDO_I18N_MINUTE = "min.";
VUHDO_I18N_MSEC = "msec";
VUHDO_I18N_PEOPLE = " people";
VUHDO_I18N_RESET_CLASS_COLORS = "This will reset your custom\nCLASS COLOR settings. Proceed?" ;
VUHDO_I18N_RESET_DEBUFF_COLORS = "This will reset your custom\nDEBUFF COLOR settings. Proceed?";
VUHDO_I18N_RESET_RAID_ICON_COLORS = "This will reset your custom\nRAID TARGET COLOR settings. Proceed?";
VUHDO_I18N_RESET_BUFF_WATCH = "This will reset all your\nBUFF WATCH settings. Proceed?";
VUHDO_I18N_RESET_CUSTOM_DEBUFFS = "This will reset all your\nCUSTOM DEBUFFs + settings. Proceed?";
VUHDO_I18N_RESET_DEFAULT_BOUQUETS = "This will reset all \nDEFAULT (not: custom) BOUQUETS. Proceed?";
VUHDO_I18N_RESET_INDICATORS = "This will reset your custom\nINDICATOR CONFIG. Proceed?";
VUHDO_I18N_RESET_ALL = "!!!WARNING: This will RESET THE WHOLE\nADDON to factory defaults!!! Proceed?" ;
VUHDO_I18N_RESET_LANGUAGE = "This will reset all settings after client\nlanguage change (Heavy STUFF!!!). Proceed?";
VUHDO_I18N_RESET_PANEL_POSITIONS = "This will reset your\npanel positions. Proceed?";
VUHDO_I18N_RESET_PER_PANEL_SETTINGS = "This will reset your\nper-panel setup. Proceed?";

-- 2.17
VUHDO_I18N_LOCK = "Lock";
VUHDO_I18N_QUIET_MODE = "Quiet Mode";
VUHDO_I18N_SETTINGS = "Settings";
VUHDO_I18N_ACTIVATE_DUE_GRP_SIZE = "Activate due to group size";
VUHDO_I18N_CUSTOM_HEALTH_BAR_BOUQUET = "Custom Health Bar Bouquet";
VUHDO_I18N_CUSTOM_SETTINGS = "Custom settings";
VUHDO_I18N_DISTANCE = "Distance";
VUHDO_I18N_DEAD_ONLY = "dead only";
VUHDO_I18N_DIRECTION = "Direction";
VUHDO_I18N_IF_OOR_SHOW = "If unit is out of range show...";
VUHDO_I18N_DEBUFF_NAME = "Debuff Name";
-- 2.18
VUHDO_I18N_DISABLE = "Disable";
VUHDO_I18N_DC_RESTORE = "D/C Restore";
VUHDO_I18N_EXPORT_CUSTOM_DEBUFFS = "Export Custom Debuffs";
VUHDO_I18N_EXPORT_TO_PROFILE = "Export to profile:";
VUHDO_I18N_THIS_TOONS = "This Toon's";
VUHDO_I18N_SELECTED = "Selected";
VUHDO_I18N_ALL = "All";
VUHDO_I18N_REPLACE = "Replace";
