if (GetLocale() ~= "zhTW") then
	return;
end


-- New Options
-- @EXACT = false
VUHDO_I18N_SCANNERS = "監視器";
VUHDO_I18N_RESURRECT_SHORT = "監視器";
VUHDO_I18N_GENERAL = "基本設置";
VUHDO_I18N_CONFIG = "設置";
VUHDO_I18N_REBUFF = "補BUFF";
VUHDO_I18N_FORMAT = "格式";
VUHDO_I18N_BUFF_NAMES = "增益名稱";
VUHDO_I18N_EMPTY_GROUPS = "無隊員";
VUHDO_I18N_STATES = "狀態";
VUHDO_I18N_CD_FLASHING = "冷卻閃爍";
VUHDO_I18N_TIMERS = "計時器";
VUHDO_I18N_WHATEVER_FIRST = "...或者... (優先執行第一條)";
VUHDO_I18N_SMART_DOTS = "智能...";
VUHDO_I18N_GROUP_BUFFS = "團隊增益";
VUHDO_I18N_MODES = "模式";
VUHDO_I18N_EMERGENCY_MODE = "緊急模式";
VUHDO_I18N_NORMAL_MODE = "普通模式";
VUHDO_I18N_DETECT = "偵測";
VUHDO_I18N_RANGE = "範圍";
VUHDO_I18N_ADD_NEW_PANEL = "添加面板";
VUHDO_I18N_HOLD_TO_TEST = "按住測試";
VUHDO_I18N_OWN_HOTS = "自身HOTS";
VUHDO_I18N_BAR_TEXTURE = "血條材質";
VUHDO_I18N_OTHER_POWERS = "其他";
VUHDO_I18N_MANA_BARS = "法力條";
VUHDO_I18N_LOSE = "損失";
VUHDO_I18N_ORDERING = "排序";
VUHDO_I18N_HIDE_EMPTY = "隱藏空面板";
VUHDO_I18N_ANCHOR = "錨點";
VUHDO_I18N_UNIT_ID = "目標ID";
VUHDO_I18N_HEADER_TEXT = "標題材質";
VUHDO_I18N_TOOLTIPS = "提示";
VUHDO_I18N_SIZING = "縮放";
VUHDO_I18N_BUTTON_SIZE = "按鍵縮放";
VUHDO_I18N_TARGET_NAME = "目標名字";
VUHDO_I18N_PERCENT = "百分比";
VUHDO_I18N_MISSING = "損失";
VUHDO_I18N_REMAINING = "剩餘";
VUHDO_I18N_HITPOINTS = "血量";
VUHDO_I18N_BAR_TEXT = "血條文字";
VUHDO_I18N_MAX_SWATCHES_PER_LINE = "每行最多";
VUHDO_I18N_MAX_BUFFS_PER_ROW = "每行最多顯示增益";
VUHDO_I18N_REFRESH_RATE = "刷新率";
VUHDO_I18N_INDICATE_REBUFF_BELOW = "低於提示REBUFF";
VUHDO_I18N_IF_AT_LEAST = "...至少";
VUHDO_I18N_PLAYERS_LOW = "名隊友.";
VUHDO_I18N_SIZE = "大小";
VUHDO_I18N_TEXTURE_NUM = "材質#";
VUHDO_I18N_TEXT_SIZE = "文字大小";
VUHDO_I18N_X_SPACING = "X-間距";
VUHDO_I18N_Y_SPACING = "Y-間距";
VUHDO_I18N_X_GAP = "X-間隙";
VUHDO_I18N_Y_GAP = "Y-間隙";

-- General Labels
-- @EXACT = false
VUHDO_I18N_CANCEL = "取消";
VUHDO_I18N_SHOW = "顯示";
VUHDO_I18N_BARS = "條"
VUHDO_I18N_COLOR = "顏色";
VUHDO_I18N_COLORS = "顏色";
VUHDO_I18N_GENERAL_SHORT = "基本設置";
VUHDO_I18N_CUSTOM = "自定義";
VUHDO_I18N_MOUSE = "鼠標";
VUHDO_I18N_STANDARD = "標準";
VUHDO_I18N_POSITION = "位置";
VUHDO_I18N_SCALE = "縮放";
VUHDO_I18N_ENABLE = "開啟";
VUHDO_I18N_BACKGROUND = "背景";
VUHDO_I18N_GROUPED = "數值";
VUHDO_I18N_SORT_BY = "按...排列";
VUHDO_I18N_NAME = "名字";
VUHDO_I18N_MAX_HP = "最大血量";
VUHDO_I18N_MAX_COLUMNS = "最大列數";
VUHDO_I18N_MAX_ROWS = "最大行數";
VUHDO_I18N_CLEAR_PANELS_CONFIRM = "清除面板設定!\nYA'確定?";
VUHDO_I18N_BUFF_NAME = "增益名稱";
VUHDO_I18N_BUFF_ON_PLAYER = "玩家名字:";
VUHDO_I18N_ALWAYS = "總是";
VUHDO_I18N_NEVER = "從不";
VUHDO_I18N_BUFF_PANEL_BG = "面板";



-- VuhDoOptionsGeneral.lua
-- @EXACT = false
VUHDO_I18N_CLEANSE = "驅散";
VUHDO_I18N_RESURRECT = "復活";
VUHDO_I18N_SMART_CAST_OO_COMBAT = "智能施法";
VUHDO_I18N_IGNORE_IRRELEVANT = "將被忽略的減益法術";
VUHDO_I18N_BY_CLASS = "職業";
VUHDO_I18N_MOVEMENT_IMPAIRING = "減速";
VUHDO_I18N_BY_DURATION = "短週期";
VUHDO_I18N_BY_NON_HARMFUL = "無害的";
VUHDO_I18N_SHOW_ALL = "Show All";
VUHDO_I18N_ESTIMATE = "標準距離";
VUHOD_I18N_BY_SPELL = "指定技能";
VUHDO_I18N_SHOW_INC = "治療輸入";
VUHDO_I18N_SHOW_OWN_HEAL = "自己";
VUHDO_I18N_SHOW_OVERHEAL = "過量治療";
VUHDO_I18N_OPERATION_MODE = "顯示方式";
VUHDO_I18N_MAX_EMERGENCIES = "最大高亮";
VUHDO_I18N_RELVEVANCE = "高於則不高亮";
VUHDO_I18N_NEUTRAL_HEALBOT = "正常顯示";
VUHDO_I18N_EMERGENCY_PERCENT = "血量低於設定數值";
VUHDO_I18N_EMERGENCY_MOST_MISSING = "最多損失";
VUHDO_I18N_EMERGENCY_LEAST_LEFT = "最少剩餘血量";



-- VuhDoFormButtonColor.lua
-- @EXACT = false
-- Labels
VUHDO_I18N_TEXT = "文本";
VUHDO_I18N_DEBUFFS = "減益";
VUHDO_I18N_ANOMALIES = "時間";
VUHDO_I18N_OPACITY = "透明度";



-- VuhDoFormButtonSize.lua
-- @EXACT = false
VUHDO_I18N_PANEL = "面板";
VUHDO_I18N_SPACING = "填白";
VUHDO_I18N_BAR_HEIGHT = "高度";
VUHDO_I18N_TARGETS = "目標";
VUHDO_I18N_BAR_TEXTURE = "材質";
VUHDO_I18N_HEIGHT = "高度";
VUHDO_I18N_BAR_WIDTH = "寬度";
VUHDO_I18N_WIDTH = "寬度";
VUHDO_I18N_HEADERS = "標題";
VUHDO_I18N_CLASS_COL = "職業Col.";
--



-- VuhDoOptionsSpell.lua
-- @EXACT = false
VUHDO_I18N_KEY_MODIFIES = "組合鍵";
VUHDO_I18N_KEY_NONE = "無";
VUHDO_I18N_ALT = "Alt";
VUHDO_I18N_CTRL = "Ctrl";
VUHDO_I18N_SHIFT = "Shift";
VUHDO_I18N_LEFT_BUTTON = "鼠標左鍵";
VUHDO_I18N_RIGHT_BUTTON = "鼠標右鍵";
VUHDO_I18N_MIDDLE_BUTTON = "鼠標中鍵";
VUHDO_I18N_BUTTON_4 = "鼠標鍵4";
VUHDO_I18N_BUTTON_5 = "鼠標鍵5";
VUHDO_I18N_MOUSE_KEY = "鼠標鍵位";
VUHDO_I18N_IN_MACROS_USE = "(在巨集中用\"vuhdo\"替代目標名稱)";
VUHDO_I18N_SPELL_STATIC = "或target(目標)/focus(焦點)/assist(協助)/menu(菜單)/tell(密語)/dropdown(下拉)";
VUHDO_I18N_NAME_TIP = "可填寫法術、巨集或物品名稱";
VUHDO_I18N_PLUS_SHIFT = "+Shift";
VUHDO_I18N_PLUS_CTRL_SHIFT = "+Ctrl+Shift";
VUHDO_I18N_PLUS_CTRL = "+Ctrl";



-- VuhDoTooltipConfig.lua
-- @EXACT = false
VUHDO_I18N_AROUND_PANEL = "周邊面板";
VUHDO_I18N_SHOW_IN_FIGHT = "戰鬥中";




-- New Options - Tooltips
-- @EXACT = false
VUHDO_I18N_TT_001 = "設定你需要VuhDo處理的增益";
VUHDO_I18N_TT_002 = "選擇增益顯示面板外觀";
VUHDO_I18N_TT_003 = "選擇增益材質和不同計時器條件的顏色";
VUHDO_I18N_TT_004 = "調整計時器設置和選擇增益版本";

VUHDO_I18N_TT_005 = "調節VuhDo增益監視全局縮放";
VUHDO_I18N_TT_006 = "設置每行最大增益個數";
VUHDO_I18N_TT_007 = "設置每列最大增益個數";
VUHDO_I18N_TT_008 = "設置增益顯示的刷新率";
VUHDO_I18N_TT_009 = "在標題欄顯示增益名稱";
VUHDO_I18N_TT_010 = "顯示空白小組的增益";
VUHDO_I18N_TT_011 = "開啟增益監視";

VUHDO_I18N_TT_012 = "選擇增益持續時間充足的提示顏色";
VUHDO_I18N_TT_013 = "選擇增益剩餘時間較短的提示顏色";
VUHDO_I18N_TT_014 = "選擇增益（部分）缺失的提示顏色";
VUHDO_I18N_TT_015 = "選擇顏色以提示所有可釋放增益目標均不在施法範圍內，無法提供增益";
VUHDO_I18N_TT_016 = "選擇增益技能冷卻中的提示顏色";
VUHDO_I18N_TT_017 = "選擇顏色以提示該小組目前無成員";
VUHDO_I18N_TT_018 = "選擇增益面板背景顏色";
VUHDO_I18N_TT_019 = "選擇增益邊界顏色";
VUHDO_I18N_TT_020 = "選擇增益監視面板邊界顏色";

VUHDO_I18N_TT_021 = "增益法術冷卻結束立即刷新增益";
VUHDO_I18N_TT_022 = "選擇判定增益剩餘時間低的臨界百分值（相對增益總時長的百分比）";
VUHDO_I18N_TT_023 = "選擇判定增益剩餘時間低的臨界值（絕對時間長度）";
VUHDO_I18N_TT_024 = "根據以下滑塊為團隊成員補充增益.";
VUHDO_I18N_TT_025 = "總是使用單人版增益法術. (比如施法材料用盡的情況下...)";
VUHDO_I18N_TT_026 = "總是使用隊伍/團隊版增益法術";
VUHDO_I18N_TT_027 = "至少有……名隊友增益剩餘時間低時才使用隊伍/團隊版增益法術.";

VUHDO_I18N_TT_028 = "根據玩家所處狀態設置顏色.";
VUHDO_I18N_TT_029 = "根據已選定顯示模式設定顏色.";

VUHDO_I18N_TT_031 = "點擊修改緊急指示顏色(注意：必須在有一個緊急情況被激活的情況下).";
VUHDO_I18N_TT_032 = "點擊修改玩家處於非緊急狀態下的指示顏色(注意：必須在有一個緊急情況被激活的情況下).";
VUHDO_I18N_TT_033 = "點擊修改滿血玩家顏色. (參見:主設置面板中的\"Irrelevant\"滑條)";
VUHDO_I18N_TT_034 = "點擊修改玩家正獲得治療顏色. (注意：需要獲得治療顯示開啟)";
VUHDO_I18N_TT_035 = "點擊修改施法距離之外玩家顏色. (注意：需要距離檢測開啟)";

VUHDO_I18N_TT_036 = "變色指示死亡玩家.";
VUHDO_I18N_TT_037 = "變色指示離線玩家.";
VUHDO_I18N_TT_038 = "變色指示被精神控制的玩家.";
VUHDO_I18N_TT_039 = "改變獲得仇恨指示顏色.";
VUHDO_I18N_TT_040 = "變色指示中毒玩家.";
VUHDO_I18N_TT_041 = "變色指示中疾病玩家.";
VUHDO_I18N_TT_042 = "變色指示中詛咒玩家.";
VUHDO_I18N_TT_043 = "變色指示受魔法減益影響的玩家.";

VUHDO_I18N_TT_044 = "設置VuhDo的基本行為.";
VUHDO_I18N_TT_045 = "選擇VuhDo監測的信息.";

VUHDO_I18N_TT_046 = "讓VuhDo在自動選擇合適的治療法術.";
VUHDO_I18N_TT_047 = "自動選擇合適的法術等級（2.3後已經沒用了）";
VUHDO_I18N_TT_048 = "治療前自動驅散.";
VUHDO_I18N_TT_049 = "自動救人.";
VUHDO_I18N_TT_050 = "開啟智能施法.";
VUHDO_I18N_TT_051 = "監測玩家獲得仇恨.";
VUHDO_I18N_TT_052 = "戰鬥記錄分析.分析戰鬥記錄對提高很有幫助.";
VUHDO_I18N_TT_053 = "整體治療視覺效果選擇.大型團隊活動以外情況下，建議選擇\"正常顯示\".";
VUHDO_I18N_TT_054 = "設定最大血量危急玩家顯示數目.默認無限制";
VUHDO_I18N_TT_055 = "設定一個健康血量百分比臨界值，意味著血量高於這個百分比的玩家將被認為是健康的，其血條也將被一定程度上淡化";

VUHDO_I18N_TT_056 = "忽略無害的減益魔法(根據減益性質判定).";
VUHDO_I18N_TT_057 = "忽略降低移動速度的減益.";
VUHDO_I18N_TT_058 = "忽略作用周期非常短的減益.";
VUHDO_I18N_TT_059 = "忽略與職業無關的減益(例如盜賊--法力燃燒).";
VUHDO_I18N_TT_060 = "只顯示你可以驅散的減益.不勾選則顯示全部減益.";
VUHDO_I18N_TT_061 = "開啟一般減益偵測.";
VUHDO_I18N_TT_062 = "過量治療時血條閃爍.";
VUHDO_I18N_TT_063 = "顯示你對自己的治療，這可能對某些玩家造成誤導.";
VUHDO_I18N_TT_064 = "指示正在獲得的（未讀完的）治療輸入.可能對降低過量治療有所幫助.";
VUHDO_I18N_TT_065 = "選擇檢查玩家是否在治療範圍內的刷新率.注意：較低的設定值可能導致系統表現的下降.";
VUHDO_I18N_TT_066 = "檢查一個\"典型的\"治療法術的距離.如果您不具有任何增益法術也選此項.";
VUHDO_I18N_TT_067 = "輸入一個法術名稱,該法術將被用於檢測距離.";
VUHDO_I18N_TT_068 = "用右邊的法術施放距離進行距離檢測.";
VUHDO_I18N_TT_069 = "開啟距離檢測.";

VUHDO_I18N_TT_070 = "選擇HOT圖標基於條高度的縮放百分比";
VUHDO_I18N_TT_071 = "血條內部右側顯示HOT圖標";
VUHDO_I18N_TT_072 = "血條內部左側顯示HOT圖標";
VUHDO_I18N_TT_073 = "血條外部右側顯示HOT圖標";
VUHDO_I18N_TT_074 = "血條外部左側顯示HOT圖標";
VUHDO_I18N_TT_075 = "在血條側顯示自己的HOT";
VUHDO_I18N_TT_076 = "通過名字選擇你最喜歡的條背景.";
VUHDO_I18N_TT_077 = "移動修改條的背景紋理.";
VUHDO_I18N_TT_078 = "修改面板背景顏色.";
VUHDO_I18N_TT_079 = "修改面板邊界顏色.";
VUHDO_I18N_TT_080 = "在法力條之外單獨顯示能量條.";
VUHDO_I18N_TT_081 = "拖動縮放法力條.";
VUHDO_I18N_TT_082 = "在面板中顯示法力條";

VUHDO_I18N_TT_083 = "在\"隊伍\"選項開啟時，設置每行最大小組數.";
VUHDO_I18N_TT_084 = "在治療面板上鬆散顯示所有玩家按鈕，而不進行隊伍或職業排序，開啟此選項將自動隱藏標題.";
VUHDO_I18N_TT_085 = "在選定面板中顯示所有玩家按鈕並按他們的小隊/職業排列";
VUHDO_I18N_TT_086 = "勾選後，團隊中的無成員小隊將被隱藏. (僅在\"隊伍\"選項開啟時有效).";
VUHDO_I18N_TT_087 = "選擇每行的最大列數Selects the max. number of columns per row before a line break.";
VUHDO_I18N_TT_088 = "面板錨點左上方.";
VUHDO_I18N_TT_089 = "面板錨點在右上方.";
VUHDO_I18N_TT_090 = "面板錨點在左下方.";
VUHDO_I18N_TT_091 = "面板錨點在右下方.";
VUHDO_I18N_TT_092 = "使玩家在面板中按默認團隊界面排列.";
VUHDO_I18N_TT_093 = "使玩家在面板中按最大血量排列.";
VUHDO_I18N_TT_094 = "使玩家在面板中按姓氏字母排列.";

VUHDO_I18N_TT_095 = "拖動修改標題高度.";
VUHDO_I18N_TT_096 = "拖動修改標題與生命/法力條間距.";
VUHDO_I18N_TT_097 = "顯示標題. (注意:必須先選擇\"基本選項\"=>\"隊伍\".)";
VUHDO_I18N_TT_098 = "移動修改標題背景材質.";
VUHDO_I18N_TT_099 = "按名字選擇標題背景材質.";
VUHDO_I18N_TT_100 = "移動調節標題背景基於條寬的百分比.";
VUHDO_I18N_TT_101 = "標題文本縮放.";
VUHDO_I18N_TT_102 = "按職業顏色顯示標題文本. (注意:僅當標題與職業關聯時有效)";
VUHDO_I18N_TT_103 = "修改標題背景與文本顏色.";

VUHDO_I18N_TT_104 = "設置面板標題外觀";
VUHDO_I18N_TT_105 = "設置面板基礎外觀.";
VUHDO_I18N_TT_106 = "設置提示樣式";
VUHDO_I18N_TT_107 = "血條文本內容與顯示方式配置.";
VUHDO_I18N_TT_108 = "選擇是否在面板中顯示玩家目標以及它們的樣式.";
VUHDO_I18N_TT_109 = "設置血條的寬度、高度以及填白、空隙.";
VUHDO_I18N_TT_110 = "設置血條外觀、面板背景及邊界顏色.";
VUHDO_I18N_TT_111 = "點擊將使當前子菜單設置應用於你所有的面板！";

VUHDO_I18N_TT_112 = "設置血條水平間隙.";
VUHDO_I18N_TT_113 = "設置血條縱向間隙.";
VUHDO_I18N_TT_114 = "設定邊界與血條間的縱向距離.";
VUHDO_I18N_TT_115 = "設定邊界與血條間的水平距離.";
VUHDO_I18N_TT_116 = "設定面板血條高度.";
VUHDO_I18N_TT_117 = "設定面板血條寬度.";

VUHDO_I18N_TT_118 = "調節目標條與血條間隙.";
VUHDO_I18N_TT_119 = "顯示當前面板中玩家的目標.";
VUHDO_I18N_TT_120 = "移動修改當前面板目標條寬度.";
VUHDO_I18N_TT_121 = "同時顯示團隊標記與目標名字.";
VUHDO_I18N_TT_122 = "顯示團隊標記而不顯示目標名字. (如果存在團隊標記)";
VUHDO_I18N_TT_123 = "總是顯示目標名字而不顯示團隊標記";
VUHDO_I18N_TT_124 = "目標名字文本縮放.";
VUHDO_I18N_TT_126 = "血量文本百分比顯示.";
VUHDO_I18N_TT_127 = "血量文本按損失數值顯示.";
VUHDO_I18N_TT_128 = "血量文本按剩餘數值顯示.";
VUHDO_I18N_TT_129 = "血量文本在玩家名字右邊";
VUHDO_I18N_TT_130 = "血量文本在玩家名字左邊";
VUHDO_I18N_TT_131 = "血量文本在玩家名字下邊.";
VUHDO_I18N_TT_132 = "血量文本在玩家名字上邊.";
VUHDO_I18N_TT_133 = "在血條上顯示血量文本.";
VUHDO_I18N_TT_134 = "血條文本縮放.";
VUHDO_I18N_TT_135 = "玩家名字用職業顏色顯示.";
VUHDO_I18N_TT_136 = "修改血條文本顏色.";
VUHDO_I18N_TT_137 = "修改各血條背景顏色. (注意：不是面板背景顏色！).";
VUHDO_I18N_TT_138 = "解鎖提示面板，可隨意移動.拖動提示面板並決定其位置.";
VUHDO_I18N_TT_139 = "開啟工具提示鼠標指針跟隨. (注意：可能會影響操作)";
VUHDO_I18N_TT_140 = "使用暴雪標準界面工具提示位置.";
VUHDO_I18N_TT_141 = "通常顯示工具提示.";
VUHDO_I18N_TT_142 = "在戰鬥中也顯示工具提示";
VUHDO_I18N_TT_143 = "工具提示全局縮放";
VUHDO_I18N_TT_144 = "選擇工具提示背景顏色.";
VUHDO_I18N_TT_145 = "選擇工具提示邊界顏色.";
VUHDO_I18N_TT_146 = "設定組合鍵\"ALT+SHIFT\"綁定技能.";
VUHDO_I18N_TT_147 = "設定組合鍵\"CTRL\".綁定技能";
VUHDO_I18N_TT_148 = "設定組合鍵\"CTRL+SHIFT\".綁定技能";
VUHDO_I18N_TT_149 = "設定組合鍵\"ALT+CTRL+SHIFT\".綁定技能";
VUHDO_I18N_TT_150 = "設定無組合鍵使用時的綁定技能";
VUHDO_I18N_TT_151 = "設定組合鍵\"ALT\".綁定技能";
VUHDO_I18N_TT_152 = "設定組合鍵\"SHIFT\".綁定技能";
VUHDO_I18N_TT_153 = "設定組合鍵\"ALT+CTRL\".綁定技能";
VUHDO_I18N_TT_154 = "設置完成.確認所有修改.";
VUHDO_I18N_TT_155 = "中止設置.放棄所有修改.";
VUHDO_I18N_TT_156 = "當增益剩餘次數大於一次（如心靈之火）時，隱藏計數.";
VUHDO_I18N_TT_157 = "修改法力、能量或怒氣顏色."
VUHDO_I18N_TT_158 = "選擇法力條顏色."
VUHDO_I18N_TT_159 = "選擇怒氣條顏色."
VUHDO_I18N_TT_160 = "選擇能量條顏色."
VUHDO_I18N_TT_161 = "選擇符文能量顏色."
VUHDO_I18N_TT_162 = "打開仇恨、獲得仇恨顯示設置面板"
VUHDO_I18N_TT_163 = "雜項設置."
VUHDO_I18N_TT_164 = "保存或讀取皮膚便於外觀快速設置."
VUHDO_I18N_TT_165 = "不再在隊伍/職業面板中顯示主坦克."
VUHDO_I18N_TT_166 = "不再顯示隊伍/職業面板顯示玩家目標."
VUHDO_I18N_TT_167 = "不再將自己所在小隊作為常規小隊進行顯示. (通常你會有本小隊框體或者開啟了VuhDo隊伍選項中的\"我的小隊\" )"
VUHDO_I18N_TT_168 = "在玩家名字前方顯示暫離、離線或死亡標籤"
VUHDO_I18N_TT_169 = "隱藏暴雪隊伍框體."
VUHDO_I18N_TT_170 = "隱藏暴雪玩家框體."
VUHDO_I18N_TT_171 = "只在法術的施放目標顯示多目標HOT."
VUHDO_I18N_TT_172 = "多目標HOT顯示在所有受影響者上.警告：開啟此項可能導致系統表現下降!"
VUHDO_I18N_TT_173 = "選擇HOT更新的刷新率" -- 173
VUHDO_I18N_TT_174 = "輸入已存在的皮膚名稱進行讀取、覆蓋或刪除操作，或將當前皮膚另存為..."
VUHDO_I18N_TT_175 = "選擇皮膚.皮膚是對視覺效果的總體設置，如顏色、材質等."
VUHDO_I18N_TT_176 = "輸入已存在的皮膚名稱進行讀取、覆蓋或刪除操作，或將當前皮膚另存為..."
VUHDO_I18N_TT_177 = "選擇一套佈局.這些設置包括了縮放、格式和佈局."
VUHDO_I18N_TT_178 = "選擇目標仇恨的相對臨界值,仇恨超過這個臨界值的玩家在仇恨條上的顯示由青色轉為紅色"
VUHDO_I18N_TT_179 = "設置仇恨條高度"
VUHDO_I18N_TT_180 = "在每個治療按鍵的上下方用脈動線顯示仇恨過高（橙色）和獲得仇恨目標（紅色）"
VUHDO_I18N_TT_181 = "在治療按鍵上方顯示仇恨情況條（百分比）."
VUHDO_I18N_TT_182 = "仇恨情況整體監視" -- 182
VUHDO_I18N_TT_183 = "選擇仇恨目標/仇恨監視刷新率"
VUHDO_I18N_TT_184 = "選擇要在仇恨目標名字左旁邊顯示的文字"
VUHDO_I18N_TT_185 = "在仇恨目標名字上添加文字提示"
VUHDO_I18N_TT_186 = "在仇恨目標單元按鍵下方作劃線指示"
VUHDO_I18N_TT_187 = "由VuhDo進行仇恨目標監測"
VUHDO_I18N_TT_188 = "選擇要在仇恨目標名字右旁邊顯示的文字" -- 188
VUHDO_I18N_TT_189 = "使用當前小隊/團隊進行測試."
VUHDO_I18N_TT_190 = "選擇以顯示測試5人隊伍/團隊."
VUHDO_I18N_TT_191 = "選擇以顯示測試10人團隊."
VUHDO_I18N_TT_192 = "選擇以顯示測試25人團隊."
VUHDO_I18N_TT_193 = "選擇以顯示測試40人團隊." -- 193
VUHDO_I18N_TT_194 = "開啟此項則血條顏色不再根據玩家血量發生變化（從綠到紅）而是始終顯示職業顏色."
VUHDO_I18N_TT_195 = "選擇標題字體"
VUHDO_I18N_TT_196 = "標題背景顏色使用職業顏色."
VUHDO_I18N_TT_197 = "選擇目標姓名文本顏色." -- 197
VUHDO_I18N_TT_198 = "選擇使用鼠標點擊施放的法術."
VUHDO_I18N_TT_199 = "選擇鼠標滑過時通過鍵盤施放的法術."
VUHDO_I18N_TT_200 = "選擇在其變為可用時立即使用的飾品/瞬發技能."
VUHDO_I18N_TT_201 = "輸入要在施放治療法術前使用的瞬發技能名稱.注意：這個技能不能有公共冷卻!"
VUHDO_I18N_TT_202 = "輸入要在施放治療法術前使用的瞬發技能名稱.注意：這個技能不能有公共冷卻!"
VUHDO_I18N_TT_203 = "在施放治療法術前先使用右邊的技能.注意：這個技能不能有公共冷卻!"
VUHDO_I18N_TT_204 = "在施放治療法術前先使用右邊的技能.注意：這個技能不能有公共冷卻!" -- 204
VUHDO_I18N_TT_205 = "施放治療法術前使用二號飾品（人物界面中下面的飾品）.注意：這個技能不能有公共冷卻!"
VUHDO_I18N_TT_206 = "施放治療法術前使用一號飾品（人物界面中上面的飾品）.注意：這個技能不能有公共冷卻!"
VUHDO_I18N_TT_207 = "不在戰鬥中時也能自動觸髮飾品."
VUHDO_I18N_TT_208 = "當技能為周期性治療法術時也能自動觸髮飾品."
VUHDO_I18N_TT_209 = "開啟/關閉飾品或技能的自動使用或施放."
VUHDO_I18N_TT_210 = "輸入開始復活時要說的話，用\"vuhdo\"代替名字";
VUHDO_I18N_TT_211 = "啟用複活時說話，用\"vuhdo\"代替名字";
VUHDO_I18N_TT_212 = "完全隱藏空面板";
VUHDO_I18N_TT_213 = "不在\"輔助坦克\"面板顯示焦點目標.";
VUHDO_I18N_TT_214 = "不在常規團隊/小隊面板中顯示協助坦克.";
VUHDO_I18N_TT_215 = "脫離戰鬥時對正在消失的BUFF進行補充。必須先在VuhDo增益監視中啟用該增益並為其指定顏色.";
VUHDO_I18N_TT_216 = "顯示從團隊/小隊其他玩家獲得的治療.";
VUHDO_I18N_TT_217 = "在血條生命值文本中添加正在獲得/過量治療";
VUHDO_I18N_TT_218 = "調整過量治療文本縮放.";
VUHDO_I18N_TT_219 = "在血條上用額外的白字顯示過量治療.";
VUHDO_I18N_TT_220 = "在獲得仇恨目標的玩家周圍顯示紅色邊框.";
VUHDO_I18N_TT_221 = "在戰鬥中也顯示正在消失的增益條";
VUHDO_I18N_TT_222 = "以文本顏色顯示正在消失的增益";
VUHDO_I18N_TT_223 = "以條顏色顯示正在消失的增益";
VUHDO_I18N_TT_224 = "HOT方塊基本顏色設定菜單";
VUHDO_I18N_TT_225 = "HOT方塊顏色高級設置菜單";
VUHDO_I18N_TT_226 = "設置職業顏色";
VUHDO_I18N_TT_227 = "選擇條背景職業顏色與條顏色的相對亮度.";
VUHDO_I18N_TT_228 = "以職業顏色顯示寵物.";
VUHDO_I18N_TT_229 = "選擇戰士顏色";
VUHDO_I18N_TT_230 = "選擇盜賊顏色";
VUHDO_I18N_TT_231 = "選擇獵人顏色";
VUHDO_I18N_TT_232 = "選擇聖騎士顏色";
VUHDO_I18N_TT_233 = "選擇術士顏色";
VUHDO_I18N_TT_234 = "選擇薩滿祭司顏色";
VUHDO_I18N_TT_235 = "選擇德魯伊顏色";
VUHDO_I18N_TT_236 = "選擇牧師顏色";
VUHDO_I18N_TT_237 = "選擇法師顏色";
VUHDO_I18N_TT_238 = "選擇死亡騎士顏色";
VUHDO_I18N_TT_239 = "選擇寵物顏色";
VUHDO_I18N_TT_240 = "顯示HOT剩餘次數，如果選擇了方塊而不是HOT圖標，則顯示四個小三角形作為指示.";
VUHDO_I18N_TT_241 = "在左側以文本顏色顯示HOT剩餘次數.";
VUHDO_I18N_TT_242 = "以背景顏色在左側顯示HOT疊加層數Check to display number of HoT appliances by background color to the left.";
VUHDO_I18N_TT_243 = "選擇HOT第二跳的顏色";
VUHDO_I18N_TT_244 = "選擇HOT第三跳的顏色";
VUHDO_I18N_TT_245 = "選擇HOT第四跳的顏色";
VUHDO_I18N_TT_246 = "選擇1號HOT條顏色";
VUHDO_I18N_TT_247 = "選擇2號HOT條顏色";
VUHDO_I18N_TT_248 = "選擇3號HOT條顏色";
VUHDO_I18N_TT_249 = "選擇1號HOT方塊顏色";
VUHDO_I18N_TT_250 = "選擇2號HOT方塊顏色";
VUHDO_I18N_TT_251 = "選擇3號HOT方塊顏色";
VUHDO_I18N_TT_252 = "選擇4號HOT方塊顏色";
VUHDO_I18N_TT_253 = "選擇5號HOT方塊顏色";
VUHDO_I18N_TT_254 = "選擇剩餘時間較短的HOT顏色";
VUHDO_I18N_TT_255 = "選擇應用時間警報顏色並顯示高速偵測（0.1秒）的時間.";
VUHDO_I18N_TT_256 = "顯示HOT計數器和計時器文本輪廓.";
VUHDO_I18N_TT_257 = "在HOT計數器和計時器文本後添加陰影.";
VUHDO_I18N_TT_258 = "HOT剩餘時間低於左側設定值時顯示警報顏色.";
VUHDO_I18N_TT_259 = "顯示HOT方塊/圖標.不選則只顯示文本.";
VUHDO_I18N_TT_260 = "當HOT剩餘時間很短時圖標/方塊淡出顯示.";
VUHDO_I18N_TT_261 = "選擇自定義減益顏色";
VUHDO_I18N_TT_262 = "減益圖標浮動.";
VUHDO_I18N_TT_263 = "選擇需要顯示的減益.";
VUHDO_I18N_TT_264 = "選擇需要顯示的自定義增、減益.";
VUHDO_I18N_TT_265 = "面板嚮導幫助你快速設置面板組.";
VUHDO_I18N_TT_266 = "用圖標顯示自定義增、減益.";
VUHDO_I18N_TT_267 = "用條顏色顯示自定義增、減益.";
VUHDO_I18N_TT_268 = "在圖標上顯示動畫效果.";
VUHDO_I18N_TT_269 = "圖標顯示剩餘時間.";
VUHDO_I18N_TT_270 = "移動縮放自定義增、減益圖標.";
VUHDO_I18N_TT_271 = "選擇同時顯示自定義增、減益的最大數量.";
VUHDO_I18N_TT_272 = "選擇獲得自定義增益時的提示聲音.";
VUHDO_I18N_TT_273 = "用圖標顯示自定義增、減益.";
VUHDO_I18N_TT_274 = "用條顏色顯示自定義增、減益.";
VUHDO_I18N_TT_275 = "在圖標上顯示動畫效果.";
VUHDO_I18N_TT_276 = "圖標顯示剩餘時間.";
VUHDO_I18N_TT_277 = "選擇血條周邊的玩家目標邊框顏色.";
VUHDO_I18N_TT_278 = "選擇所有血條邊框顏色.";
VUHDO_I18N_TT_279 = "選擇玩家獲得減益提示聲音";
VUHDO_I18N_TT_280 = "應用已選定面板設定";
VUHDO_I18N_TT_281 = "開啟額外的載具面板.寵物也將在此面板顯示.所有鼠標點擊都只是選定載具/寵物為目標.";
VUHDO_I18N_TT_282 = "開啟額外的寵物面板.";
VUHDO_I18N_TT_283 = "開啟額外的玩家目標面板.玩家目標類似主坦克顯示，但扔保留輔助坦克.";
VUHDO_I18N_TT_284 = "開啟額外的主坦克面板.";
VUHDO_I18N_TT_285 = "無組別顯示所有團隊單元Select this to show all raid units ungrouped.這是一種簡約而不簡單的顯示方式.";
VUHDO_I18N_TT_286 = "團隊按職責分組：:近戰輸出,近戰坦克,遠程輸出,治療.";
VUHDO_I18N_TT_287 = "團隊按職業分組.";
VUHDO_I18N_TT_288 = "團隊中所有小隊按隊號排列(1-8).";
VUHDO_I18N_TT_289 = "隱藏暴雪標準寵物框體.";
VUHDO_I18N_TT_290 = "隱藏暴雪標準目標框體.";
VUHDO_I18N_TT_291 = "放開鼠標按鍵而不是按下鼠標按鍵時開始施法.";
VUHDO_I18N_TT_292 = "開啟暴雪標準工具提示並關閉VuhDo工具提示.";
VUHDO_I18N_TT_293 = "在所有玩家條周圍顯示一個框體.";
VUHDO_I18N_TT_294 = "在當前選定目標周圍顯示一個框體.";
VUHDO_I18N_TT_295 = "鼠標劃過單位高亮顯示.";
VUHDO_I18N_TT_296 = "高亮顯示鼠標劃過組員.";
VUHDO_I18N_TT_297 = "選擇鼠標劃過緊湊小隊時高亮顯示的方式";
VUHDO_I18N_TT_298 = "設定當前佈局為未組隊時自動啟用.";
VUHDO_I18N_TT_299 = "設定當前佈局為五人隊時自動啟用.";
VUHDO_I18N_TT_300 = "設定當前佈局為十人團隊時自動啟用.";
VUHDO_I18N_TT_301 = "設定當前佈局為二十五人團隊時自動啟用.";
VUHDO_I18N_TT_302 = "設定當前佈局為超過二十五人團隊時自動啟用.";
VUHDO_I18N_TT_303 = "條顏色根據生命值紅綠變化.";
VUHDO_I18N_TT_304 = "固定使用右側設定顏色顯示血條.";
VUHDO_I18N_TT_305 = "血條背景使用職業顏色.";
VUHDO_I18N_TT_306 = "修改你的血條顏色.";
VUHDO_I18N_TT_307 = "放大顯示受傷害者血條（不選則收縮）.";
VUHDO_I18N_TT_308 = "血條按豎直（而不是水平）方向變化.";
VUHDO_I18N_TT_309 = "在血條中顯示團隊標記.";
VUHDO_I18N_TT_310 = "使血條呈水平（而不是豎直）排列";
VUHDO_I18N_TT_311 = "總是在小隊頂端（第一位）顯示自己.";
VUHDO_I18N_TT_312 = "設定面板錨點為頂端中點.";
VUHDO_I18N_TT_313 = "設定面板錨點為底部中點.";
VUHDO_I18N_TT_314 = "設定面板錨點為左邊中點.";
VUHDO_I18N_TT_315 = "設定面板錨點為右邊中點.";
VUHDO_I18N_TT_316 = "按最大血量排列組員.";
VUHDO_I18N_TT_317 = "按職業分組";
VUHDO_I18N_TT_318 = "選擇HOT條寬度.";
VUHDO_I18N_TT_319 = "開啟HOT條";
VUHDO_I18N_TT_320 = "為第三槽位指定HOT.";
VUHDO_I18N_TT_321 = "為第二槽位指定HOT.";
VUHDO_I18N_TT_322 = "為第一槽位指定HOT.";
VUHDO_I18N_TT_323 = "設定條收縮為從左至右.";
VUHDO_I18N_TT_324 = "設定條收縮為豎直方向而非水平方向";
VUHDO_I18N_TT_325 = "在血條左上顯示HOT圖標";
VUHDO_I18N_TT_326 = "在血條右下顯示HOT圖標";
VUHDO_I18N_TT_327 = "在血條左下顯示HOT圖標";
VUHDO_I18N_TT_328 = "在血條右下顯示HOT圖標";
VUHDO_I18N_TT_329 = "在血條左下顯示HOT圖標";
VUHDO_I18N_TT_330 = "在可施放\"迅捷治愈\" (限德魯伊)的目標血條上顯示一個小紅圈.";
VUHDO_I18N_TT_331 = "使HOT方塊材質蒼白";
VUHDO_I18N_TT_332 = "指定5號槽位HOT.如選擇顏色方塊而不是HOT圖標，則不能顯示";
VUHDO_I18N_TT_333 = "指定4號槽位HOT.";
VUHDO_I18N_TT_334 = "指定3號槽位HOT.";
VUHDO_I18N_TT_335 = "指定2號槽位HOT.";
VUHDO_I18N_TT_336 = "指定號槽位HOT.";
VUHDO_I18N_TT_337 = "配置HOT圖標樣式.";
VUHDO_I18N_TT_338 = "配置HOT條樣式.";
VUHDO_I18N_TT_339 = "面板整體縮放.";
VUHDO_I18N_TT_340 = "不以千為單位顯示生命值.例如14537而不是14.5k";
VUHDO_I18N_TT_341 = "在血條上顯示玩家名字.";
VUHDO_I18N_TT_342 = "在血條上顯示玩家職業";
VUHDO_I18N_TT_343 = "選擇按名字顯示的最大玩家數.";
VUHDO_I18N_TT_344 = "選擇玩家血條姓名字體.";
VUHDO_I18N_TT_345 = "點擊血條和目標單元框時保持姿態不變.不選擇此項可能使你自動切換姿態.";
VUHDO_I18N_TT_346 = "開啟法術工具提示信息";
VUHDO_I18N_TT_347 = "使點擊\"穿透\"面板背景以允許選定目標、移動等.開啟此項將不能通過右鍵點擊顯示誰是團長等等..";
VUHDO_I18N_TT_348 = "鎖定治療面板";
VUHDO_I18N_TT_349 = "針對敵對目標的法術選項目";
VUHDO_I18N_TT_350 = "在自定義減益圖標上顯示堆疊層數.";
VUHDO_I18N_TT_351 = "設定自定義減益錨點為血條左上.";
VUHDO_I18N_TT_352 = "設定自定義減益錨點為血條右上.";
VUHDO_I18N_TT_353 = "設定自定義減益錨點為血條左下.";
VUHDO_I18N_TT_354 = "設定自定義減益錨點為血條右下.";
VUHDO_I18N_TT_355 = "豎向調節自定義減益圖標位置.";
VUHDO_I18N_TT_356 = "橫向調節自定義減益圖標位置.";
VUHDO_I18N_TT_357 = "用名字文本顯示寵物/載具主人";
VUHDO_I18N_TT_358 = "設置非戰斗狀態下的智能施法功能";
VUHDO_I18N_TT_359 = "為智能施法指定一個組合按鍵.";
VUHDO_I18N_TT_360 = "戰鬥中自動觸發戰复(限德魯伊)";
VUHDO_I18N_TT_361 = "在血條左邊顯示目標條."
VUHDO_I18N_TT_362 = "在血條右邊顯示目標條."
VUHDO_I18N_TT_363 = "傷害閃爍靈敏度. 較大的數值意味著(對更低的傷害)更強的閃爍 .";
VUHDO_I18N_TT_364 = "血量高於警戒線時不顯示生命值文字.";
VUHDO_I18N_TT_365 = "當法術佈局發生變化時應用與HoT設置(選項=>面板=>HoTs) .";
VUHDO_I18N_TT_366 = "治療時切換目標至被治療者.";
VUHDO_I18N_TT_367 = "該面板將幫助你選擇需要監測的治療輸入類型.";
VUHDO_I18N_TT_368 = "Select the latest point in the future you want to see direct casts from.";
VUHDO_I18N_TT_369 = "顯示來自直接法術的治療輸入.";
VUHDO_I18N_TT_370 = "Select the latest point in the future you want to see channelled heals from.";
VUHDO_I18N_TT_371 = "顯示來自引導法術的治療輸入.";
VUHDO_I18N_TT_372 = "Select the latest point in the future you want to see HoTs from.";
VUHDO_I18N_TT_373 = "顯示來自HoTs的治療輸入.";
VUHDO_I18N_TT_374 = "Select the latest point in the future you want to see bombed heals from.";
VUHDO_I18N_TT_375 = "顯示來自爆發法術的治療輸入(atm: 生命之花效果).";
VUHDO_I18N_TT_376 = "Select to align groups at the bottom of the panel (at the right, when \"horizontal\" is selected above).";
VUHDO_I18N_TT_377 = "選擇面板邊緣材質.";
VUHDO_I18N_TT_378 = "面板邊界邊緣縮放.";
VUHDO_I18N_TT_379 = "Select an inset size for panel borders.";
VUHDO_I18N_TT_380 = "Check this to not show yourself in regular raid/party frames.";
VUHDO_I18N_TT_381 = "Check to apply background bar brightness setting to health bar instead of background bar when debuff color is applied. Useful if your background bar color is brighter than your health bar color.";
VUHDO_I18N_TT_382 = "Check to show an outline around name and life text instead of a shadow.";
VUHDO_I18N_TT_383 = "Ignore Pets in buff tracking.";
VUHDO_I18N_TT_384 = "Sorts raid by the order given in \"Move!\". Selecting this will only work if order is set to \"loose\" above.";
VUHDO_I18N_TT_385 = "Select a health bar color that will be applied if this buff is missing on the player.";
VUHDO_I18N_TT_386 = "若增益將消失則變色顯示.";
VUHDO_I18N_TT_387 = "提高該BUFF的優先級.";
VUHDO_I18N_TT_388 = "降低該BUFF的優先級.";
VUHDO_I18N_TT_389 = "選擇 HoT 方塊 6 的顏色";
VUHDO_I18N_TT_390 = "Check to invert sorting.";
VUHDO_I18N_TT_391 = "團隊標記縮放.";
VUHDO_I18N_TT_392 = "Set component anchor to the top-left.";
VUHDO_I18N_TT_393 = "Set component anchor to the top-right.";
VUHDO_I18N_TT_394 = "Set component anchor to the bottom-left.";
VUHDO_I18N_TT_395 = "Set component anchor to the bottom-right.";
VUHDO_I18N_TT_396 = "Set component anchor to the left.";
VUHDO_I18N_TT_397 = "Set component anchor to the top.";
VUHDO_I18N_TT_398 = "Set component anchor to the bottom";
VUHDO_I18N_TT_399 = "Set component anchor to the right.";
VUHDO_I18N_TT_400 = "Adjust component placement in horizontal direction.";
VUHDO_I18N_TT_401 = "Adjust component placement in vertical direction.";
VUHDO_I18N_TT_402 = "設置團隊標記和過量治療文本.";
VUHDO_I18N_TT_403 = "保存當前法術綁定.";
VUHDO_I18N_TT_404 = "讀取法術綁定.";
VUHDO_I18N_TT_405 = "隱藏玻璃渣默認焦點框體.";
VUHDO_I18N_TT_406 = "不顯示HOT剩餘堆疊數.";
VUHDO_I18N_TT_407 = "用文本計數器HOT剩餘堆疊數.";
VUHDO_I18N_TT_408 = "最多顯示HOT堆疊數在HOT圖標周圍顯示4 (= 4層或者更多) 個三角形.";
VUHDO_I18N_TT_409 = "單人遊戲時隱藏面板.";
VUHDO_I18N_TT_410 = "在小隊中或團隊不足五人時隱藏面板";
VUHDO_I18N_TT_411 = "設置團隊目標標記顏色";
VUHDO_I18N_TT_412 = "將這些默認設定複製到所有自定義減益上";
VUHDO_I18N_TT_413 = "為自定義減益指定顏色";
VUHDO_I18N_TT_414 = "選擇要顯示的團隊標記";
VUHDO_I18N_TT_415 = "選擇過量治療文字的顏色";
VUHDO_I18N_TT_416 = "用條/文字的顏色顯示團隊標記.";
VUHDO_I18N_TT_417 = "Check to only show raid icons by color that are enabled in Panels=>Misc";
VUHDO_I18N_TT_418 = "Select a color for this raid icon.";
VUHDO_I18N_TT_419 = "Tank mode will only watch the threat situation for aggro detection. Enemies occasionally targeting players will be ignored";
VUHDO_I18N_TT_420 = "牧師選項: 顯示盾剩餘吸收量. 醒目：仍處於測試階段.";

VUHDO_I18N_TT_421 = "選擇滿血單位顏色.";
VUHDO_I18N_TT_422 = "選擇單位血量中等的顏色.";
VUHDO_I18N_TT_423 = "選擇單位血量低的顏色."
VUHDO_I18N_TT_424 = "開啟聚團. 一個聚團為某一範圍內的一群人，該功能為治療之環以及治療鏈設計";
VUHDO_I18N_TT_425 = "選擇聚團刷新率. 可能會影響系統運行情況";
VUHDO_I18N_TT_426 = "選擇判別兩個玩家為聚團者的距離門限";
VUHDO_I18N_TT_427 = "Select a max. health level above which a unit is considered to be no worthwile target for a cluster healing spell";
VUHDO_I18N_TT_428 = "Select a minimum number of persons clustering up to be a fair target of your cluster heal.";
VUHDO_I18N_TT_429 = "Select a minimum number of persons clustering up to be a good target of your cluster heal."
VUHDO_I18N_TT_430 = "Select this if your cluster healing spell goes off from you (not from the target of the spell itself)";
VUHDO_I18N_TT_431 = "Select this if your cluster healing spell goes off from the target you are casting on (not from you, e.g. Circle of Healing)";
VUHDO_I18N_TT_432 = "Select this if all raid members will be affected by the spell (Chain Heal, Circle of Healing).";
VUHDO_I18N_TT_433 = "Select if only raid members in the spell target's group will benefit from your spell (Prayer of Healing)";
VUHDO_I18N_TT_434 = "Enable to draw a border around raid members which are in cluster with the unit you currently hover your mouse over.";
VUHDO_I18N_TT_435 = "Select to show the number of worthwile units currently clustering up (in cluster hot icon of each unit)";
VUHDO_I18N_TT_436 = "以條的形式顯示公共冷卻.";
VUHDO_I18N_TT_437 = "直接從目標周圍偵測聚團者.";
VUHDO_I18N_TT_438 = "Detects clusters jumping from target to to the nearby target with most health deficit."
VUHDO_I18N_TT_439 = "選擇你的鏈法術最多可跳躍的次數.";
VUHDO_I18N_TT_440 = "選擇聚團狀態一般的玩家人數顏色.";
VUHDO_I18N_TT_441 = "選擇聚團狀態良好的玩家人數顏色.";
VUHDO_I18N_TT_442 = "選擇鼠標滑過聚團邊界顏色.";
VUHDO_I18N_TT_443 = "選擇公共冷卻條顏色."
VUHDO_I18N_TT_444 = "If you check this button the currently selected arrangement will automatically enabled if you are in a raid of up to 15 players.";
VUHDO_I18N_TT_445 = "Check to also load HoT setup with arrangements. Don't do this if the arrangement has been saved on another class!";
VUHDO_I18N_TT_446 = "Select debuffs from the ignore list.";
VUHDO_I18N_TT_447 = "Check to rate players assigned as tanks by dungeon finder tool as MTs and show them in MT list.";
VUHDO_I18N_TT_448 = "Setup cluster detection for your mass healing spells";
VUHDO_I18N_TT_449 = "Select a color for threat indicator bar when threat is high.";
VUHDO_I18N_TT_450 = "Select a color for threat indicator bar when threat is low.";
VUHDO_I18N_TT_451 = "Enable to auto-rebuff all missing buffs using the mouse-wheel on a buff swatch.";
VUHDO_I18N_TT_452 = "Select a saved bouquet or type in a new name.";
VUHDO_I18N_TT_453 = "Select a special trigger or enter the name of a buff or debuff.";
VUHDO_I18N_TT_454 = "Select a color for this event/trigger.";
VUHDO_I18N_TT_455 = "Select a default icon for this event. If this is needed or not depends on the type of bouquet indicator.";
VUHDO_I18N_TT_456 = "Setup the bars indicators like icons and status bars.";
VUHDO_I18N_TT_457 = "Setup Bouquets. Bouquets are groups of Buffs, Debuffs and other occasions in a priorization order. You can setup a bouquet e.g. as a HoT icon";
VUHDO_I18N_TT_458 = "Will display buffs in a more screen estate saving way.";
VUHDO_I18N_TT_459 = "Enter a new boquet name to create or copy current bouquet to.";
VUHDO_I18N_TT_460 = "Enter a debuff, buff or hot name.";
VUHDO_I18N_TT_461 = "Select a color to show if statusbar value is low";
VUHDO_I18N_TT_462 = "Select a color to show if statusbar value is medium";
VUHDO_I18N_TT_463 = "Select a color to show if statusbar value is high.";
VUHDO_I18N_TT_464 = "Select a bouquet to show via this indicator";
VUHDO_I18N_TT_465 = "Enables Clique compatibility mode. Requires to reload UI after changing.";
VUHDO_I18N_TT_466 = "Scans all units no matter how far away";
VUHDO_I18N_TT_467 = "Only scans units which are in the same map with you.";
VUHDO_I18N_TT_468 = "Only scans units in a range of max. 100 yards.";
VUHDO_I18N_TT_469 = "Only scans units in a range of max. 40 yards.";
VUHDO_I18N_TT_470 = "Scans talent trees for raid role estimation. May conflict with other addons.";
VUHDO_I18N_TT_471 = "Makes bars grow from right to left.";
VUHDO_I18N_TT_472 = "Indicates units taking severe damage by flashing the health bars.";
VUHDO_I18N_TT_473 = "Enable this to show HoT squares using the original icon.";
VUHDO_I18N_TT_474 = "Enable this to show HoT squares using a glossy texture.";
VUHDO_I18N_TT_475 = "Auto-Enable profile whenever switching to primary specc";
VUHDO_I18N_TT_476 = "Auto-Enable profile whenever switching to secondaray specc";
VUHDO_I18N_TT_477 = "In this Menu you can reset several aspects of your configuration to factory defaults";
VUHDO_I18N_TT_478 = "Click to return to where you came from.";
VUHDO_I18N_TT_479 = "Only if the spell in this edit box has no cooldown clusters will be shown. Leave empty to always show clusters.";
VUHDO_I18N_TT_480 = "Move to change options screen scale";
VUHDO_I18N_TT_481 = "Setup HoT counter / timer font";
VUHDO_I18N_TT_482 = "Adjust HoT text size";
VUHDO_I18N_TT_483 = "Select a bouquet for the selected panel to override general health bar bouquet.";
VUHDO_I18N_TT_484 = "Enables PallyPower compatible remote blessing and aura setup communications";
VUHDO_I18N_TT_485 = "Check this to not show your target in \"Private Tanks\" panel.";
-- 2.17
VUHDO_I18N_TT_486 = "Enable to lock a profile so it can't be overwritten accidentally.";
VUHDO_I18N_TT_487 = "Enable to auto-overwrite existing profile instead of showing overwrite / copy / abort confirmation dialog.";
VUHDO_I18N_TT_488 = "Enable to only show direction if player is dead.";
VUHDO_I18N_TT_489 = "Enable to show distance to oor raid members.";
VUHDO_I18N_TT_490 = "Enable to show direction of out of range players by an arrow.";
VUHDO_I18N_TT_491 = "Check to display custom debuff name for about 2 secs after applied.";
-- 2.18
VUHDO_I18N_TT_492 = "Uncheck to enable creation of macros for emergency raid roster restoration after logging back in mid fight after a d/c. 2 free toon individual macro slots needed."
VUHDO_I18N_TT_493 = "Select direction arrow size."
VUHDO_I18N_TT_494 = "Select destination profile";
VUHDO_I18N_TT_495 = "Exports all custom debuffs of current profile to all profiles of this toon.";
VUHDO_I18N_TT_496 = "Exports all custom debuffs of current profile to selected profile.";
VUHDO_I18N_TT_497 = "Exports all custom debuffs of current profile to ALL other profiles.";

-- Key Binding Headers/Names
-- @EXACT = false
BINDING_HEADER_VUHDO_TITLE = "VuhDo -團隊框體";
BINDING_NAME_VUHDO_KEY_ASSIGN_1 = "鼠標滑過技能1";
BINDING_NAME_VUHDO_KEY_ASSIGN_2 = "鼠標滑過技能2";
BINDING_NAME_VUHDO_KEY_ASSIGN_3 = "鼠標滑過技能3";
BINDING_NAME_VUHDO_KEY_ASSIGN_4 = "鼠標滑過技能4";
BINDING_NAME_VUHDO_KEY_ASSIGN_5 = "鼠標滑過技能5";
BINDING_NAME_VUHDO_KEY_ASSIGN_6 = "鼠標滑過技能6";
BINDING_NAME_VUHDO_KEY_ASSIGN_7 = "鼠標滑過技能7";
BINDING_NAME_VUHDO_KEY_ASSIGN_8 = "鼠標滑過技能8";
BINDING_NAME_VUHDO_KEY_ASSIGN_9 = "鼠標滑過技能9";
BINDING_NAME_VUHDO_KEY_ASSIGN_10 = "鼠標滑過技能10";
BINDING_NAME_VUHDO_KEY_ASSIGN_11 = "鼠標滑過技能11";
BINDING_NAME_VUHDO_KEY_ASSIGN_12 = "鼠標滑過技能12";
BINDING_NAME_VUHDO_KEY_ASSIGN_13 = "鼠標滑過技能13";
BINDING_NAME_VUHDO_KEY_ASSIGN_14 = "鼠標滑過技能14";
BINDING_NAME_VUHDO_KEY_ASSIGN_15 = "鼠標滑過技能15";
BINDING_NAME_VUHDO_KEY_ASSIGN_16 = "鼠標滑過技能16";

BINDING_NAME_VUHDO_KEY_ASSIGN_SMART_BUFF = "智能Buff";

VUHDO_I18N_MOUSE_OVER_BINDING = "按鍵施法";
VUHDO_I18N_UNASSIGNED = "(未指定)";


-- #+V1.89
VUHDO_I18N_APPLY_TO_ALL = "全部應用";
VUHDO_I18N_YES = "Yes";
VUHDO_I18N_NO = "No";
VUHDO_I18N_UP = "上";
VUHDO_I18N_DOWN = "下";
VUHDO_I18N_TEST = "測試";
VUHDO_I18N_ADD = "添加";
VUHDO_I18N_SELECT = "選擇";
VUHDO_I18N_NEW_COLOR = "新顏色";
VUHDO_I18N_OLD_COLOR = "舊顏色";
VUHDO_I18N_HIDE_CHARGES = "隱藏消耗";
VUHDO_I18N_POWERS = "能量";
VUHDO_I18N_HOTS = "HoT";
VUHDO_I18N_HOT_COLORS = "HoT顏色";
VUHDO_I18N_ICONS = "圖標";
VUHDO_I18N_COUNTDOWN = "倒計時";
VUHDO_I18N_APPLIANCES = "裝置";
VUHDO_I18N_FADE_OUT = "淡出";
VUHDO_I18N_POWER_TYPES = "能量類型";
VUHDO_I18N_THREAT = "仇恨";
VUHDO_I18N_MISC = "雜項";
VUHDO_I18N_SKINS = "皮膚";
VUHDO_I18N_PANEL_WIZARD = "設置嚮導";
VUHDO_I18N_PRIV_TANKS = "輔助坦克";
VUHDO_I18N_FILTER = "過濾";
VUHDO_I18N_CUSTOM_DE_BUFFS = "自定義增/減益";
VUHDO_I18N_CHANGE_COLOR = "變色";
VUHDO_I18N_ICON = "圖標";
VUHDO_I18N_ANIMATION = "動畫";
VUHDO_I18N_STORE = "儲存";
VUHDO_I18N_SAVE = "保存";
VUHDO_I18N_DELETE = "刪除";
VUHDO_I18N_APPLY = "應用";
VUHDO_I18N_VEHICLES = "載具";
VUHDO_I18N_ADDITIONAL_PANELS = "附加面板";
VUHDO_I18N_UNSORT = "不排序";
VUHDO_I18N_ROLES = "職責";
VUHDO_I18N_CLASSES = "職業";
VUHDO_I18N_GROUPS = "隊伍";
VUHDO_I18N_MAIN_PANEL = "主面板";
VUHDO_I18N_PARTY = "隊伍";
VUHDO_I18N_PET = "寵物";
VUHDO_I18N_TARGET = "目標";
VUHDO_I18N_HIDE_STANDARD = "界面隱藏";
VUHDO_I18N_PLAYER_TARGET = "玩家目標";
VUHDO_I18N_SINGLE = "單一";
VUHDO_I18N_MULTI = "多個";
VUHDO_I18N_HOT_TARGETING = "HoT監視";
VUHDO_I18N_OR_ENTER_SKIN_NAME = "...或輸入皮膚名稱";
VUHDO_I18N_SELECT_A_SKIN = "選擇皮膚";
VUHDO_I18N_SKIN = "皮膚";
VUHDO_I18N_COLORS_FONTS = "(顏色/字體)";
VUHDO_I18N_ARRANGEMENT = "佈局";
VUHDO_I18N_SELECT_AN_ARRANGEMENT = "選擇佈局";
VUHDO_I18N_OR_ENTER_ARRANGEMENT_NAME = "...或輸入佈局名稱";
VUHDO_I18N_GROUPS_SIZES = "(組/大小)";
VUHDO_I18N_SYMBOL = "標記";
VUHDO_I18N_TOP_BAR = "仇恨條";
VUHDO_I18N_MONITOR_THREAT = "仇恨監視";
VUHDO_I18N_USE_ADD_BAR = "使用附加仇恨條";
VUHDO_I18N_LINE = "劃線";
VUHDO_I18N_LEFT = "左";
VUHDO_I18N_RIGHT = "右";
VUHDO_I18N_CHECK_FOR_AGGRO = "獲得仇恨監視";
VUHDO_I18N_CURR = "當前.";
VUHDO_I18N_BAR_COLOR = "條顏色";
VUHDO_I18N_PLUS_BG = "+背景";
VUHDO_I18N_INV_GROWTH = "Inv.Growth";
VUHDO_I18N_VERTICAL = "豎";
VUHDO_I18N_RAID_ICON = "團隊標記";
VUHDO_I18N_YOU_FIRST = "第一個顯示你";
VUHDO_I18N_IICONSI = "[圖標]";
VUHDO_I18N_ISQUARESI = "[方形]";
VUHDO_I18N_HOT_ORDER = "HoT排序";
VUHDO_I18N_SLOT_5 = "位置5 (多數不顯示)";
VUHDO_I18N_SLOT_4 = "位置4";
VUHDO_I18N_SLOT_3 = "位置3";
VUHDO_I18N_SLOT_2 = "位置2";
VUHDO_I18N_SLOT_1 = "位置1 (基本都顯示)";
VUHDO_I18N_TEXT_POSITION = "文本位置";
VUHDO_I18N_FLAGS = "標記";
VUHDO_I18N_SHOW_TEXT = "顯示文本";
VUHDO_I18N_KEYS = "按鍵設置";
VUHDO_I18N_SPEC_2 = "配置2";
VUHDO_I18N_SPEC_1 = "配置1";
VUHDO_I18N_MANAGE_KEYS = "管理按鍵配置";
VUHDO_I18N_INSTANT_2 = "替換2";
VUHDO_I18N_INSTANT_1 = "替換1";
VUHDO_I18N_TRINKET_2 = "飾品2";
VUHDO_I18N_TRINKET_1 = "飾品1";
VUHDO_I18N_TRIGGER_WHAT = "觸發...";
VUHDO_I18N_ALSO_OUT_FIGHT = "非戰斗狀態";
VUHDO_I18N_ALSO_HOTS = "HoTs類技能";
VUHDO_I18N_KEEP_STANCE = "保持姿態";
VUHDO_I18N_AUTO_TRIGGER = "自動觸發";
VUHDO_I18N_SPELL_ADVICE = "使用WOW標準按鍵綁定設置為以下法術分配按鍵. (滾動至'VuhDo'下.)";
VUHDO_I18N_SAVE_AS = "另存為...";
VUHDO_I18N_MOVE = "移動！";
VUHDO_I18N_SPELLS = "法術";
VUHDO_I18N_PANELS = "面板";
VUHDO_I18N_BUFFS = "增益";

VUHDO_I18N_ICON_SCALE = "圖標縮放";
VUHDO_I18N_THICKNESS = "邊框粗細";
VUHDO_I18N_WARNING_COLOR_AT = "警戒線";
VUHDO_I18N_THREAT_BAR_HEIGHT = "仇恨條高度";
VUHDO_I18N_REFRESH_AGGRO = "獲得仇恨監視器刷新率";
VUHDO_I18N_PANEL_SCALE = "面板縮放";
VUHDO_I18N_MAX_CHARS = "最大人物數(0=全部)";

-- #+v1.94
VUHDO_I18N_DEFAULT_RES_ANNOUNCE = "復活吧,我的勇士!";

-- #v+1.151
VUHDO_I18N_MAIN_ASSISTS = "協助坦克";

--VUHDO_OPTIONS_FONT_NAME = "Interface\\AddOns\\VuhDo\\Fonts\\ariblk.ttf";
VUHDO_OPTIONS_FONT_NAME = GameFontNormal:GetFont();

-- #v+1.169

VUHDO_I18N_ANOUNCE_RESURRECTION = "復活通知";
VUHDO_I18N_FOCUS = "焦點";
VUHDO_I18N_BUFF = "增益";
VUHDO_I18N_OTHERS = "其他";
VUHDO_I18N_LIFE_TEXT = "生命值文本";
VUHDO_I18N_EXTRA_TEXT = "Extra Text";
VUHDO_I18N_FRAME = "框體";
VUHDO_I18N_1 = " 1";
VUHDO_I18N_2 = " 2";
VUHDO_I18N_3 = " 3";
VUHDO_I18N_4 = " 4";
VUHDO_I18N_5 = " 5";
VUHDO_I18N_6 = " 6";
VUHDO_I18N_7 = " 7";
VUHDO_I18N_8 = " 8";
VUHDO_I18N_10 = " 10";
VUHDO_I18N_25 = " 25";
VUHDO_I18N_40 = " 40";
VUHDO_I18N_NUM_TRIANGLES = "# /三角形";
VUHDO_I18N_DEBUFF_DEFAULTS = "增、減益默認";
VUHDO_I18N_O_REALLY = "O'確定嘛?";
VUHDO_I18N_ITEXTUREI = "[材質]";
VUHDO_I18N_BAR = "條";
VUHDO_I18N_HOTS_2 = "HoTs #2";
VUHDO_I18N_PET_CLASS = "寵物顏色";
VUHDO_I18N_CLASS_COLORS = "職業顏色";
VUHDO_I18N_HOT_CHARGES = "HoT次數";
VUHDO_I18N_TEXT_COLOR = "文本顏色";
VUHDO_I18N_BACK_COLOR = "背景顏色";
VUHDO_I18N_HOT_BARS = "HoT條";
VUHDO_I18N_OUTLINE = "輪廓";
VUHDO_I18N_SHADOW = "陰影";
VUHDO_I18N_WARNING = "警告";
VUHDO_I18N_MISC_TEXT = "雜項.文本";
VUHDO_I18N_EXPIRY_WARNING = "期滿警告";
VUHDO_I18N_COUNTDOWN_OFF = "倒計時: 關";
VUHDO_I18N_SECS = "秒";
VUHDO_I18N_SECS_10 = "0.1秒";
VUHDO_I18N_FULL_DURATION = "滿持續時間";
VUHDO_I18N_TOOLS = "工具";
VUHDO_I18N_TIMER = "計時器";
VUHDO_I18N_DEBUFF_OPTIONS = "增、減益選項";
VUHDO_I18N_SOUND = "聲音";
VUHDO_I18N_STORE_DELETE = "保存/刪除";
VUHDO_I18N_DEBUFF_SOUND = "減益聲音";
VUHDO_I18N_MOUSE_UP = "鼠標鬆開";
VUHDO_I18N_REACTION_ON = "對...做出反應";
VUHDO_I18N_TOOLTIP_TYPE = "工具提示類型";
VUHDO_I18N_BAR_BORDER = "條邊框";
VUHDO_I18N_UNIT = "單元";
VUHDO_I18N_MOUSE_OVER_HIGH = "鼠標滑過高亮";
VUHDO_I18N_FLOAT = "浮動";
VUHDO_I18N_SOLIDD = "固定";
VUHDO_I18N_HORIZONTAL = "水平";
VUHDO_I18N_SLOT_1_2 = "Slot 1";
VUHDO_I18N_INVERT_X = "Invert X";
VUHDO_I18N_INVERT_Y = "Invert Y";
VUHDO_I18N_FLAT_TEXTURE = "平滑材質";
VUHDO_I18N_HOT_ICONS = "HoT圖標";
VUHDO_I18N_TARGET_OF_TARGET = "目標的目標";
VUHDO_I18N_VERBOSE = "Verbose";
VUHDO_I18N_1_DOT = "1.";
VUHDO_I18N_2_DOT = "2.";
VUHDO_I18N_3_DOT = "3.";
VUHDO_I18N_4_DOT = "4.";
VUHDO_I18N_5_DOT = "5.";
VUHDO_I18N_6_DOT = "6.";
VUHDO_I18N_7_DOT = "7.";
VUHDO_I18N_8_DOT = "8.";
VUHDO_I18N_9_DOT = "9.";
VUHDO_I18N_10_DOT = "10.";
VUHDO_I18N_11_DOT = "11.";
VUHDO_I18N_12_DOT = "12.";
VUHDO_I18N_13_DOT = "13.";
VUHDO_I18N_14_DOT = "14.";
VUHDO_I18N_15_DOT = "15.";
VUHDO_I18N_16_DOT = "16.";
VUHDO_I18N_KEY_BINDINGS = "按鍵綁定";
VUHDO_I18N_MOUSE_WHEEL = "鼠標滑輪";
VUHDO_I18N_TOOLTIP_INFO = "提示工具信息";
-- Slider
VUHDO_I18N_BACKG_BRIGHTNESS = "背景亮度";
VUHDO_I18N_WARN_PREC_AT = "警告/偵測……";
VUHDO_I18N_MAX_NO_DE_BUFFS = "最大增、減益數量";
VUHDO_I18N_BRIGHTNESS = "亮度";
VUHDO_I18N_RAID_ICON_SCALE = "團隊標記縮放";
VUHDO_I18N_NAME_TEXT_SIZE = "名字文本縮放";
VUHDO_I18N_LIFE_TEXT_SIZE = "生命值文本縮放";
-- Color swatches
VUHDO_I18N_BUFF_OKAY = "Buff良好";
VUHDO_I18N_BUFF_LOW = "Buff持續時間低";
VUHDO_I18N_BUFF_MISSING = "Buff正在消失";
VUHDO_I18N_OUT_OF_RANGE = "超出距離";
VUHDO_I18N_COOLDOWN = "冷卻";
VUHDO_I18N_EMPTY_GROUP = "空小隊";
VUHDO_I18N_PANEL_BACKGROUND = "面板背景";
VUHDO_I18N_SWATCH_BORDER = "Swatch Border";
VUHDO_I18N_PANEL_BORDER = "面板邊界";
VUHDO_I18N_2ND_CHARGE = "第二跳";
VUHDO_I18N_3RD_CHARGE = "第三跳";
VUHDO_I18N_4TH_CHARGE = "第四跳";
VUHDO_I18N_BAR_1 = "條1";
VUHDO_I18N_BAR_2 = "條2";
VUHDO_I18N_BAR_3 = "條3";
VUHDO_I18N_SQUARE_1 = "方塊1";
VUHDO_I18N_SQUARE_2 = "方塊2";
VUHDO_I18N_SQUARE_3 = "方塊3";
VUHDO_I18N_SQUARE_4 = "方塊4";
VUHDO_I18N_SQUARE_5 = "方塊5";
VUHDO_I18N_EMERGENCY = "緊急";
VUHDO_I18N_NO_EMEGENCY = "不緊急";
VUHDO_I18N_IRRELEVANT = "無關";
VUHDO_I18N_INCOMING = "輸入";
VUHDO_I18N_MANA = "法力";
VUHDO_I18N_RAGE = "怒氣";
VUHDO_I18N_ENERGY = "能量";
VUHDO_I18N_RUNES = "符文";
VUHDO_I18N_DEAD = "死亡";
VUHDO_I18N_OFFLINE = "離線";
VUHDO_I18N_CHARMED = "被控制";
VUHDO_I18N_AGGRO_BAR = "仇恨目標條";
VUHDO_I18N_PLAYER_TARGET = "玩家目標";
VUHDO_I18N_BAR_FRAME = "條框體";
VUHDO_I18N_POISON = "毒";
VUHDO_I18N_DISEASE = "疾病";
VUHDO_I18N_CURSE = "詛咒";
VUHDO_I18N_MAGIC = "魔法";
VUHDO_I18N_HEADER = "標題";
VUHDO_I18N_BORDER = "邊界";

VUHDO_I18N_ICON_SCALE = "圖標縮放";
VUHDO_I18N_THICKNESS = "邊框粗細";
VUHDO_I18N_WARNING_COLOR_AT = "警戒線";
VUHDO_I18N_THREAT_BAR_HEIGHT = "仇恨條高度";
VUHDO_I18N_REFRESH_AGGRO = "獲得仇恨監視器刷新率";
VUHDO_I18N_PANEL_SCALE = "面板縮放";
VUHDO_I18N_MAX_CHARS = "最大人物數(0=全部)";


-- #+v1.178
VUHDO_I18N_HOSTILE = "敵對";
VUHDO_I18N_HOSTILE_TITLE = "[敵對]";
VUHDO_I18N_HOSTILE_ADVICE_1 = "輸入法術名稱或目標/焦點/協助"
VUHDO_I18N_HOSTILE_ADVICE_2 = "不要輸入巨集名稱或者其他東西！！！"
VUHDO_I18N_HOSTILE_ADVICE_3 = "飾品/瞬發技能不會自動觸發/施放！！！"


-- Slider
VUHDO_I18N_BACKG_BRIGHTNESS = "背景亮度";
VUHDO_I18N_WARN_PREC_AT = "警告/偵測……";
VUHDO_I18N_MAX_NO_DE_BUFFS = "最大增、減益數量";
VUHDO_I18N_DEBUFF_SOUND = "減益聲音";
VUHDO_I18N_RAID_ICON_SCALE = "團隊標記縮放";
VUHDO_I18N_NAME_TEXT_SIZE = "名字文本縮放";
VUHDO_I18N_LIFE_TEXT_SIZE = "生命值文本縮放";
-- Color swatches
VUHDO_I18N_OUT_OF_RANGE = "超出距離";
VUHDO_I18N_COOLDOWN = "冷卻";
VUHDO_I18N_EMPTY_GROUP = "空小隊";
VUHDO_I18N_PANEL_BACKGROUND = "面板背景";
VUHDO_I18N_SWATCH_BORDER = "Swatch Border";
VUHDO_I18N_PANEL_BORDER = "面板邊界";
VUHDO_I18N_2ND_CHARGE = "第二跳";
VUHDO_I18N_3RD_CHARGE = "第三跳";
VUHDO_I18N_4TH_CHARGE = "第四跳";
VUHDO_I18N_BAR_1 = "條1";
VUHDO_I18N_BAR_2 = "條2";
VUHDO_I18N_BAR_3 = "條3";
VUHDO_I18N_SQUARE_1 = "方塊1";
VUHDO_I18N_SQUARE_2 = "方塊2";
VUHDO_I18N_SQUARE_3 = "方塊3";
VUHDO_I18N_SQUARE_4 = "方塊4";
VUHDO_I18N_SQUARE_5 = "方塊5";
VUHDO_I18N_EMERGENCY = "緊急";
VUHDO_I18N_NO_EMEGENCY = "不緊急";
VUHDO_I18N_IRRELEVANT = "無關";
VUHDO_I18N_INCOMING = "輸入";
VUHDO_I18N_MANA = "法力";
VUHDO_I18N_RAGE = "怒氣";
VUHDO_I18N_ENERGY = "能量";
VUHDO_I18N_RUNES = "符文";
VUHDO_I18N_DEAD = "死亡";
VUHDO_I18N_OFFLINE = "離線";
VUHDO_I18N_CHARMED = "被控制";
VUHDO_I18N_AGGRO_BAR = "仇恨目標條";
VUHDO_I18N_PLAYER_TARGET = "玩家目標";
VUHDO_I18N_BAR_FRAME = "條框體";
VUHDO_I18N_POISON = "毒";
VUHDO_I18N_DISEASE = "疾病";
VUHDO_I18N_CURSE = "詛咒";
VUHDO_I18N_MAGIC = "魔法";
VUHDO_I18N_HEALTH_BAR = "血條";
VUHDO_I18N_HEADER = "標題";
VUHDO_I18N_AUTO_ENABLE = "超過X名玩家時自動開啟:";

-- #+1.197
VUHDO_I18N_EDGE_SIZE = "邊緣縮放";
VUHDO_I18N_EDGE_INSETS = "Edge Insets";

-- #+1.203
VUHDO_I18N_SWAP_WHEN_DEBUFFED = "Swap Debuff";

-- #+1.204
VUHDO_I18N_IGNORE_PETS = "忽略寵物";
VUHDO_I18N_PANEL_MODEL = "面板模型";

-- #+1.207
VUHDO_I18N_OVERHEAL_TEXT = "過量治療文字";

-- #+1.210
VUHDO_I18N_NO_STACKS = "堆疊: 關閉";
VUHDO_I18N_NUMBER_STACKS = "文字";
VUHDO_I18N_TRIANGLE_STACKS = "三角形";
VUHDO_I18N_HIDE_PANELS = "隱藏面板";
VUHDO_I18N_SOLO = "單人";

VUHDO_I18N_CLICK_THROUGH = "+ 不點擊";
VUHDO_I18N_IHEALTH_BARI = "[血條]";
VUHDO_I18N_SLOT_6 = "位置6";
VUHDO_I18N_SQUARE_6 = "方塊6";
VUHDO_I18N_GLOSSY = "光澤";
VUHDO_I18N_DAMAGE_FLASH = "伤害闪烁";
VUHDO_I18N_SENSIVITY = "灵敏度";
VUHDO_I18N_HIDE_IRRELEVANT = "Hide irrel.";
VUHDO_I18N_LOAD_HOTS = "读取HoTs";
VUHDO_I18N_CASTED = "直接";
VUHDO_I18N_CHANNELLED = "引導";
VUHDO_I18N_BOMBED = "爆發";
VUHDO_I18N_EVENT_HORIZON = "事件視界";
VUHDO_I18N_ALGINMENT = "對齊";
VUHDO_I18N_BOTTOM = "底部";
VUHDO_I18N_PET_OWNERS = "寵物主人";
VUHDO_I18N_BATTLE_REZ = "戰复";


-- #+1.232
VUHDO_I18N_DEBUFF_LIST = "(De)Buff List";
VUHDO_I18N_DEBUFF_EDIT_BOX = "鍵入新增/減益名稱";

-- #+1.233
VUHDO_I18N_BUTTON_6 = "按鍵 6";
VUHDO_I18N_BUTTON_7 = "按鍵 7";
VUHDO_I18N_BUTTON_8 = "按鍵 8";
VUHDO_I18N_BUTTON_9 = "按鍵 9";
VUHDO_I18N_BUTTON_10 = "按鍵 10";
VUHDO_I18N_BUTTON_11 = "按鍵 11";
VUHDO_I18N_BUTTON_12 = "按鍵 12";
VUHDO_I18N_BUTTON_13 = "按鍵 13";
VUHDO_I18N_BUTTON_14 = "按鍵 14";
VUHDO_I18N_BUTTON_15 = "按鍵 15";
VUHDO_I18N_BUTTON_16 = "按鍵 16";
VUHDO_I18N_TANK_MODE = "坦克模式";


-- #+1.237
VUHDO_I18N_CLUSTER_SCANNER = "聚團監視";
VUHDO_I18N_CLUSTER_PARAMS = "聚團參數";
VUHDO_I18N_FAIR_THRESHOLD = "一般臨界值";
VUHDO_I18N_GOOD_THRESHOLD = "良好臨界值";
VUHDO_I18N_SOURCE_SPELL = "法術源";
VUHDO_I18N_SOURCE_MINE = "玩家";
VUHDO_I18N_SOURCE_ALL = "目標";
VUHDO_I18N_DEST_SPELL = "Spell Destination";
VUHDO_I18N_DEST_RAID = "團隊";
VUHDO_I18N_DEST_PARTY = "小隊";
VUHDO_I18N_CLUSTERS = "聚團者";
VUHDO_I18N_LOW = "低";
VUHDO_I18N_FAIR = "一般";
VUHDO_I18N_GOOD = "良好";
VUHDO_I18N_HEALTH_LEVEL = "血量水平 <";
VUHDO_I18N_CLUSTER_FINDER = "揪出聚團者";
VUHDO_I18N_OTHER_HOTS = "其他玩家的HOTS";
VUHDO_I18N_EMPTY_HOTS = "空";
VUHDO_I18N_MOUSE_HOVER = "Mouse Hover";
VUHDO_I18N_COUNTER = "計數器";
VUHDO_I18N_GLOBAL_COOLDOWN = "公共冷卻";
VUHDO_I18N_GCD = "公共冷卻";

-- #+1.238
VUHDO_I18N_DISPLAY_OPTIONS = "顯示選項";
VUHDO_I18N_RADIAL = "徑向";
VUHDO_I18N_CHAINED = "連鎖的";
VUHDO_I18N_CHAINED_MAX_JUMP = "最大跳躍次數";
VUHDO_I18N_TIMES = " 次數";
VUHDO_I18N_SOURCE_DESTINATION = "Source/Destination";

VUHDO_I18N_HIGH = "高";


-- #+1.251
VUHDO_I18N_15 = " 15";
VUHDO_I18N_LOAD_HOTS = "Load HoTs";
VUHDO_I18N_IGNORE_LIST = "Ignore List";
VUHDO_I18N_FIVE_MAN_MTS = "5 man MTs";
VUHDO_I18N_FILTER_ONLY = "Filter only";
VUHDO_I18N_LIFE_COLORS = "Life colors";
VUHDO_I18N_SMART_WHEEL = "Smart Wheel";
VUHDO_I18N_PASTE = "Paste";
VUHDO_I18N_COPY = "Copy";

-- #+1.252
VUHDO_I18N_BOUQUETS = "Bouquets";
VUHDO_I18N_SELECT_OR_ENTER_BOUQUET = "Select a Bouquet ...";
VUHDO_I18N_NEW = "New";
VUHDO_I18N_BOUQUET_DETAILS = "Bouquet Details";
VUHDO_I18N_HIGHEST_PRIO = "Highest Priority";
VUHDO_I18N_LOWEST_PRIO = "Lowest Priority";
VUHDO_I18N_ITEM_DETAILS = "Item Details";
VUHDO_I18N_ENTER_DE_BUFF_OR_SPECIAL = "Select special event ...";
VUHDO_I18N_ITEM = "Item";
VUHDO_I18N_SELECT_DEFAULT_ICON = "Select default icon";
VUHDO_I18N_MINE = "Mine";
VUHDO_I18N_GRADIENT = "Gradient";
VUHDO_I18N_INDICATORS = "Indicators";

VUHDO_I18N_COPIED_BOUQUET = "Copied bouquet ";
VUHDO_I18N_BOUQUET_ALREADY_EXISTS = ": Bouquet already exists. Type new name first.";
VUHDO_I18N_CREATED_NEW_BOUQUET = "Created new Bouquet: ";
VUHDO_I18N_DELETED_BOUQUET = "Deleted bouquet: ";
VUHDO_I18N_BOUQUET_NOT_FOUND = ": No such bouquet found.";
VUHDO_I18N_SELECT_STORE_BOUQUET_FIRST = "Select bouquet first";
VUHDO_I18N_SELECT_ITEM_FIRST = "Select an item to remove first.";
VUHDO_I18N_SELECT_A_PROFILE = "Select a profile";
VUHDO_I18N_PROFILES = "Profiles";
VUHDO_I18N_EDIT_BUTTON = "Edit...";
VUHDO_I18N_MORE_BUTTON = "More...";
VUHDO_I18N_DONE_BUTTON = "Done";
VUHDO_I18N_BASIC = "Basic";
VUHDO_I18N_ADVANCED = "Advanced";
VUHDO_I18N_EXPERT = "Expert";
VUHDO_I18N_COMPACT = "Compact";

VUHDO_I18N_REALLY_DELETE_PROFILE = "Really delete profile";
VUHDO_I18N_MUST_ENTER_SELECT_PROFILE = "You must enter/select a name first.";
VUHDO_I18N_DELETED_PROFILE = "Successfully deleted profile";

VUHDO_I18N_TURN_AXIS = "Turn Axis";

VUHDO_I18N_OR_NEW_BOUQUET_NAME = "... or new Bouquet name";
VUHDO_I18N_OR_ENTER_DEBUFF_HOT = "... or enter Buff / Debuff / HoT name";
VUHDO_I18N_TALENT_TREES = "Talent trees";
VUHDO_I18N_SCAN = "Scan";
VUHDO_I18N_INFINITE = "Infinite";
VUHDO_I18N_SAME_ZONE = "Same Zone";
VUHDO_I18N_100_YARDS = "100 yards";
VUHDO_I18N_40_YARDS = "40 yards";
VUHDO_I18N_LIFE_TEXT = "Life Text";
VUHDO_I18N_BACK = "Back";

VUHDO_I18N_OR_NEW_BOUQUET_NAME = "... or new Bouquet name";
VUHDO_I18N_OR_ENTER_DEBUFF_HOT = "... or enter Buff / Debuff / HoT name";
VUHDO_I18N_TALENT_TREES = "Talent trees";
VUHDO_I18N_SCAN = "Scan";
VUHDO_I18N_INFINITE = "Infinite";
VUHDO_I18N_SAME_ZONE = "Same Zone";
VUHDO_I18N_100_YARDS = "100 yards";
VUHDO_I18N_40_YARDS = "40 yards";
VUHDO_I18N_LIFE_TEXT = "Life Text";
VUHDO_I18N_BACK = "Back";

VUHDO_I18N_CLIQUE_COMPAT_MODE = "Clique support";
VUHDO_I18N_RESET = "Reset";
VUHDO_I18N_DEBUFF_COLORS = "Debuff Colors";
VUHDO_I18N_BUFFS_HOTS = "Buffs/HoTs";
VUHDO_I18N_BUFF_WATCH = "Buff Watch";
VUHDO_I18N_CUSTOM_DEBUFFS = "Custom Debuffs";
VUHDO_I18N_DEFAULT_BOUQUETS = "Default Bouquets";
VUHDO_I18N_EVERYTHING = "Everything";
VUHDO_I18N_LANGUAGE = "Language";
VUHDO_I18N_PANEL_POSITIONS = "Panel Positions";
VUHDO_I18N_PER_PANEL_SETTINGS = "per Panel Settings";
VUHDO_I18N_MINUTE = "min.";
VUHDO_I18N_MSEC = "msec";
VUHDO_I18N_PEOPLE = " people";
VUHDO_I18N_RESET_CLASS_COLORS = "This will reset your custom\nCLASS COLOR settings. Proceed?" ;
VUHDO_I18N_RESET_DEBUFF_COLORS = "This will reset your custom\nDEBUFF COLOR settings. Proceed?";
VUHDO_I18N_RESET_RAID_ICON_COLORS = "This will reset your custom\nRAID TARGET COLOR settings. Proceed?";
VUHDO_I18N_RESET_BUFF_WATCH = "This will reset all your\nBUFF WATCH settings. Proceed?";
VUHDO_I18N_RESET_CUSTOM_DEBUFFS = "This will reset all your\nCUSTOM DEBUFFs + settings. Proceed?";
VUHDO_I18N_RESET_DEFAULT_BOUQUETS = "This will reset all \nDEFAULT (not: custom) BOUQUETS. Proceed?";
VUHDO_I18N_RESET_INDICATORS = "This will reset your custom\nINDICATOR CONFIG. Proceed?";
VUHDO_I18N_RESET_ALL = "!!!WARNING: This will RESET THE WHOLE\nADDON to factory defaults!!! Proceed?" ;
VUHDO_I18N_RESET_LANGUAGE = "This will reset all settings after client\nlanguage change (Heavy STUFF!!!). Proceed?";
VUHDO_I18N_RESET_PANEL_POSITIONS = "This will reset your\npanel positions. Proceed?";
VUHDO_I18N_RESET_PER_PANEL_SETTINGS = "This will reset your\nper-panel setup. Proceed?";

-- 2.17
VUHDO_I18N_LOCK = "Lock";
VUHDO_I18N_QUIET_MODE = "Quiet Mode";
VUHDO_I18N_SETTINGS = "Settings";
VUHDO_I18N_ACTIVATE_DUE_GRP_SIZE = "Activate due to group size";
VUHDO_I18N_CUSTOM_HEALTH_BAR_BOUQUET = "Custom Health Bar Bouquet";
VUHDO_I18N_CUSTOM_SETTINGS = "Custom settings";
VUHDO_I18N_DISTANCE = "Distance";
VUHDO_I18N_DEAD_ONLY = "dead only";
VUHDO_I18N_DIRECTION = "Direction";
VUHDO_I18N_IF_OOR_SHOW = "If unit is out of range show...";
VUHDO_I18N_DEBUFF_NAME = "Debuff Name";
-- 2.18
VUHDO_I18N_DISABLE = "Disable";
VUHDO_I18N_DC_RESTORE = "D/C Restore";
VUHDO_I18N_EXPORT_CUSTOM_DEBUFFS = "Export Custom Debuffs";
VUHDO_I18N_EXPORT_TO_PROFILE = "Export to profile:";
VUHDO_I18N_THIS_TOONS = "This Toon's";
VUHDO_I18N_SELECTED = "Selected";
VUHDO_I18N_ALL = "All";
VUHDO_I18N_REPLACE = "Replace";
