if (GetLocale() ~= "deDE") then
	return;
end

-- New Options
-- @EXACT = false
VUHDO_I18N_SCANNERS = "Scanner";
VUHDO_I18N_RESURRECT_SHORT = "Wiederbel.";
VUHDO_I18N_GENERAL = "Allgemein";
VUHDO_I18N_CONFIG = "Konfig";
VUHDO_I18N_REBUFF = "Re-Buff";
VUHDO_I18N_FORMAT = "Format";
VUHDO_I18N_BUFF_NAMES = "Buff Namen";
VUHDO_I18N_EMPTY_GROUPS = "auch leere";
VUHDO_I18N_STATES = "Zustände";
VUHDO_I18N_CD_FLASHING = "CD-Blinken";
VUHDO_I18N_TIMERS = "Timers";
VUHDO_I18N_WHATEVER_FIRST = "...oder...(was zuerst kommt)";
VUHDO_I18N_SMART_DOTS = "Smart...";
VUHDO_I18N_GROUP_BUFFS = "Gruppenbuffs";
VUHDO_I18N_MODES = "Modi";
VUHDO_I18N_EMERGENCY_MODE = "Notfallmodus";
VUHDO_I18N_NORMAL_MODE = "Normalmodus";
VUHDO_I18N_DETECT = "Prüfen";
VUHDO_I18N_RANGE = "Reichweite";
VUHDO_I18N_ADD_NEW_PANEL = "Neues Fenster";
VUHDO_I18N_HOLD_TO_TEST = "Gedrückt halten";
VUHDO_I18N_OWN_HOTS = "Eigene HoTs";
VUHDO_I18N_BAR_TEXTURE = "Balkentextur";
VUHDO_I18N_OTHER_POWERS = "Sonstige";
VUHDO_I18N_MANA_BARS = "Mana-Balken";
VUHDO_I18N_LOSE = "frei";
VUHDO_I18N_ORDERING = "Anordnung";
VUHDO_I18N_HIDE_EMPTY = "Keine leeren";
VUHDO_I18N_ANCHOR = "Ankerpunkt";
VUHDO_I18N_UNIT_ID = "Unit ID";
VUHDO_I18N_HEADER_TEXT = "Spaltentext";
VUHDO_I18N_TOOLTIPS = "Tooltips";
VUHDO_I18N_SIZING = "Größeneinst.";
VUHDO_I18N_BUTTON_SIZE = "Buttongröße";
VUHDO_I18N_TARGET_NAME = "Name des Ziels";
VUHDO_I18N_PERCENT = "Prozent";
VUHDO_I18N_MISSING = "Fehlend";
VUHDO_I18N_REMAINING = "Verbleibend";
VUHDO_I18N_HITPOINTS = "Hitpoints";
VUHDO_I18N_BAR_TEXT = "Balkentext";
VUHDO_I18N_MAX_SWATCHES_PER_LINE = "Max.Buttons/Zeile";
VUHDO_I18N_MAX_BUFFS_PER_ROW = "Max.Buffs/Spalte";
VUHDO_I18N_REFRESH_RATE = "Aktualisierungsrate";
VUHDO_I18N_INDICATE_REBUFF_BELOW = "Neu buffen unter";
VUHDO_I18N_IF_AT_LEAST = "... wenn mind.";
VUHDO_I18N_PLAYERS_LOW = " Spieler low.";
VUHDO_I18N_SIZE = "Größe";
VUHDO_I18N_TEXTURE_NUM = "Textur #";
VUHDO_I18N_TEXT_SIZE = "Textgröße";
VUHDO_I18N_X_SPACING = "Abstand X";
VUHDO_I18N_Y_SPACING = "Abstand Y";
VUHDO_I18N_X_GAP = "Rand X";
VUHDO_I18N_Y_GAP = "Rand Y";

-- General Labels
-- @EXACT = false
VUHDO_I18N_CANCEL = "Abbruch";
VUHDO_I18N_SHOW = "Anzeigen";
VUHDO_I18N_BARS = "Balken"
VUHDO_I18N_COLOR = "Farbe";
VUHDO_I18N_COLORS = "Farben";
VUHDO_I18N_GENERAL_SHORT = "Allgem.";
VUHDO_I18N_CUSTOM = "Eigene";
VUHDO_I18N_MOUSE = "Maus";
VUHDO_I18N_STANDARD = "Standard";
VUHDO_I18N_POSITION = "Position";
VUHDO_I18N_SCALE = "Größe";
VUHDO_I18N_ENABLE = "Aktiviert";
VUHDO_I18N_BACKGROUND = "Hintergrund";
VUHDO_I18N_GROUPED = "ordnen";
VUHDO_I18N_SORT_BY = "Sortierung...";
VUHDO_I18N_NAME = "Name";
VUHDO_I18N_MAX_HP = "Max HP";
VUHDO_I18N_MAX_COLUMNS = "max. Spalten";
VUHDO_I18N_MAX_ROWS = "max. Zeilen";
VUHDO_I18N_CLEAR_PANELS_CONFIRM = "Modelle des Panels leeren!\nYA'RLY?";
VUHDO_I18N_BUFF_NAME = "Buff-Name";
VUHDO_I18N_BUFF_ON_PLAYER = "auf Spieler mit Namen:";
VUHDO_I18N_ALWAYS = "Immer";
VUHDO_I18N_NEVER = "Niemals";
VUHDO_I18N_BUFF_PANEL_BG = "Fenster";



-- VuhDoOptionsGeneral.lua
-- @EXACT = false
VUHDO_I18N_CLEANSE = "Reinigen";
VUHDO_I18N_RESURRECT = "Wiederbeleben";
VUHDO_I18N_SMART_CAST_OO_COMBAT = "Smart Cast";
VUHDO_I18N_IGNORE_IRRELEVANT = "Ignoriere bedeutungslose ...";
VUHDO_I18N_BY_CLASS = "Klasse";
VUHDO_I18N_MOVEMENT_IMPAIRING = "Bewegung";
VUHDO_I18N_BY_DURATION = "Dauer";
VUHDO_I18N_BY_NON_HARMFUL = "unschädliche";
VUHDO_I18N_SHOW_ALL = "Show All";
VUHDO_I18N_ESTIMATE = "Schätze";
VUHOD_I18N_BY_SPELL = "Spruch";
VUHDO_I18N_SHOW_INC = "Eingehende Heilung";
VUHDO_I18N_SHOW_OWN_HEAL = "Eigene";
VUHDO_I18N_SHOW_OVERHEAL = "Überheilung";
VUHDO_I18N_OPERATION_MODE = "Betriebsmodus";
VUHDO_I18N_MAX_EMERGENCIES = "max. # Notfälle";
VUHDO_I18N_RELVEVANCE = "Irrelevant über";
VUHDO_I18N_NEUTRAL_HEALBOT = "Neutral";
VUHDO_I18N_EMERGENCY_PERCENT = "Notfall - HP %";
VUHDO_I18N_EMERGENCY_MOST_MISSING = "Meiste HP fehlend";
VUHDO_I18N_EMERGENCY_LEAST_LEFT = "Wenigste HP übrig";


-- VuhDoFormButtonColor.lua
-- @EXACT = false
-- Labels
VUHDO_I18N_TEXT = "Text";
VUHDO_I18N_DEBUFFS = "Debuffs";
VUHDO_I18N_ANOMALIES = "Anomalien";
VUHDO_I18N_OPACITY = "Opazität";



-- VuhDoFormButtonSize.lua
-- @EXACT = false
VUHDO_I18N_PANEL = "Panel";
VUHDO_I18N_SPACING = "Abstand";
VUHDO_I18N_BAR_HEIGHT = "Balkenhöhe";
VUHDO_I18N_TARGETS = "Ziele";
VUHDO_I18N_BAR_TEXTURE = "Balken-Textur";
VUHDO_I18N_HEIGHT = "Höhe";
VUHDO_I18N_BAR_WIDTH = "Balkenbreite";
VUHDO_I18N_WIDTH = "Breite";
VUHDO_I18N_HEADERS = "Titel";
VUHDO_I18N_CLASS_COL = "Klassenf.";
--



-- VuhDoOptionsSpell.lua
-- @EXACT = false
VUHDO_I18N_KEY_MODIFIES = "Modifikationstaste";
VUHDO_I18N_KEY_NONE = "keine";
VUHDO_I18N_ALT = "Alt";
VUHDO_I18N_CTRL = "Strg";
VUHDO_I18N_SHIFT = "Umschalt";
VUHDO_I18N_LEFT_BUTTON = "Linke Taste";
VUHDO_I18N_RIGHT_BUTTON = "Rechte Taste";
VUHDO_I18N_MIDDLE_BUTTON = "Mittlere Taste";
VUHDO_I18N_BUTTON_4 = "Taste 4";
VUHDO_I18N_BUTTON_5 = "Taste 5";
VUHDO_I18N_MOUSE_KEY = "Maustaste";
VUHDO_I18N_IN_MACROS_USE = "(in Makros \"vuhdo\" statt Spielernamen)";
VUHDO_I18N_SPELL_STATIC = "oder target/focus/assist/menu/tell/dropdown";
VUHDO_I18N_NAME_TIP = "Name eines Zaubers, Makros or Items,";
VUHDO_I18N_PLUS_SHIFT = "+Umschalt";
VUHDO_I18N_PLUS_CTRL_SHIFT = "+Strg+Umsch.";
VUHDO_I18N_PLUS_CTRL = "+Strg";


-- VuhDoTooltipConfig.lua
-- @EXACT = false
VUHDO_I18N_AROUND_PANEL = "Um Panel";
VUHDO_I18N_SHOW_IN_FIGHT = "im Kampf";


-- New Options - Tooltips
-- @EXACT = false
VUHDO_I18N_TT_001 = "Konfigurieren Sie, welche Buffs durch VuhDo verwaltet werden sollen.";
VUHDO_I18N_TT_002 = "Bestimmen Sie das generelle Aussehen der Buffanzeige.";
VUHDO_I18N_TT_003 = "Wählen Sie die Farben Ihrer Buffanzeige.";
VUHDO_I18N_TT_004 = "Nehmen Sie die Buff-Timer-Einstellungen vor und bestimmen Sie, wie gebufft werden soll.";

VUHDO_I18N_TT_005 = "Wählen Sie die Gesamtgrösse ihrer Buffanzeige.";
VUHDO_I18N_TT_006 = "Stellen Sie die maximale Anzahl von Buff-Kästchen pro Zeile ein.";
VUHDO_I18N_TT_007 = "Stellen Sie die maximale Zahl von angezeigten Buffs pro spalte ein.";
VUHDO_I18N_TT_008 = "Wählen Sie die Aktualisierungsrate der Buffanzeige.";
VUHDO_I18N_TT_009 = "Markieren Sie diese Option, um die Buff-Namen im Titel der Buffanzeige einzublenden.";
VUHDO_I18N_TT_010 = "Markeren Sie dieses Feld, um auch ggf. derzeit leere Buff-Gruppen anzuzeigen.";
VUHDO_I18N_TT_011 = "Wenn Sie dieses Feld markieren, aktivieren Sie die VuhDo Buff-Anzeige.";

VUHDO_I18N_TT_012 = "Wählen Sie eine Farbe für ausreichende Restdauer eines Buffs.";
VUHDO_I18N_TT_013 = "Wählen Sie eine Farbe für bald auslaufende Buffs.";
VUHDO_I18N_TT_014 = "Wählen Sie eine Farbe für (teilweise) fehlende Buffs.";
VUHDO_I18N_TT_015 = "Wählen Sie eine Farbe für den Fall, dass alle Buff-Ziele ausser Reichweite sind.";
VUHDO_I18N_TT_016 = "Wählen Sie eine Farbe, um anzuzeigen, dass der Buff aktuell Cooldown hat.";
VUHDO_I18N_TT_017 = "Wählen Sie eine Farbe, die anzeigt, dass die Buff-Gruppe derzeit leer ist.";
VUHDO_I18N_TT_018 = "Wählen Sie eine Farbe für den Fensterhintergrund.";
VUHDO_I18N_TT_019 = "Wählen Sie eine Farbe für den Rahmen der Buff-Kästchen.";
VUHDO_I18N_TT_020 = "Wählen Sie eine Farbe für den Rahmen des Buff-Fensters.";

VUHDO_I18N_TT_021 = "Wenn Sie dieses Feld aktivieren, werden Ihnen auslaufende Cooldowns durch mehrmaliges Blinken angezeigt.";
VUHDO_I18N_TT_022 = "Wählen Sie aus, bei welcher Buff-Restlaufzeit in Prozent, die Buff-Anzeige von \"grün\" auf \"gelb\" springen soll";
VUHDO_I18N_TT_023 = "Wählen Sie aus, bei welcher Buff-Restlaufzeit in Minuten, die Buff-Anzeige von \"grün\" auf \"gelb\" springen soll";
VUHDO_I18N_TT_024 = "Wählen Sie diese Option, um die Buff-Version von der Schieberegler-Einstellung unterhalb abhängig zu machen.";
VUHDO_I18N_TT_025 = "Wählen Sie diese Option, um stets die Einzel-Variante des Buffs zu benutzen (z.B., wenn Ihnen die nötigen Reagenzien ausgegangen sind)";
VUHDO_I18N_TT_026 = "Wählen Sie diese Options, wenn sie immer den Gruppen-Buff statt des Einzelbuffs verwenden wollen.";
VUHDO_I18N_TT_027 = "Stellen Sie ein, wieviele Gruppenmitglieder mindestens \"LOW\" sein müssen, bevor Sie den Gruppen- anstatt des Einzel-Buffs verwenden wollen.";

VUHDO_I18N_TT_028 = "Wählen Sie alle Farben, die den Zustand eines Spielers widergeben.";
VUHDO_I18N_TT_029 = "Wählen Sie Farben zum aktivierten Anzeigemodus.";

VUHDO_I18N_TT_031 = "Wählen Sie eine Farbe, die einen Notfall symbolisiert. (Hinweis: Wirkt nur bei aktiviertem Betriebsmodus \"Notfall\")";
VUHDO_I18N_TT_032 = "Wählen Sie eine Farbe, die einen NICHT-Notfall symbolisiert. (Hinweis: Wirkt nur bei aktiviertem Betriebsmodus \"Notfall\").";
VUHDO_I18N_TT_033 = "Wählen Sie eine Farbe für Spieler, die als irrelevant für Heilung gelten, weil sie noch zu viele Lebenspunkte haben. (Beachte: \"Irrelevant\"-Schieberegler in den generellen Fenster-Einstellungen)";
VUHDO_I18N_TT_034 = "Wählen Sie eine Farbe für eingehende Heilung. (Hinweis: Die Anzeige eingehender Heilung muss aktiviert sein.)";
VUHDO_I18N_TT_035 = "Wählen Sie eine Farbe für Spieler, die sich nicht in Reichweite befinden. (Hinweis: Die Reichweitenprüfung muss aktiviert sein.)";

VUHDO_I18N_TT_036 = "Wählen Sie eine Farbe, um anzuzeigen, dass die Spielfigur verschieden ist.";
VUHDO_I18N_TT_037 = "Wählen Sie eine Farbe für Spieler, die aktuell offline sind.";
VUHDO_I18N_TT_038 = "Wählen Sie eine Farbe für übernommene, d.h. fremdgesteuerte Spieler.";
VUHDO_I18N_TT_039 = "Wählen Sie eine Farbe für den Aggro-Balken unter dem Spielernamen.";
VUHDO_I18N_TT_040 = "Wählen Sie eine Farbe für vergiftete Spieler.";
VUHDO_I18N_TT_041 = "Wählen Sie eine Farbe für Spieler, die von einem Krankheit-Debuff betroffen sind.";
VUHDO_I18N_TT_042 = "Wählen Sie eine Farbe für verfluchte Spieler.";
VUHDO_I18N_TT_043 = "Wählen Sie eine Farbe für Spieler, die an einem Magie-Debuff leiden.";

VUHDO_I18N_TT_044 = "Nehmen Sie grundsätzliche VuhDo-Einstellungen vor.";
VUHDO_I18N_TT_045 = "Wählen Sie aus, welche besonderen Spielsituationen von VuhDo geprüft werden sollen.";

VUHDO_I18N_TT_046 = "Ausserhalb eines Kampfes soll VuhDo entscheiden, welcher Heilspruch der geeignetste ist.";
VUHDO_I18N_TT_047 = "Automatische Auswahl des Spruchrangs ausserhalb des Kampfes. (Sinnlos seit WoW V2.3x, da alle Ränge das selbe Mana kosten)";
VUHDO_I18N_TT_048 = "Automatisches Reinigen ausserhalb des Kampfes (Gift, Fluch etc.).";
VUHDO_I18N_TT_049 = "Automatische Wiederbelebung toter Spielfiguren ausserhalb des Kampfes.";
VUHDO_I18N_TT_050 = "Wählen Sie diese Option, um den Smart-Cast generell einzuschalten.";
VUHDO_I18N_TT_051 = "Wählen Sie dieses Feld, um VuhDo Spieler mit Aggro aufspüren zu lassen.";
VUHDO_I18N_TT_052 = "Wählen Sie diese Option, wenn VuhDo zusätzlich Informationen aus dem Kampflog auswerten soll. Dies beschleunigt i.d.R. die Anzeige.";
VUHDO_I18N_TT_053 = "Wählen Sie den generellen Anzeigemodus aus. Es sollte \"neutral\" ausgewählt sein, solange sie keine Quer-Heilung in grossen Schlatzügen oder im PvP betreiben wollen.";
VUHDO_I18N_TT_054 = "Wählen Sie die maximal gleichzeitig anzuzeigende Anzahl von Notfällen. Irrelevant, wenn der Modus auf \"neutral\" eingestellt ist.";
VUHDO_I18N_TT_055 = "Stellen Sie den maximalen Prozentsatz an Lebensenergie ein, bis zu dem ein Spieler als gesund, d.h. irrelevant für Heilung erachtet wird. Wenn Sie keine Präferenz haben, sollten Sie 100% einstellen.";

VUHDO_I18N_TT_056 = "Wählen Sie diese Option, um Debuffs zu ignorieren, die per se nicht schädlich sind.";
VUHDO_I18N_TT_057 = "Wählen Sie diese Option, wenn Sie Debuffs ignorieren wollen, die lediglich das Bewegungstempo einschränken.";
VUHDO_I18N_TT_058 = "Wählen Sie diese Option, um Debuffs mit sehr niedriger Gesamtdauer zu ignorieren.";
VUHDO_I18N_TT_059 = "Wählen Sie diese Options, um Debuffs zu ignorieren, die für die jeweilige Klasse irrelevant sind (z.B. Manabrand auf Krieger).";
VUHDO_I18N_TT_060 = "Wenn Sie diese Option wählen, werden Ihnen farblich nur die Buffs angezeigt, die sie auch selbst in der Lage sind zu entfernen. Anderenfalls werden alle Debuffs angezeigt.";
VUHDO_I18N_TT_061 = "Wählen Sie diese Option, um die Prüfung auf Debuffs generell zu aktivieren.";
VUHDO_I18N_TT_062 = "Wählen Sie diese Option, um die Überheilung durch Aufhellen des Balkens anzuzeigen.";
VUHDO_I18N_TT_063 = "Wählen Sie diese Option, wenn Sie eingehende Heilung auch anzeigen wollen, wenn diese von Ihnen stammt. Manche Spieler finden dies irritierend, andere mögen es.";
VUHDO_I18N_TT_064 = "Wählen Sie diese Option um eingehende (Heilsrpüche, die begonnen, aber noch nicht vollendet wurden) Heilung anzuzeigen. Dies kann entscheidend zur Vermeidung sog. Overheals beitragen.";
VUHDO_I18N_TT_065 = "Wählen Sie die Aktualisierungsrate für die Reichweitenprüfung. Achtung: Sehr schnelle Aktualisierungsraten können die Systemleistung beeinträchtigen.";
VUHDO_I18N_TT_066 = "Wählen Sie diese Option, um die Reichweitenprüfung pauschal durchzuführen. Dies ist sinnvoll, wenn Ihre Klasse nicht über Heilsprüche verfügt.";
VUHDO_I18N_TT_067 = "Tragen Sie den Namen desjenigen Ihrer Heilsprüche ein, der für die Reichweitenprüfung verwendet werden soll.";
VUHDO_I18N_TT_068 = "Wählen Sie diese Option, um die Reichweitenprüfung gemäß der Reichweite des rechts im Eingabeld eingetragenen Spruchs durchzuführen.";
VUHDO_I18N_TT_069 = "Wählen Sie diese Option, um die Reichweitenprüfung generell zu aktivieren.";

VUHDO_I18N_TT_070 = "Wählen Sie einen Prozentsatz des Balkenhöhe, die das HoT-Symbol gross sein soll";
VUHDO_I18N_TT_071 = "Auswählen, um das HoT-Symbol RECHTS INNEN im Heilbalken anzuzeigen";
VUHDO_I18N_TT_072 = "Auswählen, um das HoT-Symbol LINKS INNEN im Heilbalken anzuzeigen";
VUHDO_I18N_TT_073 = "Auswählen, um das HoT-Symbol LINKS AUSSEN neben dem Heilbalken anzuzeigen";
VUHDO_I18N_TT_074 = "Auswählen, um das HoT-Symbol RECHTS AUSSEN neben dem Heilbalken anzuzeigen";
VUHDO_I18N_TT_075 = "Wählen Sie diese Option, um ein Symbol für Ihre Heilung-über-Zeit-Zauber anzuzeigen";
VUHDO_I18N_TT_076 = "Wählen Sie Ihre bevorzugte Balken-Textur.";
VUHDO_I18N_TT_077 = "Bewegen Sie den Knopf, um die Balkentextur zu wechseln.";
VUHDO_I18N_TT_078 = "Wählen Sie eine Farbe für den Heilfenster-Hintergrund.";
VUHDO_I18N_TT_079 = "Wählen Sie eine Farbe für den Rahmen des Heilfensters.";
VUHDO_I18N_TT_080 = "Wählen Sie diese Option, um auch Energie-Typen ausser Mana anzuzeigen.";
VUHDO_I18N_TT_081 = "Bewegen Sie den Knopf, um die Grösse des Mana-Balkens zu verändern.";
VUHDO_I18N_TT_082 = "Wählen Sie diese Option, um die Anzeige der Mana-Balken zu aktivieren.";

VUHDO_I18N_TT_083 = "Stellen Sie die max. Anzahl der Gruppen pro Zeile ein, wenn \"gruppiert\" angewählt ist.";
VUHDO_I18N_TT_084 = "Wählen Sie diese Option um die Spieler im Fenster lose, d.h. ohne Gruppierung in Gruppen oder Klassen anzuzeigen. Durch Auswahl dieser Option werden die Gruppenüberschriften automatisch ausgeblendet.";
VUHDO_I18N_TT_085 = "Durch Auswahl dieser Option werden die Spieler des Fenster gruppiert nach Klassen, Gruppen etc. angezeigt.";
VUHDO_I18N_TT_086 = "Wenn angewählt werden leere Gruppen des Fensters ausgeblendet. (funktioniert nur, wenn \"gruppiert\" angewählt ist).";
VUHDO_I18N_TT_087 = "Wählen Sie die maximale Zahl an Heilbalken pro Spalte, bevor eine neue Spalte begonnen wird.";
VUHDO_I18N_TT_088 = "Setzt den Ankerpunkt des Fensters in die linke obere Ecke.";
VUHDO_I18N_TT_089 = "Setzt den Ankerpunkt des Fensters in die rechte obere Ecke.";
VUHDO_I18N_TT_090 = "Setzt den Ankerpunkt des Fensters in die linke untere Ecke.";
VUHDO_I18N_TT_091 = "Setzt den Ankerpunkt des Fensters in die rechte untere Ecke.";
VUHDO_I18N_TT_092 = "Zeigt die Spieler in einer Gruppe in der Reihenfolge an, wie sie in der Blizzard-Schlachtzuganzeige erscheinen.";
VUHDO_I18N_TT_093 = "Sortiert die Spieler einer Gruppe absteigend nach den maximalen Lebenspunkten.";
VUHDO_I18N_TT_094 = "Sortiert die Spieler einer Gruppe alphabetisch nach Namen.";

VUHDO_I18N_TT_095 = "Bewegen Sie den Knopf, um die Höhe der Spaltenüberschriften zu ändern.";
VUHDO_I18N_TT_096 = "Bewegen Sie den Knopf, um den Abstand zwischen Spaltenüberschriften un Balken zu justieren.";
VUHDO_I18N_TT_097 = "Wählen Sie diese Option, um die Spaltenüberschriften zu aktivieren. (Note: \"Basic\"=>\"grouped\" must be selected.)";
VUHDO_I18N_TT_098 = "Bewegen Sie den Knopf, um die Hintergrundtextur für die Spaltenüberschriften einzustellen.";
VUHDO_I18N_TT_099 = "Wählen Sie eine Hintergrundtextur für die Spaltenüberschriften.";
VUHDO_I18N_TT_100 = "Stellen Sie die Breite der Spaltenüberschriftentextur als Prozentsatz der Balkenbreite ein.";
VUHDO_I18N_TT_101 = "Stellen Sie die Textgrösse für die Spaltenüberschriften ein.";
VUHDO_I18N_TT_102 = "Wählen Sie diese Option, um die Spaltenüberschriften in Klassenfarben anzuzeigen. (Hinweis: Wirkt sich nur aus, wenn die Spalte eine Klasse repräsentiert)";
VUHDO_I18N_TT_103 = "Wählen Sie eine Farbe für Text und Hintergrund der Spaltenüberschriften.";

VUHDO_I18N_TT_104 = "Passen Sie das Aussehen der Spaltenüberschriften an.";
VUHDO_I18N_TT_105 = "Nehmen Sie grundsätzliche Einstellungen zum Erscheinungsbild der Fenster vor.";
VUHDO_I18N_TT_106 = "Stellen Sie ein, wie die Tooltips aussehen sollen.";
VUHDO_I18N_TT_107 = "Konfigurieren Sie Inhalt und Erscheinung der Balkenbeschriftungen.";
VUHDO_I18N_TT_108 = "Stellen Sie ein, ob und wie die Ziele der Spieler in einem Fenster angezeigt  werden.";
VUHDO_I18N_TT_109 = "Stellen Sie Grössen und Abstände der Balken ein.";
VUHDO_I18N_TT_110 = "Verändern Sie das Aussehen der Balken sowie des Fensterhintergrunds und -rahmens.";
VUHDO_I18N_TT_111 = "Klicken Sie diesen Button, um die Einstellungen des aktuell sichtbaren Untermenüs für alle Fenster zu übernehmen";

VUHDO_I18N_TT_112 = "Stellen Sie die horizontalen Abstände zwischen den Balken ein.";
VUHDO_I18N_TT_113 = "Stellen Sie die vertikalen Abstände zwischen den Balken ein.";
VUHDO_I18N_TT_114 = "Stellen Sie den horizontalen Abstand zum Fensterrand ein.";
VUHDO_I18N_TT_115 = "Stellen Sie den vertikalen Abstand zum Fensterrand ein.";
VUHDO_I18N_TT_116 = "Stellen Sie die Höhe der Gesundheitsbalken ein.";
VUHDO_I18N_TT_117 = "Stellen Sie die Breite der Gesundheitsbalken ein.";

VUHDO_I18N_TT_118 = "Stellen Sie den Abstand zwischen Lebensbalken und Zielbalken ein.";
VUHDO_I18N_TT_119 = "Wählen Sie diese Option um die Spielerziele im aktuellen Fenster einzublenden.";
VUHDO_I18N_TT_120 = "Verändern Sie die Breite des Zielbalkens.";
VUHDO_I18N_TT_121 = "Wählen Sie diese Option, um Schlachtzugssymbol und Zielnamen gleichzeitig anzuzeigen.";
VUHDO_I18N_TT_122 = "Wählen Sie diese Option, um - falls vorhanden - das Schlachtzugssymbol statt des Zielnamens anzuzeigen";
VUHDO_I18N_TT_123 = "Wählen Sie diese Option, wenn Sie immer den Zielnamen anstatt des Schlachtzugssymbols sehen wollen.";
VUHDO_I18N_TT_124 = "Verändern Sie die Textgrösse des Zielnamens.";

VUHDO_I18N_TT_126 = "Wählen Sie diese Option, um die Lebenspunkte als PROZENTZAHL anzuzeigen.";
VUHDO_I18N_TT_127 = "Wählen Sie diese Option, um die FEHLENDEN Lebenspunkte als absolute Zahl anzuzeigen.";
VUHDO_I18N_TT_128 = "Wählen Sie diese Option, um die VERBLEIBENDEN Lebenspunkte als absolute Zahl anzuzeigen.";
VUHDO_I18N_TT_129 = "Diese Option zeigt die Lebenspunkte RECHTS vom Spielernamen";
VUHDO_I18N_TT_130 = "Diese Option zeigt die Lebenspunkte LINKS vom Spielernamen";
VUHDO_I18N_TT_131 = "Diese Option zeigt die Lebenspunkte UNTERHALB des Spielernamens.";
VUHDO_I18N_TT_132 = "Diese Option zeigt die Lebenspunkte OBERHALB des Spielernamens.";
VUHDO_I18N_TT_133 = "Wählen Sie diese Option, um die Lebenspunkte im aktuellen Fenster auf den Gesundheitsbalken anzuzeigen.";
VUHDO_I18N_TT_134 = "Stellen Sie die Textgrösse auf dem Gesundheitsbalken ein.";
VUHDO_I18N_TT_135 = "Wählen Sie diese Option, um den Spielernamen in Klassenfarben anzuzeigen.";
VUHDO_I18N_TT_136 = "Wählen Sie die Textfarbe für den Spielernamen auf den Gesundheitsbalken.";
VUHDO_I18N_TT_137 = "Wählen Sie die Farbe für den Balkenhintergrund (NICHT: Fensterhintergrund).";

VUHDO_I18N_TT_138 = "Diese Option erlaubt Ihnen, die Position der Tooltips frei zu bestimmen. Klicken Sie auf den Demo-Tooltip, um ihn zu verschieben.";
VUHDO_I18N_TT_139 = "Diese Option zeigt die Tooltips immer am Mouse-Cursor an. Achtung: Möglich Auswirkungen auf die Systemleistung!";
VUHDO_I18N_TT_140 = "Diese Option zeigt die Tooltips an der von Blizzard vorgesehenen Standardposition an.";
VUHDO_I18N_TT_141 = "Wählen Sie diese Option, um die Tooltips zu aktivieren.";
VUHDO_I18N_TT_142 = "Wählen Sie diese Option, um Tooltips auch während des Kampfes anzuzeigen.";
VUHDO_I18N_TT_143 = "Justieren Sie die Gesamtgrösse der Tooltips";
VUHDO_I18N_TT_144 = "Wählen Sie eine Hintergrundfarbe für die Tooltips.";
VUHDO_I18N_TT_145 = "Wählen Sie eine Rahmenfabre für die Tooltips.";

VUHDO_I18N_TT_146 = "Wählen Sie diese Option, um die Einstellungen der Tastenkombination \"ALT+UMSCHALT\" zu verändern.";
VUHDO_I18N_TT_147 = "Wählen Sie diese Option, um die Einstellungen der Tastenkombination \"STRG\" zu verändern.";
VUHDO_I18N_TT_148 = "Wählen Sie diese Option, um die Einstellungen der Tastenkombination \"STRG+UMSCHALT\" zu verändern.";
VUHDO_I18N_TT_149 = "Wählen Sie diese Option, um die Einstellungen der Tastenkombination \"ALT+STRG+UMSCHALT\" zu verändern.";
VUHDO_I18N_TT_150 = "Wählen Sie diese Option, um die Einstellungen zu verändern, wenn keine Kombinationstaste gedrückt ist.";
VUHDO_I18N_TT_151 = "Wählen Sie diese Option, um die Einstellungen der Tastenkombination \"ALT\" zu verändern.";
VUHDO_I18N_TT_152 = "Wählen Sie diese Option, um die Einstellungen der Tastenkombination \"UMSCHALT\" zu verändern.";
VUHDO_I18N_TT_153 = "Wählen Sie diese Option, um die Einstellungen der Tastenkombination \"ALT+STRG\" zu verändern.";

VUHDO_I18N_TT_154 = "Klicken Sie hier, um alle Einstellungen zu übernehmen und der Optionsbildschirm zu verlassen.";
VUHDO_I18N_TT_155 = "Klicken Sie hier, um den Optionsbildschirm abzubrechen und alle gemachten Änderungen zu verwerfen.";

VUHDO_I18N_TT_156 = "Wählen Sie diese Option, wenn Sie keinen Zähler für die Anzahl der restlichen Aufladungen eines Buffs sehen möchten.";
VUHDO_I18N_TT_157 = "Wählen Sie dieses Menü, um die Farben der Manabalken zu verändern."
VUHDO_I18N_TT_158 = "Wählen Sie eine Farbe für Mana."
VUHDO_I18N_TT_159 = "Wählen Sie eine Farbe für Wut."
VUHDO_I18N_TT_160 = "Wählen Sie eine Farbe für Energie."
VUHDO_I18N_TT_161 = "Wählen Sie eine Farbe für Runenmacht."
VUHDO_I18N_TT_162 = "In diesem Untermenü können Sie Einstellung bzgl. Aggro/Bedrohung vornehmen."
VUHDO_I18N_TT_163 = "Konfigurieren Sie einige zusätzliche Einstellungen."
VUHDO_I18N_TT_164 = "Laden und Speichern der optischen Einstellungen sowie der Fensteranordnung."
VUHDO_I18N_TT_165 = "Wählen Sie diese Option, um die gesetzten Main Tanks aus den übrigen Fenstern zu entfernen."
VUHDO_I18N_TT_166 = "Wählen Sie diese Option, um die gesetzten Zielgeber aus den übrigen Fenstern zu entfernen."
VUHDO_I18N_TT_167 = "Wählen Sie diese Option, um Ihre jeweils eigene Gruppe nicht als reguläre Gruppe anzuzeigen."
VUHDO_I18N_TT_168 = "Wählen Sie diese Option´, um Spieler zu markieren, die AFK, tot oder nicht eingelogt sind."
VUHDO_I18N_TT_169 = "Wählen Sie diese Option, um die Blizzard Standard Gruppenanzeige auszublenden."
VUHDO_I18N_TT_170 = "Schaltet die Standard-Blizzard Spieleranzeige aus."
VUHDO_I18N_TT_171 = "Wenn gewählt, werden HoTs mit mehreren Zielen nur auf dem direkten Ziel angezeigt."
VUHDO_I18N_TT_172 = "Wenn gewählt, werden HoTs mit mehreren Zielen auf allen Zielen angezeigt. WARNUNG: Negativer Einfluss auf Performance nicht ausgeschlossen!"
VUHDO_I18N_TT_173 = "Wählen Sie die Aktualisierungsrate für die HoT-Anzeige" -- 173
VUHDO_I18N_TT_174 = "Geben Sie den Namen eines Skins ein."
VUHDO_I18N_TT_175 = "Wählen Sie einen Skin. Skins sind alle Einstellungen, die lediglich ästhetischen Nutzen haben."
VUHDO_I18N_TT_176 = "Geben Sie den Namen eines Arrangements ein."
VUHDO_I18N_TT_177 = "Wählen Sie ein Arrangement. Arrangements sind alle Einstellungen, die Position, Größe und Aufteilung der Fenster betreffen."
VUHDO_I18N_TT_178 = "Wählen Sie ab welchem Prozentwert Bedrohung des Bedrohungsbalken von türkis auf violett wechseln soll."
VUHDO_I18N_TT_179 = "Wählen Sie die Höhe des Bedrohungsbalkens"
VUHDO_I18N_TT_180 = "Zeigt gelbe bzw. rote pulsierende Balken an, die generelle Bedrohung der Spieler wiedergibt."
VUHDO_I18N_TT_181 = "Zeigt einen zusätzlichen Balken an, der die Menge an Bedrohung der Spieler wiedergibt."
VUHDO_I18N_TT_182 = "Schaltet die Prüfung der Bedrohung an." -- 182
VUHDO_I18N_TT_183 = "Wählen Sie eine Aktualisierungsrate für die Aggro-Prüfung"
VUHDO_I18N_TT_184 = "Text, der links von Aggro-Habenden angezeigt wird."
VUHDO_I18N_TT_185 = "Zeigt Aggro durch eine Texteinfassung an"
VUHDO_I18N_TT_186 = "Zeigt Aggro durch einen roten (einstellbar) Balken an"
VUHDO_I18N_TT_187 = "Spürt auf, welche Spieler Aggro haben."
VUHDO_I18N_TT_188 = "Text, der rechts von Aggro-Habenden angezeigt wird." -- 188
VUHDO_I18N_TT_189 = "Zeigt den aktuellen Raid als Testeinstellung."
VUHDO_I18N_TT_190 = "Zeigt eine 5-Manngruppe als als Testeinstellung."
VUHDO_I18N_TT_191 = "Zeigt einen 10er Raid als Testeinstellung."
VUHDO_I18N_TT_192 = "Zeigt einen 25er Raid als Testeinstellung."
VUHDO_I18N_TT_193 = "Zeigt einen 40er Raid als Testeinstellung.." -- 193
VUHDO_I18N_TT_194 = "Zeigt die Klassenfarbe statt des rot-grün Verlaufs an."
VUHDO_I18N_TT_195 = "Wählen Sie eine Schriftart für die Spaltenüberschriften."
VUHDO_I18N_TT_196 = "Zeigt den Hintergrund der Überschriften in Klassenfarben."
VUHDO_I18N_TT_197 = "Wählen Sie eine Textfarbe für den Namen des Ziels." -- 197
VUHDO_I18N_TT_198 = "Stellen Sie Zauber für die Maustasten ein."
VUHDO_I18N_TT_199 = "Stellen Sie Zauber für Tastendrücke ein."
VUHDO_I18N_TT_200 = "Stellen Sie ein, welche Trinkets und/oder sofort wirkenden Zauber Sie zusammen mit den Heilsprüchen zünden wollen."
VUHDO_I18N_TT_201 = "Geben Sie den Namen eines Instant-Spruchs ein."
VUHDO_I18N_TT_202 = "Geben Sie den Namen eines Instant-Spruchs ein."
VUHDO_I18N_TT_203 = "Zündet automatisch den Instant rechts."
VUHDO_I18N_TT_204 = "Zündet automatisch den Instant rechts." -- 204
VUHDO_I18N_TT_205 = "Zündet das untere Trinket in der Charakteransicht."
VUHDO_I18N_TT_206 = "Zündet das obere Trinket in der Charakteransicht."
VUHDO_I18N_TT_207 = "Zündet Schmuckstücke auch außerhalb des Kampfes."
VUHDO_I18N_TT_208 = "Zündet Schmuckstücke auch für HoTs."
VUHDO_I18N_TT_209 = "Zündet ggf. angelegte Schmuckstücke automatisch sobald diese bereit sind."
VUHDO_I18N_TT_210 = "Geben Sie einen Text ein, der im Chat ausgegeben wird, wenn Sie eine Wiederbelebung starten. Benutzen Sie \"vuhdo\" als Platzhalter für den Namen.";
VUHDO_I18N_TT_211 = "Wählen Sie diese Option, um einen Text in den Chat auszugeben, wenn Sie eine Wiederbelebung starten. Benutzen Sie \"vuhdo\" als Platzhalter für den Namen.";
VUHDO_I18N_TT_212 = "Wählen Sie diese Option, um alle leeren Fenster vollständig zu verbergen.";
VUHDO_I18N_TT_213 = "Wählen Sie diese Option, um den aktuellen Fokus aus dem Privat-Tank-Fenster zu entfernen.";
VUHDO_I18N_TT_214 = "Wählen Sie diese Option, damit Assistenten nicht ein zweites Mal in der Gruppen-/Raid-Anzeige erscheinen.";
VUHDO_I18N_TT_215 = "Wählen Sie diese Option, um Spieler ohne Buffs automatisch nachzubuffen (nur außerhalb des Kampfes).";
VUHDO_I18N_TT_216 = "Wählen Sie diese Option, um eingehende Heilung anderer Spieler anzeigen zu lassen.";
VUHDO_I18N_TT_217 = "Wählen Sie diese Option, um eingehende Heilung/Überheilung in den Wert der Lebensanzeige mit einzurechnen.";
VUHDO_I18N_TT_218 = "Mit diesem Slider können Sie die Textgröße des Textes zur Anzeige der Überheilung anpassen.";
VUHDO_I18N_TT_219 = "Wählen Sie diese Option, um Überheilung als zusätzlichen Text auf dem Heilbalken anzeigen zu lassen. Dieser Text variiert je nach Höhe der Heilung in seiner Größe.";
VUHDO_I18N_TT_220 = "Wählen Sie diese Option, um Spieler, die Aggro haben, durch einen roten Rahmen um den Gesundheitsbalken zu kennzeichnen.";
VUHDO_I18N_TT_221 = "Wählen Sie diese Option, um die Farben für fehlende Buffs auch während des Kampfes anzeigen zu lassen.";
VUHDO_I18N_TT_222 = "Wählen Sie diese Option, um fehlende Buffs durch die jew. definierte Textfarbe anzuzeigen.";
VUHDO_I18N_TT_223 = "Wählen Sie diese Option, um die Farbe der jew. Begleiterklasse statt der Begleiterfarbe anzuzeigen.";
VUHDO_I18N_TT_224 = "Wählen Sie dieses Menü, um grundlegene Einstellungen der Balkenfarben vorzunehmen.";
VUHDO_I18N_TT_225 = "Wählen Sie dieses Menü, um fortgeschrittene Einstellung für die Farben der HoT-Rechtecke vorzunehmen.";
VUHDO_I18N_TT_226 = "Verändern Sie individuell die Klassenfarben.";
VUHDO_I18N_TT_227 = "Wählen Sie die Helligkeit des Balkenhintergrunds als Prozentsatz der Helligkeit der Balkenfarbe.";
VUHDO_I18N_TT_228 = "Wählen Sie diese Option, um Begleiter in der Farbe ihrer jeweiligen Klasse und nicht der Begleiterfarbe anzuzeigen.";
VUHDO_I18N_TT_229 = "Wählen Sie eine Farbe für Krieger";
VUHDO_I18N_TT_230 = "Wählen Sie eine Farbe für Schurken";
VUHDO_I18N_TT_231 = "Wählen Sie eine Farbe für Jäger";
VUHDO_I18N_TT_232 = "Wählen Sie eine Farbe für Paladine";
VUHDO_I18N_TT_233 = "Wählen Sie eine Farbe für Hexenmeister";
VUHDO_I18N_TT_234 = "Wählen Sie eine Farbe für Schamanen";
VUHDO_I18N_TT_235 = "Wählen Sie eine Farbe für Druiden";
VUHDO_I18N_TT_236 = "Wählen Sie eine Farbe für Priester";
VUHDO_I18N_TT_237 = "Wählen Sie eine Farbe für Magier";
VUHDO_I18N_TT_238 = "Wählen Sie eine Farbe für Todesritter";
VUHDO_I18N_TT_239 = "Wählen Sie eine Farbe für Begleiter";
VUHDO_I18N_TT_240 = "Zeigt die Anzahl Aufladungen eines HoTs. Es werden 1-3 sowie 4 und mehr Aufladungen durch kleine Dreiecke angezeigt.";
VUHDO_I18N_TT_241 = "Zeigt die Anzahl Aufladungen eines HoTs mit der geänderten Textfarbe links an. Die erste Aufladung entspricht der normalen HoT-Farbe";
VUHDO_I18N_TT_242 = "Zeigt die Anzahl Aufladungen eines HoTs mit der geänderten Hintergrundfarbe links an. Die erste Aufladung entspricht der normalen HoT-Farbe.";
VUHDO_I18N_TT_243 = "Wählen Sie eine Farbe, wenn der HoT zwei Aufladungen hat.";
VUHDO_I18N_TT_244 = "Wählen Sie eine Farbe, wenn der HoT drei Aufladungen hat.";
VUHDO_I18N_TT_245 = "Wählen Sie eine Farbe, wenn der HoT vier oder mehr Aufladungen hat.";
VUHDO_I18N_TT_246 = "Wählen Sie eine Farbe für den HoT-Balken 1";
VUHDO_I18N_TT_247 = "Wählen Sie eine Farbe für den HoT-Balken 2";
VUHDO_I18N_TT_248 = "Wählen Sie eine Farbe für den HoT-Balken 3";
VUHDO_I18N_TT_249 = "Wählen Sie eine Farbe für das HOT-Farbfeld 1";
VUHDO_I18N_TT_250 = "Wählen Sie eine Farbe für das HOT-Farbfeld 2";
VUHDO_I18N_TT_251 = "Wählen Sie eine Farbe für das HOT-Farbfeld 3";
VUHDO_I18N_TT_252 = "Wählen Sie eine Farbe für das HOT-Farbfeld 4";
VUHDO_I18N_TT_253 = "Wählen Sie eine Farbe für das HOT-Farbfeld 5";
VUHDO_I18N_TT_254 = "Wählen Sie eine Warnfarbe für auslaufende HoTs.";
VUHDO_I18N_TT_255 = "Wählen Sie ab welcher HoT-Restdauer die Warnfarbe und/oder die erhöhte Präzision angezeigt werden sollen.";
VUHDO_I18N_TT_256 = "Zeigt die HoT-Zähler mit einer Textumrandung an.";
VUHDO_I18N_TT_257 = "Zeigt die HoT-Zähler mit einem Schatten an.";
VUHDO_I18N_TT_258 = "Zeigt eine Warnfarbe für HoTs an der Restdauer unter dem links zu definerenden Wert liegt.";
VUHDO_I18N_TT_259 = "Zeigt das Icon bzw. das Farbfeld für HoTs an. Anderenfalls wird nur der Text von Timer/Counter angezeigt.";
VUHDO_I18N_TT_260 = "Blendet auslaufende HoTs langsam aus.";
VUHDO_I18N_TT_261 = "Wählen Sie eine Farbe für die selbstdefinierten (De)Buffs";
VUHDO_I18N_TT_262 = "Diese Option zeigt reguläre Debuffs - wie selbstefinierte - ebenfalls als Icon an.";
VUHDO_I18N_TT_263 = "Hier können Sie Einstellungen zu Standard-Debuffs vornehmen.";
VUHDO_I18N_TT_264 = "Hier können Sie anzuzeigende Debuffs und Buffs selbst definieren.";
VUHDO_I18N_TT_265 = "Mit dem Fenster-Wizard können Sie die wesentlichen Gruppen-Einstellungen mit wenigen Klicks durchführen.";
VUHDO_I18N_TT_266 = "Zeigt bei selbstdefinierten (De)Buffs mit einem Icon an.";
VUHDO_I18N_TT_267 = "Verändert die Balkenfarbe bei selbstdefinierten (De)Buffs.";
VUHDO_I18N_TT_268 = "Zeigt eine Animation bei selbstdefinierten (De)Buffs an.";
VUHDO_I18N_TT_269 = "Zeigt die Restdauer auf den Symbolen an.";
VUHDO_I18N_TT_270 = "Verändern Sie die Größe des Debuff-Symbole.";
VUHDO_I18N_TT_271 = "Wählen Sie eine Maximalzahl gleichzeitig anzuzeigender Debuff-Icons.";
VUHDO_I18N_TT_272 = "Wählen Sie einen Klang, um das Auftreten eines selbstdefinierten (De)Buffs zu signalisieren.";
VUHDO_I18N_TT_273 = "Zeigt die selbstdefinierten (De)Buffs durch ein Symbol an.";
VUHDO_I18N_TT_274 = "Zeigt die selbstdefinierten (De)Buffs durch Verändern der Balkenfarbe an.";
VUHDO_I18N_TT_275 = "Zeigt einen Animationseffekt beim Einblenden des Icons.";
VUHDO_I18N_TT_276 = "Zeigt die Restdauer auf den Icons an.";
VUHDO_I18N_TT_277 = "Wählen Sie eine Farbe für den Rahmen zur Anzeige Ihres Ziels.";
VUHDO_I18N_TT_278 = "Wählen Sie eine Farbe für den Rahmen um jeden einzelnen Heilbalken.";
VUHDO_I18N_TT_279 = "Wählen sie einen Klang, der gespielt wird, wenn ein Spieler einen Debuff bekommt.";
VUHDO_I18N_TT_280 = "Überträgt die gewählten Einstellungen auf Ihre Fenster.";
VUHDO_I18N_TT_281 = "Zeigt ein extra Fenster für Vehikel an.";
VUHDO_I18N_TT_282 = "Zeigt ein Extrafenster für Begleiter an.";
VUHDO_I18N_TT_283 = "Zeigt ein gesondertes Fenster für Ihre Privat-Tanks an.";
VUHDO_I18N_TT_284 = "Zeigt ein gesondertes Fenster für die Maintanks.";
VUHDO_I18N_TT_285 = "Zeigt den Schlachtzug unsortiert an.";
VUHDO_I18N_TT_286 = "Zeigt den Schlachtzug nach wahrnehmender Rolle an: Tanks, Melees, Ranged-DPS bzw. Heiler.";
VUHDO_I18N_TT_287 = "Zeigt den Schlachtzug klassenweise an.";
VUHDO_I18N_TT_288 = "Zeigt den Schlachtzug nach Gruppen eingeteilt (1-8).";
VUHDO_I18N_TT_289 = "Mit dieser Option können Sie die normale Blizzard Begleiter-Anzeige ausblenden.";
VUHDO_I18N_TT_290 = "Mit dieser Option können Sie die normale Blizzard Spielerziel-Anzeige ausblenden.";
VUHDO_I18N_TT_291 = "Mit dieser Option werden die Zauber gestartet, wenn Sie die Maustaste loslassen statt wenn Sie sie zu drücken.";
VUHDO_I18N_TT_292 = "Mit dieser Option werden die normalen statt der VuhDo-eigenen Tooltips angezeigt.";
VUHDO_I18N_TT_293 = "Wählen Sie diese Option, um einen Begrenzungsrahmen.";
VUHDO_I18N_TT_294 = "Wählen Sie diese Option, um einen Rahmen um die Balken Ihres gegenwärtig gewähltes Ziels anzuzeigen.";
VUHDO_I18N_TT_295 = "Wählen Sie diese Option, um die Buttons des Ziels aufzuhellen, wenn Sie mit der Maus darüber fahren.";
VUHDO_I18N_TT_296 = "Wählen Sie diese Option, um die Buttons des Ziels sowie dessen Gruppe aufzuhellen, wenn Sie mit der Maus darüber fahren.";
VUHDO_I18N_TT_297 = "Wählen Sie, wie Stark die Buttons aufgehellt werden sollen, wenn Sie mit der Maus darüber fahren.";
VUHDO_I18N_TT_298 = "Mit dieser Option wird das gewählte Arrangement bei automatisch aktiviert, wenn Sie in keiner Gruppe sind.";
VUHDO_I18N_TT_299 = "Mit dieser Option wird das gewählte Arrangement bei BIS ZU 5 Spielern automatisch aktiviert.";
VUHDO_I18N_TT_300 = "Mit dieser Option wird das gewählte Arrangement bei BIS ZU 10 Spielern automatisch aktiviert.";
VUHDO_I18N_TT_301 = "Mit dieser Option wird das gewählte Arrangement bei BIS ZU 25 Spielern automatisch aktiviert.";
VUHDO_I18N_TT_302 = "Mit dieser Option wird das gewählte Arrangement bei MEHR ALS 25 Spielern automatisch aktiviert.";
VUHDO_I18N_TT_303 = "Wählen Sie diese Option um die Gesundheitsbalken je nach Gesundheit fließend von grün nach rot zu färben.";
VUHDO_I18N_TT_304 = "Mit dieser Option werden die Gesundheitsbalken in einer einhetlich festen Farbe dargestellt (s. rechts).";
VUHDO_I18N_TT_305 = "Wählen Sie diese Option, um auch den Hintergrund der Gesundheitsbalken in Klassenfarbe darzustellen.";
VUHDO_I18N_TT_306 = "Wählen Sie eine feste Farbe für die Gesundheitsbalken.";
VUHDO_I18N_TT_307 = "Wählen Sie diese Option, damit die Gesundheitsbalken größer statt kleiner werden, wenn ein Spieler Leben verliert.";
VUHDO_I18N_TT_308 = "Wählen Sie diese Option, damit die Gesundheitsbalken von oben nach unten statt von links nach rechts wachsen.";
VUHDO_I18N_TT_309 = "Wählen Sie diese Option, um das Schlachtzugsymbol auf dem Gesundheitsbalken anzuzeigen.";
VUHDO_I18N_TT_310 = "Wählen Sie diese Option, um die Gruppen horizontal statt vertikal auszurichten.";
VUHDO_I18N_TT_311 = "Wählen Sie diese Option, um sich selbst immer zuoberst in ihrer Gruppe anzeigen zu lassen.";
VUHDO_I18N_TT_312 = "Setzt den Ankerpunkt des Fensters in der Mitte oben.";
VUHDO_I18N_TT_313 = "Setzt den Ankerpunkt des Fensters in der Mitte unten.";
VUHDO_I18N_TT_314 = "Setzt den Ankerpunkt des Fensters links in der Mitte.";
VUHDO_I18N_TT_315 = "Setzt den Ankerpunkt des Fensters rechts in der Mitte.";
VUHDO_I18N_TT_316 = "Sortieren Sie die Spieler einer Gruppe nach maximalen Lebenspunkten.";
VUHDO_I18N_TT_317 = "Wählen Sie diese Option, um die Gruppen nach Klassen zu sortieren.";
VUHDO_I18N_TT_318 = "Wählen Sie die Breite der Gesundheitsbalken.";
VUHDO_I18N_TT_319 = "Wählen Sie diese Option, um die HoT-Balken anzeigen zu lassen.";
VUHDO_I18N_TT_320 = "Wählen Sie einen HoT für Balkenposition 3.";
VUHDO_I18N_TT_321 = "Wählen Sie einen HoT für Balkenposition 2.";
VUHDO_I18N_TT_322 = "Wählen Sie einen HoT für Balkenposition 1.";
VUHDO_I18N_TT_323 = "Wählen Sie diese Option, um die Balkenanzeige umzukehren, d.h. größerer Balken = weniger Leben.";
VUHDO_I18N_TT_324 = "Wählen Sie diese Option, um die Gesundheitsbalken vertikal statt horizontal auszurichten.";
VUHDO_I18N_TT_325 = "Zeigt die HoT icons links über dem Gesundheitsbalken";
VUHDO_I18N_TT_326 = "Zeigt die HoT icons rechts unter dem Gesundheitsbalken";
VUHDO_I18N_TT_327 = "Zeigt die HoT icons links unter dem Gesundheitsbalken";
VUHDO_I18N_TT_328 = "Zeigt die HoT icons rechts unter dem Gesundheitsbalken";
VUHDO_I18N_TT_329 = "Zeigt die HoT icons links unter dem Gesundheitsbalken";
VUHDO_I18N_TT_330 = "Diese Option ist nur für Druiden wichtig: Zeigt einen kleinen roten Punkt auf dem Balken, wenn \"Rasche Heilung \" auf dem Ziel möglich ist.";
VUHDO_I18N_TT_331 = "Die HoT-Farbquadrate werden durch eine einfache Textur angezeigt.";
VUHDO_I18N_TT_332 = "Wählen Sie einen HoT für den fünften Platz.";
VUHDO_I18N_TT_333 = "Wählen Sie einen HoT für den vierten Platz.";
VUHDO_I18N_TT_334 = "Wählen Sie einen HoT für den dritten Platz.";
VUHDO_I18N_TT_335 = "Wählen Sie einen HoT für den zweiten Platz.";
VUHDO_I18N_TT_336 = "Wählen Sie einen HoT für den ersten Platz.";
VUHDO_I18N_TT_337 = "Hier finden Sie Einstellungen bzgl. der HoT-Symbole/-Farbquadrate.";
VUHDO_I18N_TT_338 = "Hier finden Sie Einstellungen bzgl. der HoT-Balken";
VUHDO_I18N_TT_339 = "Justieren Sie die Gesamtgröße des Fensters.";
VUHDO_I18N_TT_340 = "Wählen Sie diese Option, um zu verhindern, dass der Lebenstext auf Tausender eingekürzt wird (18437 statt 18.4k).";
VUHDO_I18N_TT_341 = "Wählen Sie diese Option, um der Spielernamen auf den Lebensbalken anzeigen zu lassen.";
VUHDO_I18N_TT_342 = "Wählen Sie diese Option, um die Klasse des Spielers als Text auf den Balken anzeigen zu lassen.";
VUHDO_I18N_TT_343 = "Wählen Sie die maximale Anzahl Zeichen, mit der ein Spielername angezeigt wird.";
VUHDO_I18N_TT_344 = "Wählen Sie einen Zeichensatz für Spielernamen und Lebenstext.";
VUHDO_I18N_TT_345 = "Wählen Sie diese Option, um einen unbeabsichtigten Stance-Wechsel bei Auslösen eines Zaubers zu verhindern.";
VUHDO_I18N_TT_346 = "Mit dieser Option können Sie Informationen über die Click-Cast Spruchbelegung in den Tooltips anzeigen lassen.";
VUHDO_I18N_TT_347 = "Mit dieser Option empfängt der Fensterhintergrund keine Mausklicks mehr. Das ermöglicht es, Ziele anzuklicken und sich zu bewegen. Es ist dann aber nicht mehr möglich, mit Rechtsklick Raid-Leiter usw. zu ermitteln.";
VUHDO_I18N_TT_348 = "Diese Option sperrt die Fenster, um unbeabsichtigtes Verschieben zu verhindern.";
VUHDO_I18N_TT_349 = "Wählen Sie Zaubereinstellungen für gegnerische Ziele";
VUHDO_I18N_TT_350 = "Wählen Sie diese Option, um die Anzahl Aufladungen eines (De)Buffs anzuzeigen.";
VUHDO_I18N_TT_351 = "Verankerung der (De)Buffs oben links.";
VUHDO_I18N_TT_352 = "Verankerung der (De)Buffs oben rechts.";
VUHDO_I18N_TT_353 = "Verankerung der (De)Buffs unten links.";
VUHDO_I18N_TT_354 = "Verankerung der (De)Buffs unten rechts.";
VUHDO_I18N_TT_355 = "Verschieben Sie die (De)Buffs in vertikaler Richtung.";
VUHDO_I18N_TT_356 = "Verschieben Sie die (De)Buffs in horizontaler Richtung.";
VUHDO_I18N_TT_357 = "Wählen Sie diese Option, um ggf. den Namen des Tierbesitzers/Vehikel-Fahrers im Lebenstext anzuzeigen.";
VUHDO_I18N_TT_358 = "Hier können Sie Einstellungen bezüglich automatischer Spruchwahl außerhalb des Kampfes treffen.";
VUHDO_I18N_TT_359 = "Wählen Sie eine Modifikationstaste, unter der die automatische Spruchwahl ausgelöst werden soll.";
VUHDO_I18N_TT_360 = "Anwählen, um während des Kampfes tote Spieler auf Mausklick automatisch wiederzubeleben (nur für Druiden).";
VUHDO_I18N_TT_361 = "Diese Option zeigt die Zielbalken links vom Gesundheitsbalken."
VUHDO_I18N_TT_362 = "Diese Option zeigt die Zielbalken rechts vom Gesundheitsbalken."
VUHDO_I18N_TT_363 = "Wählen Sie die Empfindlichkeit des Schadensblitzens. Je größer der Wert desto geringer der Schaden, der nötig ist, um das Blitzen auszulösen.";
VUHDO_I18N_TT_364 = "Wählen Sie diese Option um den Lebenstext zu verstecken, wenn das Leben überhalb der Irrelevant-Schwelle ist.";
VUHDO_I18N_TT_365 = "Wählen Sie diese Option, um die HoT-Einstellungen zusammen mit der Tastaturbelegung zu laden.";
VUHDO_I18N_TT_366 = "Wählen Sie diese Funktion, um beim Heilen den Geheilten auch gleichzeitg ins Ziel zu nehmen.";
VUHDO_I18N_TT_367 = "In diesem Menü können Sie auswählen, ob und welche Arten eingehender Heilung Sie sehen möchten.";
VUHDO_I18N_TT_368 = "Wählen Sie den spätestens Zeitpunkt in der Zukunft, bis zu dem Sie direkte eingehende Heilung anzeigen möchten.";
VUHDO_I18N_TT_369 = "Wählen Sie diese Option, um direkte Heilung in die eingehende Heilung einzubeziehen.";
VUHDO_I18N_TT_370 = "Wählen Sie den spätestens Zeitpunkt in der Zukunft, bis zu dem Sie kanalisierte eingehende Heilung anzeigen möchten.";
VUHDO_I18N_TT_371 = "Wählen Sie diese Option, um kanalisierte Heilung in die eingehende Heilung einzubeziehen.";
VUHDO_I18N_TT_372 = "Wählen Sie den spätestens Zeitpunkt in der Zukunft, bis zu dem Sie eingehende Heilung aus HoTs anzeigen möchten.";
VUHDO_I18N_TT_373 = "Wählen Sie diese Option, um Heilung aus HoTs in die eingehende Heilung einzubeziehen.";
VUHDO_I18N_TT_374 = "Wählen Sie den spätestens Zeitpunkt in der Zukunft, bis zu dem Sie gebombte eingehende Heilung anzeigen möchten. (z.Zt. Effekt von \"Blühendes Leben\")";
VUHDO_I18N_TT_375 = "Wählen Sie diese Option, um gebombte Heilung in die eingehende Heilung einzubeziehen. (z.Zt. Effekt von \"Blühendes Leben\")";
VUHDO_I18N_TT_376 = "Wählen Sie diese Option, um die Heilbalken unten innerhalb der Gruppe anzuordnen. (bzw. rechts, wenn \"horizontal\" angewählt ist).";
VUHDO_I18N_TT_377 = "Wählen Sie eine Textur für den Rahmen des Fensters.";
VUHDO_I18N_TT_378 = "Wählen Sie die Breite des Rahmens.";
VUHDO_I18N_TT_379 = "Wählen Sie den Abstand des Hintergrunds zum Rahmen.";
VUHDO_I18N_TT_380 = "Filtert Ihren eigenen Heilbalken aus der regulären Raidanzeige heraus.";
VUHDO_I18N_TT_381 = "Vertauscht bei einem Debuff, der die Balkenfarbe ändert die Farbe des Heilbalkens mit der des Hintergundes. Diese Option sollte gewählt sein, wenn Ihre Hintergrundfarbe HELLER ist als die des Heilbalkens.";
VUHDO_I18N_TT_382 = "Zeigt einen Rand (Outline) statt des Schattens um Lebens- und Namenstext.";
VUHDO_I18N_TT_383 = "Keine Pets bei der Buffverfolgung einbeziehen.";
VUHDO_I18N_TT_384 = "Sortiert den Raid, wie in \"Move!\" definiert. Macht nur dann Sinn, wenn Anordnung \"frei\" oben gewählt wurde.";

VUHDO_I18N_TT_385 = "Wählen Sie eine Balkenfarbe für den Fall, dass der Buff fehlt.";
VUHDO_I18N_TT_386 = "Zeigt das Fehlen des Buffs durch die Balkenfarbe an.";
VUHDO_I18N_TT_387 = "Erhöht die Priorität des Buffs.";
VUHDO_I18N_TT_388 = "Verringert die Priorität des Buffs.";
VUHDO_I18N_TT_389 = "Wählen Sie eine Farbe für HoT 6.";
VUHDO_I18N_TT_390 = "Kehrt die Sortierreihenfolge um.";
VUHDO_I18N_TT_391 = "Stellen Sie die Größe der Schlachtzugsymbole ein.";
VUHDO_I18N_TT_392 = "Setzt den Ankerpunkt oben links.";
VUHDO_I18N_TT_393 = "Setzt den Ankerpunkt oben rechts.";
VUHDO_I18N_TT_394 = "Setzt den Ankerpunkt unten links.";
VUHDO_I18N_TT_395 = "Setzt den Ankerpunkt unten rechts.";
VUHDO_I18N_TT_396 = "Setzt den Ankerpunkt links.";
VUHDO_I18N_TT_397 = "Setzt den Ankerpunkt oben.";
VUHDO_I18N_TT_398 = "Setzt den Ankerpunkt unten.";
VUHDO_I18N_TT_399 = "Setzt den Ankerpunkt rechts.";
VUHDO_I18N_TT_400 = "Verändern Sie die horizontale Ausrichtung der Komponente.";
VUHDO_I18N_TT_401 = "Verändern Sie die vertikale Ausrichtung der Komponente.";
VUHDO_I18N_TT_402 = "Einstellungen zu Schlachtzugsymbolen und dem Text für Überheilung.";
VUHDO_I18N_TT_403 = "Speichern sie die aktuelle Tastenbelegung.";
VUHDO_I18N_TT_404 = "Wählen Sie eine gespeicherte Tastenbelegung.";
VUHDO_I18N_TT_405 = "Versteckt das Standard-Fokusfenster.";
VUHDO_I18N_TT_406 = "Die Aufladungen eines HoTs werden nicht angezeigt.";
VUHDO_I18N_TT_407 = "Die verbleibenden Aufladungen eines HoTs werden als Text angezeigt.";
VUHDO_I18N_TT_408 = "Die verbleibenden Aufladungen eines HoTs werden als Dreiecke angezeigt.";
VUHDO_I18N_TT_409 = "Fenster im Solospiel verstecken.";
VUHDO_I18N_TT_410 = "Fenster in 5er-Gruppen verstecken.";

VUHDO_I18N_TT_411 = "Legt die Farben für Schlachtugsymbole fest.";
VUHDO_I18N_TT_412 = "Klicken um die Default-Einstellungen für alle (De)Buffs zu übernehmen.";
VUHDO_I18N_TT_413 = "Wählen Sie eine Farbe für diesen (De)Buff.";
VUHDO_I18N_TT_414 = "Wählen Sie, welche Schlachtzugsymbole angezeigt werden sollen.";
VUHDO_I18N_TT_415 = "Wählen Sie eine Textfarbe für den Überheilung-Text.";
VUHDO_I18N_TT_416 = "Zeigt die Schlachtzugsymbole durch geänderte Balkenfarbe.";
VUHDO_I18N_TT_417 = "Zeigt die Farben nur für Symbole die unter Fenster=>Sonstige definiert sind.";
VUHDO_I18N_TT_418 = "Wählen Sie eine Farbe für dieses Schlachtzugsymbol.";
VUHDO_I18N_TT_419 = "Tank-Modus zeigt nur Spieler an, deren Bedrohungssituation kritisch ist. Gegner, die andere Spieler zufällig ins Ziel nehmen, werden ignoriert.";
VUHDO_I18N_TT_420 = "Nur für Priester: Zeigt die verbleibende Absorption von Schilden. Achtung: EXPERIMENTELL.";

VUHDO_I18N_TT_421 = "Farbe für Spieler bei voller Gesundheit.";
VUHDO_I18N_TT_422 = "Farbe für Spieler bei mittlerer Gesundheit.";
VUHDO_I18N_TT_423 = "Farbe für Spieler bei niedriger Gesundheit."
VUHDO_I18N_TT_424 = "Schaltet die Cluster-Prüfung ein. Ein Cluster ist eine Ansammlung von Spielern in einer bestimmten Reichweite zueinander, wie sie für z.B. Kreis der Heilung oder Kettenheilung erforderlich sind.";
VUHDO_I18N_TT_425 = "Aktualisierungsrate der Cluster-Prüfung.";
VUHDO_I18N_TT_426 = "Setzt den max. Abstand, bis zu dem Spieler als in einem Cluster zueinander befindlich gelten.";
VUHDO_I18N_TT_427 = "Wählt die minimale Gesundheit, ab der Spieler als lohnendes Ziel einer Gruppenheilung gelten.";
VUHDO_I18N_TT_428 = "Wählt die Minimalzahl an Spielern unter dem Gesundheitslevel, die eine Gruppenheilung als angemessen erscheinen lassen.";
VUHDO_I18N_TT_429 = "Wählt die Minimalzahl an Spielern unter dem Gesundheitslevel, die eine Gruppenheilung als optimal erscheinen lassen.";
VUHDO_I18N_TT_430 = "Diese Option wählen, wenn die Gruppenheilung von Ihrem Spieler ausgeht/überspringt (und nicht dem Ziel des Zaubers).";
VUHDO_I18N_TT_431 = "Diese Option wählen, wenn die Gruppenheilung vom Zauberziel ausgeht/überspringt. (und nicht von Ihnen).";
VUHDO_I18N_TT_432 = "Diese Option wählen, wenn theoretisch alle Raidmitglieder von der Heilung getroffen werden können.";
VUHDO_I18N_TT_433 = "Diese Option wählen, wenn nur Ziele getroffen werden können, die sich in der selben Gruppe wie das Zauberziel befinden.";
VUHDO_I18N_TT_434 = "Wählen Sie diese Option, um um alle Spieler (unter dem Gesundheitslevel) einen Rahmen zu zeichnen, die sich im selben Cluster befinden wie der Spieler unter der Maus.";
VUHDO_I18N_TT_435 = "Diese Option schaltet die Anzeige der Anzahl der im Cluster befindlichen Personen im HoT-Icon an.";
VUHDO_I18N_TT_436 = "Zeigt die globale Abklingzeit anhand eines Balkens.";
VUHDO_I18N_TT_437 = "Ermittelt Cluster, die sich kreisförmig um das Ziel befinden.";
VUHDO_I18N_TT_438 = "Ermittelt Cluster, die von einem Spieler zum nächsten springen."
VUHDO_I18N_TT_439 = "Nur für verkettete Heilungen: Theoretische Maximalzahl an Übersprüngen der Kettenheilung.";
VUHDO_I18N_TT_440 = "Wählen Sie eine Farbe für das Cluster-HoT-Icon, wenn das Cluster akzeptabel ist.";
VUHDO_I18N_TT_441 = "Wählen Sie eine Farbe für das Cluster-HoT-Icon, wenn das Cluster optimal ist.";
VUHDO_I18N_TT_442 = "Wählen Sie eine Farbe für die Balkenumrandung zur Cluster-Anzeige.";
VUHDO_I18N_TT_443 = "Wählen Sie Farbe und Transparenz des Balkens für die globale Abklingzeit."

VUHDO_I18N_TT_444 = "Diese Options schaltet das Arrangement bei einer Raid-Stärke von bis zu 15 Spielern ein.";
VUHDO_I18N_TT_445 = "Speichert/lädt die HoT-Einstellungen mit. Nicht auswählen, wenn Sie Arrangements zwischen zwei Klassen tauschen!";
VUHDO_I18N_TT_446 = "Wählen Sie einen Debuff von der Ignorieren-Liste.";
VUHDO_I18N_TT_447 = "Behandelt Tanks aus dem Dungeon-Finder-Tool als Main Tanks und zeigt sie in der Liste der Main Tanks an.";
VUHDO_I18N_TT_448 = "Stellen Sie die Cluster-Erkennung für Ihre Gruppenheilung ein.";
VUHDO_I18N_TT_449 = "Wählen Sie eine Farbe für die Bedrohungsanzeige, wenn die Bedrohung hoch ist.";
VUHDO_I18N_TT_450 = "Wählen Sie eine Farbe für die Bedrohungsanzeige, wenn die Bedrohung niedrig ist.";
VUHDO_I18N_TT_451 = "Schaltet das automatische Nachbuffen über das Mausrad ein.";
VUHDO_I18N_TT_452 = "Wählen Sie ein gespeichertes Bouquet oder geben Sie einen neuen Namen ein.";
VUHDO_I18N_TT_453 = "Wählen Sie ein Spezial-Ereignis oder geben Sie den Namen ein Buffs oder Debuffs ein.";
VUHDO_I18N_TT_454 = "Wählen Sie eine Farbe für das Ereignis.";
VUHDO_I18N_TT_455 = "Wählen Sie ein Icon für das Ereignis. Wählen Sie \"- kein / Default -\" um das Standard-Icon bei Buffs und Debuffs anzuzeigen.";
VUHDO_I18N_TT_456 = "Stellen Sie Indikatoren wie Statusbalken, Rahmen und Icons ein.";
VUHDO_I18N_TT_457 = "Konfigurieren Sie Ihre Bouquets. Bouquets sind priorisierte Listen aus Zaubern und/oder Ereignissen";
VUHDO_I18N_TT_458 = "Zeigt das Buff-Fenster kompakter an.";
VUHDO_I18N_TT_459 = "Geben Sie hier den Namen für ein neues oder zu kopierendes Bouquet ein.";
VUHDO_I18N_TT_460 = "Geben Sie den Namen eines Buffs, Debuffs oder HoTs hier ein.";
VUHDO_I18N_TT_461 = "Wählen Sie eine Farbe für einen leeren Statusbalken.";
VUHDO_I18N_TT_462 = "Wählen Sie eine Farbe für einen mittleren Statusbalkenwert.";
VUHDO_I18N_TT_463 = "Wählen Sie eine Farbe für einen vollen Statusbalken.";
VUHDO_I18N_TT_464 = "Wählen Sie ein Bouquet, das durch diesen Indikator angezeigt werden soll.";
VUHDO_I18N_TT_465 = "Schaltet \"Clique\"-Spruchzuweisungen ein. Achtung: Lädt nach Änderung die UI neu.";
VUHDO_I18N_TT_466 = "Überprüft Mitspieler unabhängig von ihrer Entfernung";
VUHDO_I18N_TT_467 = "Überprüft nur Mitspieler im selben Gebiet.";
VUHDO_I18N_TT_468 = "Überprüft nur Mitspieler innerhalb von 100 Metern.";
VUHDO_I18N_TT_469 = "Überprüft nur Mitspieler innerhalb von 40 Metern.";
VUHDO_I18N_TT_470 = "Prüft die Talentbäume der Mitspieler. Kann Konflikte mit anderen Addons verursachen.";
VUHDO_I18N_TT_471 = "Ändert die Wachstumsrichtung der Balken auf rechts=>links.";
VUHDO_I18N_TT_472 = "Zeigt Spieler durch Aufblitzen der Balken an, die gerade schweren Schaden nehmen.";
VUHDO_I18N_TT_473 = "Zeigt die HoTs mit dem Icon des Zaubers.";
VUHDO_I18N_TT_474 = "Zeigt die HoTs in einer glänzenden Textur.";
VUHDO_I18N_TT_475 = "Profil wird automatisch bei Wechsel zu den primären Taltenten aktiviert";
VUHDO_I18N_TT_476 = "Profil wird automatisch bei Wechsel zu den sekundären Taltenten aktiviert";
VUHDO_I18N_TT_477 = "In diesem Menü können Sie Teile der Konfiguration zurücksetzen";
VUHDO_I18N_TT_478 = "Springen Sie in das Menü zurück, aus dem Sie kamen.";
VUHDO_I18N_TT_479 = "Cluster werden nur angezeigt, wenn der Spruch in dieser Box keinen Cooldown hat. Löschen, um Cluster immer anzuzeigen.";
VUHDO_I18N_TT_480 = "Verändert die Skalierung des Optionsbildschirms";
VUHDO_I18N_TT_481 = "Wählen Sie einen Zeichensatz für HoT-Timer und -Zähler";
VUHDO_I18N_TT_482 = "Stellt die Größe des HoT-Textes ein";
VUHDO_I18N_TT_483 = "Wählen Sie ein Lebensbalken-Bouquet für dieses Fenster, wenn es vom Allgemeinen (Optionen=> Allg. => Indikatoren) abweichen soll.";
VUHDO_I18N_TT_484 = "Ermöglicht PallyPower-kompatible Zuweisung von Buffs und Auren.";
VUHDO_I18N_TT_485 = "Wählen, um Ihr aktuelles Ziel aus dem Privat-Tank-Fenster zu entfernen.";
-- 2.17
VUHDO_I18N_TT_486 = "Sperrt das Profil, um versehentliches Überschreiben zu verhindern.";
VUHDO_I18N_TT_487 = "Verhindert den Benutzerdialog vor Überschreiben eines Profils.";
VUHDO_I18N_TT_488 = "Zeigt den Richtungspfeil nur für tote Spieler.";
VUHDO_I18N_TT_489 = "Zeigt die Entfernung zu Spielern ausser Reichweite.";
VUHDO_I18N_TT_490 = "Zeigt die Richtung zu Spielern ausser Reichweite durch einen Pfeil.";
VUHDO_I18N_TT_491 = "Zeigt den Namen neuer eigener Debuffs für 2 sec über dem Icon.";
-- 2.18
VUHDO_I18N_TT_492 = "Deaktivieren um Notfall-Makros zu erzeugen, die nach einem Disconnect in-fight die Raid-Fenster wiederherstellen können. Es werden zwei freie Makro-Slots je Charakter benötigt."
VUHDO_I18N_TT_493 = "Verändert die Größe des Richtungspfeils."
VUHDO_I18N_TT_494 = "Zielprofil wählen";
VUHDO_I18N_TT_495 = "Exportiert alle derzeitig eingestellten eigenen Debuffs in alle Profile dieses Charakters.";
VUHDO_I18N_TT_496 = "Exportiert alle derzeitig eingestellten eigenen Debuffs in das gewählte Profil.";
VUHDO_I18N_TT_497 = "Exportiert alle derzeitig eingestellten eigenen Debuffs in alle vorhandenen Profile.";



VUHDO_I18N_APPLY_TO_ALL = "für alle"; --nv
VUHDO_I18N_TEST = "Test"; -- nv
VUHDO_I18N_ADD = "Hinzufügen"; --nv
VUHDO_I18N_SELECT = "Wählen"; --nv
VUHDO_I18N_NEW_COLOR = "Neue Farbe"; --nv
VUHDO_I18N_OLD_COLOR = "Alte Farbe"; --nv
VUHDO_I18N_HIDE_CHARGES = "Keine Anzahl"; --nv
VUHDO_I18N_POWERS = "Mana"; --nv
VUHDO_I18N_HOTS = "HoTs"; --nv
VUHDO_I18N_HOT_COLORS = "HoT-Farben"; --nv
VUHDO_I18N_ICONS = "Icons"; --nv
VUHDO_I18N_COUNTDOWN = "Countdown"; --nv
VUHDO_I18N_APPLIANCES = "Aufladungen"; --nv
VUHDO_I18N_FADE_OUT = "Verblassen"; --nv
VUHDO_I18N_POWER_TYPES = "Mana-Typen"; --nv
VUHDO_I18N_THREAT = "Bedrohung"; --nv
VUHDO_I18N_MISC = "Sonst."; --nv
VUHDO_I18N_SKINS = "Skins"; --nv
VUHDO_I18N_PANEL_WIZARD = "Wizard"; --nv
VUHDO_I18N_PRIV_TANKS = "Privat-Tanks"; --nv
VUHDO_I18N_CUSTOM_DE_BUFFS = "Eigene (De)buffs"; --nv
VUHDO_I18N_CHANGE_COLOR = "Farbe Wechseln"; --nv
VUHDO_I18N_ICON = "Icon"; --nv
VUHDO_I18N_ANIMATION = "Animation"; --nv
VUHDO_I18N_STORE = "Sichern"; --nv
VUHDO_I18N_SAVE = "Speichern"; --nv
VUHDO_I18N_DELETE = "Löschen"; --nv
VUHDO_I18N_APPLY = "Anwenden"; --nv
VUHDO_I18N_ADDITIONAL_PANELS = "Zusätzliche Fenster"; --nv
VUHDO_I18N_UNSORT = "Unsortiert"; --nv
VUHDO_I18N_ROLES = "Rollen"; --nv
VUHDO_I18N_CLASSES = "Klassen"; --nv
VUHDO_I18N_GROUPS = "Gruppen"; --nv
VUHDO_I18N_MAIN_PANEL = "Hauptfenster"; --nv
VUHDO_I18N_PARTY = "Gruppe"; --nv
VUHDO_I18N_PET = "Begleiter"; --nv
VUHDO_I18N_TARGET = "Ziel"; --nv
VUHDO_I18N_HIDE_STANDARD = "Standard verstecken..."; --nv
VUHDO_I18N_SINGLE = "Einfach"; --nv
VUHDO_I18N_MULTI = "Multi"; --nv
VUHDO_I18N_HOT_TARGETING = "Globaler Scanner"; --nv
VUHDO_I18N_COLORS_FONTS = "(Farbe/Schriftart)"; --nv
VUHDO_I18N_ARRANGEMENT = "Anordnung";
VUHDO_I18N_SELECT_AN_ARRANGEMENT = "Anordnung wählen"; --nv
VUHDO_I18N_OR_ENTER_PROFILE_NAME = "... oder einen neuen Namen eingeben"; --nv
VUHDO_I18N_GROUPS_SIZES = "(Gruppen/Größen)"; --nv
VUHDO_I18N_SYMBOL = "Symbol"; --nv
VUHDO_I18N_TOP_BAR = "Balken oben"; --nv
VUHDO_I18N_MONITOR_THREAT = "Bedrohung überwachen"; --nv
VUHDO_I18N_USE_ADD_BAR = "zusätzlicher Balken"; --nv
VUHDO_I18N_LINE = "Linie"; --nv
VUHDO_I18N_LEFT = "Links"; --nv
VUHDO_I18N_RIGHT = "Rechts"; --nv
VUHDO_I18N_CHECK_FOR_AGGRO = "Aggro überwachen"; --nv
VUHDO_I18N_CURR = "akt."; --nv
VUHDO_I18N_BAR_COLOR = "Balkenfarbe"; --nv
VUHDO_I18N_PLUS_BG = "+Hintergrund"; --nv
VUHDO_I18N_INV_GROWTH = "Umkehren"; --nv
VUHDO_I18N_VERTICAL = "Vertikal"; --nv
VUHDO_I18N_RAID_ICON = "Raid Icon"; --nv
VUHDO_I18N_YOU_FIRST = "Du zuerst"; --nv
VUHDO_I18N_IICONSI = "[Icons]"; --nv
VUHDO_I18N_ISQUARESI = "[Rechtecke]"; --nv
VUHDO_I18N_HOT_ORDER = "HoT Anordnung"; --nv
VUHDO_I18N_SLOT_5 = "Platz 5"; --nv
VUHDO_I18N_SLOT_4 = "Platz 4"; --nv
VUHDO_I18N_SLOT_3 = "Platz 3"; --nv
VUHDO_I18N_SLOT_2 = "Platz 2"; --nv
VUHDO_I18N_SLOT_1 = "Platz 1 (innen)"; --nv
VUHDO_I18N_TEXT_POSITION = "Textposition"; --nv
VUHDO_I18N_FLAGS = "Flags"; --nv
VUHDO_I18N_SHOW_TEXT = "Text zeigen"; --nv
VUHDO_I18N_KEYS = "Tasten"; --nv
VUHDO_I18N_SPEC_2 = "Spec 2"; --nv
VUHDO_I18N_SPEC_1 = "Spec 1"; --nv
VUHDO_I18N_MANAGE_KEYS = "Tastenbel. verwalten"; --nv
VUHDO_I18N_INSTANT_2 = "Instant 2"; --nv
VUHDO_I18N_INSTANT_1 = "Instant 1"; --nv
VUHDO_I18N_TRINKET_2 = "Trinket 2"; --nv
VUHDO_I18N_TRINKET_1 = "Trinket 1"; --nv
VUHDO_I18N_TRIGGER_WHAT = "Was auslösen..."; --nv
VUHDO_I18N_ALSO_OUT_FIGHT = "+ out-fight"; --nv
VUHDO_I18N_ALSO_HOTS = "+ HoTs"; --nv
VUHDO_I18N_KEEP_STANCE = "Stance bleibt"; --nv
VUHDO_I18N_AUTO_TRIGGER = "Auto-Auslösen"; --nv
VUHDO_I18N_SPELL_ADVICE = "Benutzen Sie die Standard-Tastenbelegung, um die Sprüche unten zuzuweisen. (Scrollen Sie zum Abschnitt 'VuhDo'.)"; --nv
VUHDO_I18N_SAVE_AS = "Speichern..."; --nv
VUHDO_I18N_MOVE = "Move!"; --nv
VUHDO_I18N_SPELLS = "Zauber"; --nv
VUHDO_I18N_PANELS = "Fenster"; --nv
VUHDO_I18N_BUFFS = "Buffs"; --nv
VUHDO_I18N_ICON_SCALE = "Icon-Größe"; --nv
VUHDO_I18N_THICKNESS = "Dicke"; --nv
VUHDO_I18N_WARNING_COLOR_AT = "Warnen ab"; --nv
VUHDO_I18N_THREAT_BAR_HEIGHT = "Höhe Bedrohungsbalken"; --nv
VUHDO_I18N_REFRESH_AGGRO = "Aktualisieren"; --nv
VUHDO_I18N_PANEL_SCALE = "Gesamtgröße Fenster"; --nv
VUHDO_I18N_MAX_CHARS = "Max.Zeichen (0=Alle)"; --nv

-- #+v1.178
VUHDO_I18N_HOSTILE = "Gegnerisch";
VUHDO_I18N_HOSTILE_TITLE = "[FEINDLICH]";
VUHDO_I18N_HOSTILE_ADVICE_1 = "Spruchname oder target/focus/assist"
VUHDO_I18N_HOSTILE_ADVICE_2 = "KEINE Makronamen oder andere Konstanten!!!"
VUHDO_I18N_HOSTILE_ADVICE_3 = "Trinkets etc. werden NICHT autom.gezündet!!!"

-- Slider
VUHDO_I18N_BACKG_BRIGHTNESS = "Helligkeit Hintergr.";
VUHDO_I18N_WARN_PREC_AT = "Warnung/genau ab";
VUHDO_I18N_MAX_NO_DE_BUFFS = "Max. # (de)buffs";
VUHDO_I18N_DEBUFF_SOUND = "Debuff Sound";
VUHDO_I18N_BRIGHTNESS = "Helligkeit";
VUHDO_I18N_RAID_ICON_SCALE = "Größe Raid-Icon";
VUHDO_I18N_NAME_TEXT_SIZE = "Größe Text Name";
VUHDO_I18N_LIFE_TEXT_SIZE = "Größe Text Leben";
-- Color swatches
VUHDO_I18N_BUFF_OKAY = "Buff OKAY";
VUHDO_I18N_BUFF_LOW = "Buff NIEDRIG";
VUHDO_I18N_BUFF_MISSING = "Buff FEHLT";
VUHDO_I18N_OUT_OF_RANGE = "Außer Reichweite";
VUHDO_I18N_COOLDOWN = "Cooldown";
VUHDO_I18N_EMPTY_GROUP = "Leere Gruppe";
VUHDO_I18N_PANEL_BACKGROUND = "Fensterhintergrund";
VUHDO_I18N_SWATCH_BORDER = "Fenster";
VUHDO_I18N_PANEL_BORDER = "Rahmen";
VUHDO_I18N_2ND_CHARGE = "2.Aufladung";
VUHDO_I18N_3RD_CHARGE = "3.Aufladung";
VUHDO_I18N_4TH_CHARGE = "4.Aufladung";
VUHDO_I18N_BAR_1 = "Balken 1";
VUHDO_I18N_BAR_2 = "Balken 2";
VUHDO_I18N_BAR_3 = "Balken 3";
VUHDO_I18N_SQUARE_1 = "Rechteck 1";
VUHDO_I18N_SQUARE_2 = "Rechteck 2";
VUHDO_I18N_SQUARE_3 = "Rechteck 3";
VUHDO_I18N_SQUARE_4 = "Rechteck 4";
VUHDO_I18N_SQUARE_5 = "Rechteck 5";
VUHDO_I18N_EMERGENCY = "Notfall";
VUHDO_I18N_NO_EMEGENCY = "Kein Notfall";
VUHDO_I18N_IRRELEVANT = "Irrelevant";
VUHDO_I18N_INCOMING = "Eingehend";
VUHDO_I18N_MANA = "Mana";
VUHDO_I18N_RAGE = "Wut";
VUHDO_I18N_ENERGY = "Energie";
VUHDO_I18N_RUNES = "Runen";
VUHDO_I18N_DEAD = "Tot";
VUHDO_I18N_OFFLINE = "Offline";
VUHDO_I18N_CHARMED = "Charmed";
VUHDO_I18N_AGGRO_BAR = "Aggro-Balken";
VUHDO_I18N_PLAYER_TARGET = "Eigenes Ziel";
VUHDO_I18N_BAR_FRAME = "Rahmen Balken";
VUHDO_I18N_POISON = "Gift";
VUHDO_I18N_DISEASE = "Krankheit";
VUHDO_I18N_CURSE = "Fluch";
VUHDO_I18N_MAGIC = "Magie";
VUHDO_I18N_HEADER = "Titel";
VUHDO_I18N_TARGET_NAME = "Name Ziel";
VUHDO_I18N_BORDER = "Rahmen";

VUHDO_I18N_AUTO_ENABLE = "autom. aktiveren, wenn bis zu x Spieler:";

VUHDO_I18N_ANOUNCE_RESURRECTION = "Wiederbelebung ankündigen"; -- nv
VUHDO_I18N_FILTER = "Filter"; -- nv
VUHDO_I18N_FOCUS = "Fokus"; -- nv
VUHDO_I18N_BUFF = "Buff"; -- nv
VUHDO_I18N_OTHERS = "Anderer"; -- nv
VUHDO_I18N_LIFE_TEXT = "Lebenstext"; -- nv
VUHDO_I18N_EXTRA_TEXT = "Extra Text"; -- nv
VUHDO_I18N_FRAME = "Rahmen"; -- nv
VUHDO_I18N_1 = " 1"; -- nv
VUHDO_I18N_2 = " 2"; -- nv
VUHDO_I18N_3 = " 3"; -- nv
VUHDO_I18N_4 = " 4"; -- nv
VUHDO_I18N_5 = " 5"; -- nv
VUHDO_I18N_6 = " 6"; -- nv
VUHDO_I18N_7 = " 7"; -- nv
VUHDO_I18N_8 = " 8"; -- nv
VUHDO_I18N_10 = " 10"; -- nv
VUHDO_I18N_25 = " 25"; -- nv
VUHDO_I18N_40 = " 40"; -- nv
VUHDO_I18N_NUM_TRIANGLES = "# / Dreiecke"; -- nv
VUHDO_I18N_DEBUFF_DEFAULTS = "(De)Buff Defaults"; -- nv
VUHDO_I18N_ITEXTUREI = "[Textur]"; -- nv
VUHDO_I18N_BAR = "Balken"; -- nv
VUHDO_I18N_HOTS_2 = "HoTs #2"; -- nv
VUHDO_I18N_PET_CLASS = "Pet-Klasse"; -- nv
VUHDO_I18N_CLASS_COLORS = "Klassenfarben"; -- nv
VUHDO_I18N_HOT_CHARGES = "Aufladungen"; -- nv
VUHDO_I18N_TEXT_COLOR = "Textfarbe"; -- nv
VUHDO_I18N_BACK_COLOR = "Hintergrund"; -- nv
VUHDO_I18N_HOT_BARS = "HoT-Balken"; -- nv
VUHDO_I18N_OUTLINE = "Rahmen"; -- nv
VUHDO_I18N_SHADOW = "Schatten"; -- nv
VUHDO_I18N_WARNING = "Warnung"; -- nv
VUHDO_I18N_MISC_TEXT = "Sonst.Text"; -- nv
VUHDO_I18N_EXPIRY_WARNING = "Ablaufwarnung"; -- nv
VUHDO_I18N_COUNTDOWN_OFF = "Countdown: Aus"; -- nv
VUHDO_I18N_SECS = "secs"; -- nv
VUHDO_I18N_SECS_10 = "sec/10"; -- nv
VUHDO_I18N_FULL_DURATION = "volle Dauer"; -- nv
VUHDO_I18N_TOOLS = "Tools"; -- nv
VUHDO_I18N_TIMER = "Timer"; -- nv
VUHDO_I18N_DEBUFF_OPTIONS = "(De)Buff Optionen"; -- nv
VUHDO_I18N_SOUND = "Sound"; -- nv
VUHDO_I18N_STORE_DELETE = "Speichern/Löschen"; -- nv
VUHDO_I18N_DEBUFF_SOUND = "Debuff Sound"; -- nv
VUHDO_I18N_MOUSE_UP = "Maus hoch"; -- nv
VUHDO_I18N_REACTION_ON = "Reaktion bei..."; -- nv
VUHDO_I18N_TOOLTIP_TYPE = "Tooltip-Typ"; -- nv
VUHDO_I18N_BAR_BORDER = "Rahmen Balken"; -- nv
VUHDO_I18N_UNIT = "Einzeln"; -- nv
VUHDO_I18N_MOUSE_OVER_HIGH = "Mausziel heller"; -- nv
VUHDO_I18N_FLOAT = "Fließend"; -- nv
VUHDO_I18N_SOLIDD = "Einfarbig"; -- nv
VUHDO_I18N_HORIZONTAL = "horizontal"; -- nv
VUHDO_I18N_SLOT_1_2 = "Platz 1"; -- nv
VUHDO_I18N_INVERT_X = "Invertiere X"; -- nv
VUHDO_I18N_INVERT_Y = "Invertiere Y"; -- nv
VUHDO_I18N_FLAT_TEXTURE = "Flach"; -- nv
VUHDO_I18N_HOT_ICONS = "HoT-Icons"; -- nv
VUHDO_I18N_TARGET_OF_TARGET = "Ziel des Ziels"; -- nv
VUHDO_I18N_VERBOSE = "Exakt"; -- nv
VUHDO_I18N_1_DOT = "1."; -- nv
VUHDO_I18N_2_DOT = "2."; -- nv
VUHDO_I18N_3_DOT = "3."; -- nv
VUHDO_I18N_4_DOT = "4."; -- nv
VUHDO_I18N_5_DOT = "5."; -- nv
VUHDO_I18N_6_DOT = "6."; -- nv
VUHDO_I18N_7_DOT = "7."; -- nv
VUHDO_I18N_8_DOT = "8."; -- nv
VUHDO_I18N_9_DOT = "9."; -- nv
VUHDO_I18N_10_DOT = "10."; -- nv
VUHDO_I18N_11_DOT = "11."; -- nv
VUHDO_I18N_12_DOT = "12."; -- nv
VUHDO_I18N_13_DOT = "13."; -- nv
VUHDO_I18N_14_DOT = "14."; -- nv
VUHDO_I18N_15_DOT = "15."; -- nv
VUHDO_I18N_16_DOT = "16."; -- nv
VUHDO_I18N_KEY_BINDINGS = "Tastenbelegung"; -- nv
VUHDO_I18N_MOUSE_WHEEL = "Mausrad"; -- nv
VUHDO_I18N_TOOLTIP_INFO = "Zauber-Info"; -- nv

-- #+1.197
VUHDO_I18N_EDGE_SIZE = "Breite Rand";
VUHDO_I18N_EDGE_INSETS = "Randabstand";

-- #+1.203
VUHDO_I18N_SWAP_WHEN_DEBUFFED = "<->Debuff";

-- #+1.204
VUHDO_I18N_IGNORE_PETS = "Keine Pets";
VUHDO_I18N_PANEL_MODEL = "Modelle";

-- #+1.207
VUHDO_I18N_OVERHEAL_TEXT = "Overheal Text";

-- #+1.210
VUHDO_I18N_NO_STACKS = "Stacks: Aus";
VUHDO_I18N_NUMBER_STACKS = "Text";
VUHDO_I18N_TRIANGLE_STACKS = "Dreiecke";
VUHDO_I18N_HIDE_PANELS = "Ausblenden";
VUHDO_I18N_SOLO = "Solo";

VUHDO_I18N_CLICK_THROUGH = "+Keine Klicks";
VUHDO_I18N_IHEALTH_BARI = "[Lebensbalken]";
VUHDO_I18N_SLOT_6 = "Slot 6 (aussen)";
VUHDO_I18N_SQUARE_6 = "Rechteck 6";
VUHDO_I18N_GLOSSY = "Glänzend";
VUHDO_I18N_DAMAGE_FLASH = "Schadenblitz";
VUHDO_I18N_SENSIVITY = "Empfindlichkeit";
VUHDO_I18N_HIDE_IRRELEVANT = "Nur relevant";
VUHDO_I18N_LOAD_HOTS = "Lade HoTs";
VUHDO_I18N_CASTED = "Direkt";
VUHDO_I18N_CHANNELLED = "Kanalisiert";
VUHDO_I18N_BOMBED = "Gebombt";
VUHDO_I18N_EVENT_HORIZON = "Ereignishorizont";
VUHDO_I18N_ALGINMENT = "Ausrichtung";
VUHDO_I18N_BOTTOM = "Unten";
VUHDO_I18N_PET_OWNERS = "Tierbesitzer";
VUHDO_I18N_BATTLE_REZ = "Battle Rez";


-- #+1.232
VUHDO_I18N_DEBUFF_LIST = "(De)Buff-Liste";
VUHDO_I18N_DEBUFF_EDIT_BOX = "Name eines neuen Buffs oder Debuffs";

-- #+1.233
VUHDO_I18N_BUTTON_6 = "Taste 6";
VUHDO_I18N_BUTTON_7 = "Taste 7";
VUHDO_I18N_BUTTON_8 = "Taste 8";
VUHDO_I18N_BUTTON_9 = "Taste 9";
VUHDO_I18N_BUTTON_10 = "Taste 10";
VUHDO_I18N_BUTTON_11 = "Taste 11";
VUHDO_I18N_BUTTON_12 = "Taste 12";
VUHDO_I18N_BUTTON_13 = "Taste 13";
VUHDO_I18N_BUTTON_14 = "Taste 14";
VUHDO_I18N_BUTTON_15 = "Taste 15";
VUHDO_I18N_BUTTON_16 = "Taste 16";
VUHDO_I18N_TANK_MODE = "Tank-Modus";


-- #+1.237
VUHDO_I18N_CLUSTER_SCANNER = "Cluster-Erkennung";
VUHDO_I18N_CLUSTER_PARAMS = "Cluster-Parameter";
VUHDO_I18N_FAIR_THRESHOLD = "Anzahl akzeptabel";
VUHDO_I18N_GOOD_THRESHOLD = "Anzahl optimal";
VUHDO_I18N_SOURCE_SPELL = "Quelle des Zaubers";
VUHDO_I18N_SOURCE_MINE = "Spieler";
VUHDO_I18N_SOURCE_ALL = "Zauberziel";
VUHDO_I18N_DEST_SPELL = "Ziel des Zaubers";
VUHDO_I18N_DEST_RAID = "Raid";
VUHDO_I18N_DEST_PARTY = "Gruppe";
VUHDO_I18N_CLUSTERS = "Clusters";
VUHDO_I18N_LOW = "Niedrig";
VUHDO_I18N_FAIR = "Mittel";
VUHDO_I18N_GOOD = "Voll";
VUHDO_I18N_HEALTH_LEVEL = "Gesundheit <";
VUHDO_I18N_CLUSTER_FINDER = "Cluster-Erkennung";
VUHDO_I18N_OTHER_HOTS = "HoTs anderer Spieler";
VUHDO_I18N_EMPTY_HOTS = "leer";
VUHDO_I18N_MOUSE_HOVER = "unter Maus";
VUHDO_I18N_COUNTER = "Zähler";
VUHDO_I18N_GLOBAL_COOLDOWN = "Globaler Cooldown";
VUHDO_I18N_GCD = "GCD";

-- #+1.238
VUHDO_I18N_DISPLAY_OPTIONS = "Anzeigeoptionen";
VUHDO_I18N_RADIAL = "Radial";
VUHDO_I18N_CHAINED = "Verkettet";
VUHDO_I18N_CHAINED_MAX_JUMP = "Max.Sprünge der Kette";
VUHDO_I18N_TIMES = " mal";
VUHDO_I18N_SOURCE_DESTINATION = "Quelle/Ziel";

VUHDO_I18N_HIGH = "Hoch";


-- #+1.251
VUHDO_I18N_15 = " 15";
VUHDO_I18N_LOAD_HOTS = "Lade HoTs";
VUHDO_I18N_IGNORE_LIST = "Ignorieren";
VUHDO_I18N_FIVE_MAN_MTS = "5-Mann MTs";
VUHDO_I18N_FILTER_ONLY = "nur Filter";
VUHDO_I18N_LIFE_COLORS = "Lebensfarben";
VUHDO_I18N_SMART_WHEEL = "Smart Wheel";
VUHDO_I18N_PASTE = "Einfügen";
VUHDO_I18N_COPY = "Kopieren";

-- #+1.252
VUHDO_I18N_BOUQUETS = "Bouquets";
VUHDO_I18N_SELECT_OR_ENTER_BOUQUET = "Bouquet wählen ...";
VUHDO_I18N_NEW = "Neu";
VUHDO_I18N_BOUQUET_DETAILS = "Bouquet-Details";
VUHDO_I18N_HIGHEST_PRIO = "Höchste Priorität";
VUHDO_I18N_LOWEST_PRIO = "Niedrigste Priorität";
VUHDO_I18N_ITEM_DETAILS = "Details Bestandteil";
VUHDO_I18N_ENTER_DE_BUFF_OR_SPECIAL = "Ereignis wählen ...";
VUHDO_I18N_ITEM = "Teil";
VUHDO_I18N_SELECT_DEFAULT_ICON = "Icon wählen";
VUHDO_I18N_MINE = "Meine";
VUHDO_I18N_GRADIENT = "Verlauf";
VUHDO_I18N_INDICATORS = "Indikatoren";

VUHDO_I18N_COPIED_BOUQUET = "Bouquet kopiert ";
VUHDO_I18N_BOUQUET_ALREADY_EXISTS = ": Bouquet existiert bereits. Zuerst neuen Namen eingeben.";
VUHDO_I18N_CREATED_NEW_BOUQUET = "Neues Bouquet angelegt: ";
VUHDO_I18N_DELETED_BOUQUET = "Bouquet gelöscht: ";
VUHDO_I18N_BOUQUET_NOT_FOUND = ": Bouquet wurde nicht gefunden.";
VUHDO_I18N_SELECT_STORE_BOUQUET_FIRST = "Wählen Sie zuerst ein Bouquet";
VUHDO_I18N_SELECT_ITEM_FIRST = "Wählen Sie zuerst ein Bestandteil.";
VUHDO_I18N_SELECT_A_PROFILE = "Wählen Sie ein Profil...";
VUHDO_I18N_PROFILES = "Profile";
VUHDO_I18N_EDIT_BUTTON = "Edit...";
VUHDO_I18N_MORE_BUTTON = "Mehr...";
VUHDO_I18N_DONE_BUTTON = "Fertig";
VUHDO_I18N_BASIC = "Basic";
VUHDO_I18N_ADVANCED = "Fortgeschritten";
VUHDO_I18N_EXPERT = "Experte";
VUHDO_I18N_COMPACT = "Kompakt";

VUHDO_I18N_REALLY_DELETE_PROFILE = "Profil wirklich löschen";
VUHDO_I18N_MUST_ENTER_SELECT_PROFILE = "Sie müssen zuerst etwas auswählen.";
VUHDO_I18N_DELETED_PROFILE = "Profil wurde gelöscht";

VUHDO_I18N_TURN_AXIS = "<->Achse";
VUHDO_I18N_DO_NOT_EDIT_BOUQUET = "Generisch: DETAILS NICHT ÄNDERN !";

VUHDO_I18N_OR_NEW_BOUQUET_NAME = "... oder ein neuer Bouquet-Name";
VUHDO_I18N_OR_ENTER_DEBUFF_HOT = "... oder Buff, Debuff oder HoTs";
VUHDO_I18N_TALENT_TREES = "Talentbäume";
VUHDO_I18N_SCAN = "Prüfen";
VUHDO_I18N_INFINITE = "Unbegrenzt";
VUHDO_I18N_SAME_ZONE = "Selbe Zone";
VUHDO_I18N_100_YARDS = "100 Meter";
VUHDO_I18N_40_YARDS = "40 Meter";
VUHDO_I18N_LIFE_TEXT = "Lebenstext";
VUHDO_I18N_BACK = "Zurück";

VUHDO_I18N_CLIQUE_COMPAT_MODE = "Clique verwenden";
VUHDO_I18N_RESET = "Zurücksetzen";
VUHDO_I18N_DEBUFF_COLORS = "Debuff-Farben";
VUHDO_I18N_BUFFS_HOTS = "Buffs/HoTs";
VUHDO_I18N_BUFF_WATCH = "Buff Watch";
VUHDO_I18N_CUSTOM_DEBUFFS = "Eigene Debuffs";
VUHDO_I18N_DEFAULT_BOUQUETS = "Default Bouquets";
VUHDO_I18N_EVERYTHING = "Alles";
VUHDO_I18N_LANGUAGE = "Sprachwechsel";
VUHDO_I18N_PANEL_POSITIONS = "Fensterpositonen";
VUHDO_I18N_PER_PANEL_SETTINGS = "Einst. je Fenster";
VUHDO_I18N_MINUTE = "min.";
VUHDO_I18N_MSEC = "msec";
VUHDO_I18N_PEOPLE = " Spieler";

VUHDO_I18N_RESET_CLASS_COLORS = "Setzt die Einstellungen für\ndie Klassenfarben zurück. Weiter?" ;
VUHDO_I18N_RESET_DEBUFF_COLORS = "Setzt die Einstellungen für\ndie Debuff-Farben zurück. Weiter?";
VUHDO_I18N_RESET_RAID_ICON_COLORS = "Setzt die Farben für\nSchlachtzugsziele zurück. Weiter?";
VUHDO_I18N_RESET_BUFF_WATCH = "Setzt die Einstellungen für\nBuffWatch zurück. Weiter?";
VUHDO_I18N_RESET_CUSTOM_DEBUFFS = "Setzt alle eigenen Debuffs\nund deren Einstellungen zurück. Weiter?";
VUHDO_I18N_RESET_DEFAULT_BOUQUETS = "Setzt alle Standard-Bouquets\n(keine: eigenen) zurück. Weiter?";
VUHDO_I18N_RESET_INDICATORS = "Setzt die Indikatoren-\nkonfiguration zurück. Weiter?";
VUHDO_I18N_RESET_ALL = "!!!ACHTUNG: Dies setzt VuhDo\nvollständig zurück!!! Weiter?" ;
VUHDO_I18N_RESET_LANGUAGE = "Setzt alle Einstellungen nach\nClient-Sprachwechsel zurück. Weiter?";
VUHDO_I18N_RESET_PANEL_POSITIONS = "Setzt die Fenster-\npositionen zurück. Weiter?";
VUHDO_I18N_RESET_PER_PANEL_SETTINGS = "Setzt alle Fenster-\neinstellungen zurück. Weiter?";

-- 2.17
VUHDO_I18N_LOCK = "Sperren";
VUHDO_I18N_QUIET_MODE = "Quiet Mode";
VUHDO_I18N_SETTINGS = "Einstellungen";
VUHDO_I18N_ACTIVATE_DUE_GRP_SIZE = "Automat. aktivieren";
VUHDO_I18N_CUSTOM_HEALTH_BAR_BOUQUET = "Eigenes Gesundheitsbalken-Bouquet";
VUHDO_I18N_CUSTOM_SETTINGS = "Eigene Einstellungen";
VUHDO_I18N_DISTANCE = "Abstand";
VUHDO_I18N_DEAD_ONLY = "nur Tote";
VUHDO_I18N_DIRECTION = "Richtung";
VUHDO_I18N_IF_OOR_SHOW = "Wenn Spieler ausser Reichweite, zeige...";
VUHDO_I18N_DEBUFF_NAME = "Debuff-Name";
-- 2.18
VUHDO_I18N_DISABLE = "Abschalten";
VUHDO_I18N_DC_RESTORE = "d/c-Schild";
VUHDO_I18N_EXPORT_CUSTOM_DEBUFFS = "Export eigene Debuffs";
VUHDO_I18N_EXPORT_TO_PROFILE = "Exportieren zu Profil:";
VUHDO_I18N_THIS_TOONS = "Dieses Chars";
VUHDO_I18N_SELECTED = "Gewähltes";
VUHDO_I18N_ALL = "Alle";
VUHDO_I18N_REPLACE = "Ersetzen";
